### ISSUE TITLE
Allow fine grained workflow retention

### ISSUE THREAD

**Issue by wxing1292** [temporalio/temporal#1000]
**Is your feature request related to a problem? Please describe.**
Currently the workflow retention garrulity is days, we should allow reasonable garrulity, e.g. hours

**Comment by alexshtin** [comment]
I think this is the only place where we still have hardcoded measure unit but DB, I believe, uses correct data type.

**Comment by yiminc** [comment]
I’m not sure what the implication is if user specify a very small retention like a few seconds. Will it cause replication to fail?
maybe we should only allow non-global namespace (those does not enable replications) to have small retention (less than 1 day)?

**Comment by wxing1292** [comment]
> I’m not sure what the implication is if user specify a very small retention like a few seconds. Will it cause replication to fail?
> maybe we should only allow non-global namespace (those does not enable replications) to have small retention (less than 1 day)?

that is the concensus
