### ISSUE TITLE
tctl admin database commands fail on Aurora MySQL

### ISSUE THREAD

**Issue by skrul** [temporalio/temporal#1004]
## Expected Behavior

tctl admin database commands should work on Aurora MySQL

## Actual Behavior

```
# tctl adm namespace list \
>   --db_engine mysql \
>   --db_address $SQL_HOST \
>   --db_port $SQL_PORT \
>   --username $SQL_USER \
>   --password $SQL_PASSWORD \
>   --keyspace $SQL_DATABASE
Error: Failed to initialize metadata manager
Error Details: Error 1193: Unknown system variable 'transaction_isolation'
('export TEMPORAL_CLI_SHOW_STACKS=1' to see stack traces)
```

The `transaction_isolation` variable issue remains to be an issue with Aurora MySQL. We are able to overcome this in the regular service config by specifying connection attributes for the database connection:
```
        connectAttributes:
          tx_isolation: "READ-COMMITTED"
```

However I don't see a way to do this for tctl.

## Specifications

  - Version: 1.1.1
  - Platform: Linux + Aurora MySQL

**Comment by tendulkar** [comment]
did you try passing additional option to tctl like `--ca tx_isolation='READ-COMMITTED'` ?

**Comment by skrul** [comment]
The `--ca` flag does not seem to exist in 1.1.1, I get "Incorrect Usage: flag provided but not defined: -ca"

**Comment by wxing1292** [comment]
@skrul is this issue still relevant ?
