### ISSUE TITLE
Remove 30 days maximum retention limit

### ISSUE THREAD

**Issue by mfateev** [temporalio/temporal#103]
Introduced by https://github.com/uber/cadence/pull/2783
Obviously this is not what most external users want if they have low rate and no archival.

**Comment by kdisneur** [comment]
Is it still an issue you want to tackle? It's probably something we would like to have. 
I see there are an assignee (ping @Ardagan): Can we help somehow?

**Comment by samarabbas** [comment]
@yiminc

**Comment by yux0** [comment]
This limit is removed. https://github.com/temporalio/temporal/pull/3148
