### ISSUE TITLE
Dropped tasks when cancelling polling requests under load

### ISSUE THREAD

**Issue by antstorm** [temporalio/temporal#1058]
## Expected Behavior

When cancelling polling requests workflow & activity tasks should not get dropped, but instead dispatched to a different poller or wait until there's an available poller

## Actual Behavior

Both workflow & activity tasks can get dropped resulting in a timeout and a later retry.

## Steps to Reproduce the Problem

  1. Single worker / server setup, create workflow that schedules lots of parallel activities (e.g. 100)
  2. Start the workflow
  3. Restart the worker (Ctrl+C & launch again) couple times while it's churning through the activities
  4. At this point there should be activity and/or workflow tasks hanging waiting for a timeout and not dispatched to the worker

## Specifications

  - Version: 1.3.2
  - Platform: MacOS X

**Comment by antstorm** [comment]
CC @mfateev

**Comment by wxing1292** [comment]
just some clarification:

if a task is polled by the worker then worker restart, timeout is the correct behavior.

can you check the workflow history events? specifically looking for `WorkflowTaskStarted` and `ActivityTaskStarted`
if above events exists, it means the workers / pollers already have the task and only thing server can do is timeout.

**Comment by antstorm** [comment]
@wxing1292 I'm closely monitoring the GRPC responses on the poller and can confirm that poll requests are getting canceled and no tasks are received when this happens. So it's not like the worker drops these tasks, but more looks like they are dispatched over a cancelled GRPC channel (I'm speculating here).

"Started" events do not exist in these cases, activities time out with the "started_event_id" of zero (see the screenshot attached).

<img width="1422" alt="Screenshot 2020-12-08 at 21 18 55" src="https://user-images.githubusercontent.com/118353/101543029-91935c80-399b-11eb-97ef-4cf32b143101.png">

**Comment by wxing1292** [comment]
@antstorm thanks for reporting the issue, we will look into this

**Comment by wxing1292** [comment]
@antstorm 
could you plz provide the activity timeout settings? especially the schedule to start timeout configuration, seems that the timeout is 10s, meaning the activity is timed out before server able to dispatch the tasks (did not notice the short timeout before.)

**Comment by samarabbas** [comment]
@mmcshane looks like we need some help with reproducing this issue.  The claim is we are dispatching tasks over a cancelled connection.

**Comment by yiminc** [comment]
Not repro.
