### ISSUE TITLE
Add history_size_bytes to WorkflowExecutionInfo and PollWorkflowTaskQueueResponse

### ISSUE THREAD

**Issue by mfateev** [temporalio/temporal#1114]
**Is your feature request related to a problem? Please describe.**
Controlling a workflow history size is important to keep the system performant. None of the existing APIs exposes the aggregated size of the history.

**Describe the solution you'd like**
Add history_size_bytes to WorkflowExecutionInfo (returned from DescribeWorkflowExecution) and PollWorkflowTaskQueueResponse.

**Comment by yiminc** [comment]
Should also expose history size to workflow task started event so workflow code can access this info as well as they might use it to decide if continue as new is needed.
