### ISSUE TITLE
Make consistency level on temporal-cassandra-tool and auto-setup image configurable

### ISSUE THREAD

**Issue by ingyamilmolinar** [temporalio/temporal#1168]
While trying to use Temporal docker image with AWS Keyspaces I get the following error at startup:

>temporal-cassandra-tool --ep cassandra.us-east-1.amazonaws.com validate-health
>2021/01/08 21:31:28 error: failed to connect to 3.234.248.202:9142 due to error: Consistency level ALL is not supported for this operation. Supported consistency levels are: ONE, LOCAL_QUORUM, LOCAL_ONE

This is because AWS Keyspaces [does not support](https://docs.aws.amazon.com/keyspaces/latest/devguide/consistency.html) the consistency level that the CLI tool is defaulting to. A temporal-cassandra-tool CLI argument should be provided to select alternative consistency levels so the tool can be used with the AWS managed service.

Same principle applies regarding the auto-setup docker image. An environmental variable should be provided to control the gocql driver consistency level to avoid any unsupported consistency levels in the cloud.

**Comment by ingyamilmolinar** [comment]
Related open issue: https://github.com/temporalio/temporal/issues/513

**Comment by wxing1292** [comment]
#1189 (begining from 1.6.x) should unblock this issue
