### ISSUE TITLE
Expose ActivityStarted, ActivityCompleted, ActivityTimedOut events to running workflow

### ISSUE THREAD

**Issue by meetchandan** [temporalio/temporal#1175]
If we want to store data about when the activity started, completed or timed out etc so that we can `query` those in Workflow. 
Currently - we have to iterate over workflow history which is slow and not scalable.

**Comment by meetchandan** [comment]
@mfateev - from the discussion we had on slack
https://temporalio.slack.com/archives/CTRCR8RBP/p1609800080341800

**Comment by samarabbas** [comment]
Looks like we have lost the slack conversation.  @mfateev we need more context on this.

**Comment by yiminc** [comment]
Workflow should be able to do this in workflow code.
