### ISSUE TITLE
Please add ActivityCompletionClient support in TestActivityEnvironment

### ISSUE THREAD

**Issue by rubyhfu** [temporalio/temporal#1185]
We are using TestActivityEnvironment to isolate activity testing, but the challenge for us is that we need to inject an ActivityCompletionClient into the activity, which is only available from TestWorkflowEnvironment. I tried this approach and the test didn't work (null pointer exception).. it'd be great if you have an example for testing an isolated activity that uses ActivityCompletionClient. Thanks!

**Comment by wxing1292** [comment]
recreate issue on go SDK, see above
