### ISSUE TITLE
Workflow.Await, Workflow.Sleep to show custom message/additional context about the await/sleep event in history

### ISSUE THREAD

**Issue by kkcmadhu** [temporalio/temporal#1190]
**Is your feature request related to a problem? Please describe.**
When workflow waits on a condition or goes for a sleep , the history in tctl and web shows timer/ sleep activity. but will will be nice if a custom message can be added to give hints on why the workflow went to await or sleep

**Describe the solution you'd like**
Api/sdk enhancement which supports something like
Workflow.await(maxDuration, () -> getApproval(), “waiting for admin Approval”);
Workflow.sleep(Duration.days(2), “waiting for cool of period to get over”);

**Describe alternatives you've considered**

**Additional context**
Workflow history shows the signal names, acticity names, child workflow names, but for workflow.sleep and workflow.await it shows up as Timer'SomeRandomNumber()' , instead custom message could be very meaningful.

**Comment by houseofcat** [comment]
Just adding a thought. A further enhancement would be two events, Entrance and Exit state for the Events.

**Comment by samarabbas** [comment]
History should never be used for business level decisions.  Workflows already support query capability.  You should be setting your application level state and make it accessible through query.  Another useful primitive is `Enhanced Visibility` which even allows you to search workflow executions based on custom criteria.

**Comment by madhukkc** [comment]
hi the original intention of the enhancment request was not to make business decisions , but  to ensure that going throught he history is easy , and human readable.
![image](https://user-images.githubusercontent.com/73097404/124422940-cde83900-dd81-11eb-9c2a-16489197b9c0.png)
