### ISSUE TITLE
Binaries do not build for 386

### ISSUE THREAD

**Issue by ingyamilmolinar** [temporalio/temporal#1207]
## Expected Behavior
I expect binaries to be built successfully with GOOS=linux GOARCH=386

## Actual Behavior
```
$ GOOS=linux GOARCH=386 make bins
Delete old binaries...
Build temporal-server with OS: linux, ARCH: 386...
go build -ldflags '-X go.temporal.io/server/common/metrics.GitRevision=b468ed56 -X go.temporal.io/server/common/metrics.GitBranch=HEAD -X go.temporal.io/server/common/metrics.GitVersion=v1.5.1 -X go.temporal.io/server/common/metrics.BuildDate=2021-01-20-15:38:12 -X go.temporal.io/server/common/metrics.BuildTimeUnix=1611185892' -o temporal-server cmd/server/main.go
# go.temporal.io/server/common/persistence/elasticsearch
common/persistence/elasticsearch/esVisibilityStore.go:829:13: constant -9223372036854775808 overflows int
common/persistence/elasticsearch/esVisibilityStore.go:831:13: constant 9223372036854775807 overflows int
```

## Steps to Reproduce the Problem

  1. `GOOS=linux GOARCH=386 make bins`

## Specifications

  - Version: 1.5.1
  - Platform: Linux

**Comment by houseofcat** [comment]
Well 386 is not a 64-bit system, I anticipate the compiler for these systems do the double stacking int32 when coming across int64 primitives as available - I am not sure how much I even remember from the x86_x64 days to be honest.

This particular value though is an untyped constant of the max value of INT64. This should always fail to compile on a 32-bit OS and x86 bit compiler with over/underflow issues. Read more details on untyped constants in a paragraph [here](https://golang.org/ref/spec#Constants).

This is filed for a revision for Golang v2 and is accepted as is for now [here](https://github.com/golang/go/issues/23086). A work around would be to create your own constant for Temporal that is a typed primitive `MAX_INT64 := int64(math.MaxInt64)`. I don't know if 386 image would compile even that correctly so I don't propose it as a solution.

If you are feeling particularly hackerish/dirty one could convert to using the long as string.

The line that triggers the compilation problem is this:
https://github.com/temporalio/temporal/blob/eee26ca754b6ef37bb7cb07dbf732853075e27b2/common/persistence/elasticsearch/esVisibilityStore.go#L829

`sortVal = math.MaxInt64`

For more Code Context
```golang
func (v *esVisibilityStore) getValueOfSearchAfterInJSON(token *esVisibilityPageToken, sortField string) (string, error) {
	var sortVal interface{}
	var err error
	switch v.getFieldType(sortField) {
	case enumspb.INDEXED_VALUE_TYPE_INT, enumspb.INDEXED_VALUE_TYPE_DATETIME, enumspb.INDEXED_VALUE_TYPE_BOOL:
		sortVal, err = token.SortValue.(json.Number).Int64()
		if err != nil {
			err, ok := err.(*strconv.NumError) // field not present, ES will return big int +-9223372036854776000
			if !ok {
				return "", err
			}
			if err.Num[0] == '-' { // desc
				sortVal = math.MinInt64
			} else { // asc
				sortVal = math.MaxInt64
			}
		}
```

**Comment by wxing1292** [comment]
service logic will use int64 type, so not sure how 32bit mode will work.

for now, i don't think support 32bit will be an option.
