### ISSUE TITLE
Set application_name in Postgres connection string

### ISSUE THREAD

**Issue by chris-rcn** [temporalio/temporal#1208]
**The problem**
Setting application_name informs the database.  The value may be used in logs and metrics, depending on the DB implementation.
See https://www.postgresql.org/docs/9.0/runtime-config-logging.html#GUC-APPLICATION-NAME

**The solution**
Set the application name on the SQL connection somewhere in 
https://github.com/temporalio/temporal/blob/master/common/persistence/sql/sqlplugin/postgresql/plugin.go

**Comment by wxing1292** [comment]
solved by #1214
