### ISSUE TITLE
Possible to set up new cluster with bad database version

### ISSUE THREAD

**Issue by skrul** [temporalio/temporal#1215]
Back in the Temporal 1.3.2 days, I used the following command to create the visibility db, accidentally specifying the wrong version number:
```
temporal-sql-tool \
  --endpoint $VISIBILITY_HOST \
  --port $VISIBILITY_PORT \
  --database $VISIBILITY_DATABASE \
  setup-schema \
  --version 1.1 \
  --schema-file /etc/temporal/schema/mysql/v57/visibility/schema.sql
```

The visibility database schema was only at version 1.0 at the time, but this command did run successfully. The result was that I had a database with the 1.0 schema but the `schema_version` and `schema_update_history` tables said it was version 1.1.

Ideally I would not have been allowed to make this mistake!

**Comment by wxing1292** [comment]
hi,

i checked the code logic. 

the command used above is actually one supported feature, i.e. combining multiple version worth of schema changes into one file to reduce number of changes.

here is usually how we setup / upgrade the schema in dev env:
https://github.com/temporalio/temporal/blob/v1.6.0/Makefile#L324-L325
https://github.com/temporalio/temporal/blob/v1.6.0/Makefile#L328-L329

btw, i will keep the issue open in case
