### ISSUE TITLE
how to join different workflow

### ISSUE THREAD

**Issue by GreedyGrand** [temporalio/temporal#1225]
there are three workflow in different microservice，how to join them。
workflowA in msA，workflowB in msB，workflowC in msC，how to wA->wC->wB

**Comment by wxing1292** [comment]
`wA->wC->wB` (waiting workflow) can be modeled as a parent workflow of `workflowA` / `workflowB` / `workflowC`

within the waiting workflow, execute the following pseudo code:
* start child workflow A (workflow A) and get future A
* future A.Get()
* start child workflow B (workflow B) and get future B
* future B.Get()
* start child workflow C (workflow C) and get future C
* future C.Get()

ref: https://docs.temporal.io/docs/go-child-workflows

**Comment by wxing1292** [comment]
please reopen this issue if you have more questions / comments
