### ISSUE TITLE
docker image temporalio/server:1.6.1   version report 1.6.0

### ISSUE THREAD

**Issue by rmrf** [temporalio/temporal#1226]
## Expected Behavior
docker image temporalio/server:1.6.1  
`temporal-server  -version` will report 1.6.1

## Actual Behavior
```
$ docker run -it --rm temporalio/server:1.6.1 temporal-server -version
temporal version 1.6.0
```

## Steps to Reproduce the Problem

  1. docker run -it --rm temporalio/server:1.6.1 temporal-server -version
  1.
  1.

## Specifications

  - Version:1.6.1
  - Platform: Linux AMD64

**Comment by wxing1292** [comment]
the release version 1.6.1 did not include the necessary change to version number reported by server

versions to be released in the future will correctly report the version (same as docker tag)

**Comment by wxing1292** [comment]
https://github.com/temporalio/temporal/releases/tag/v1.6.2
