### ISSUE TITLE
When running ./temporal-sql-tool I get Unknown system variable 'transaction_isolation'

### ISSUE THREAD

**Issue by jalwandyags** [temporalio/temporal#1251]
When running ./temporal-sql-tool I get Unknown system variable 'transaction_isolation' 
I figured I have to modify the makefile but not too sure where I do this (RDS Mysql), ideas?

**Comment by leowmjw** [comment]
Only applies to older MySQL 5.7 (Aurora RDS MySQL)

Use env to pass in the necessary: 
```
$ SQL_CONNECT_ATTRIBUTES=tx_isolation=“READ-COMMITTED" ./temporal-sql-tool ...
```
More details: https://community.temporal.io/t/aurora-mysql-5-7-on-temporal-v1-3-0/1004

**Comment by wxing1292** [comment]
Please reopen if this above solution does not work
