### ISSUE TITLE
Support cron workflows to (de/re)-schedule themselves

### ISSUE THREAD

**Issue by robzienert** [temporalio/temporal#1256]
**Is your feature request related to a problem? Please describe.**

If a workflow needs to run periodically (cron), but also have the ability to complete itself under certain conditions, the scheduling logic needs to be implemented manually.
After a cron workflow has started, I would like to be able to deschedule (or reschedule) itself if it determines that it no longer needs to run.

**Describe the solution you'd like**

I'd like the ability for workflows to be able to deschedule/reschedule itself through a `Workflow.reschedule` or similar method.

**Describe alternatives you've considered**

Alternative is to implement the scheduling logic manually. I suppose I could also call out to an activity that cancels the workflow execution?

**Comment by yiminc** [comment]
Pause/Resume is supported by the new schedule feature. 
https://docs.temporal.io/workflows#schedule
