### ISSUE TITLE
Cannot run temporal services as non-root user in kubernetes

### ISSUE THREAD

**Issue by sivasamyk** [temporalio/temporal#1263]
## Expected Behavior

Run temporal cluster in kubernetes environment as non-root user. 

Some enterprises have restrictions in k8s environment to block running containers as root user. Kubernetes also recommends running containers as non-root user - https://kubernetes.io/blog/2018/07/18/11-ways-not-to-get-hacked/#8-run-containers-as-a-non-root-user

https://community.temporal.io/t/cannot-run-temporal-services-as-non-root-user-in-kubernetes/1441

## Actual Behavior

Starting temporal containers (using the helm chart from temporal helm chart repo) as non-root user throws the below permission error:

```
dockerize -template /etc/temporal/config/config_template.yaml:/etc/temporal/config/docker.yaml
2021/02/04 14:28:48 unable to create open /etc/temporal/config/docker.yaml: permission denied
```

## Steps to Reproduce the Problem

  1. Create Pod Security Policy (PSP) in kubernetes cluster to block running containers as root user
  2. Adjust Temporal helm charts to include PSP spec with `runAsUser: 1000`
  3. Temporal services fail to start with above error

## Specifications

  - Version: 1.6.2
  - Platform: Kubernetes

**Comment by loopingrage** [comment]
This is blocking us as well. Any update?

**Comment by samarabbas** [comment]
@mcbryde can you drive this request?  I think we need to start scoping out work needed to run Temporal as non-root user.

**Comment by sagardeo2105** [comment]
This is blocker for us as well. It would be really helpful if we can get this pushed. :)
