### ISSUE TITLE
Temporal Cassandra Tools doesn't expost ConnectTimeout

### ISSUE THREAD

**Issue by shiyao-afterpay** [temporalio/temporal#1270]
Temporal Cassandra Tools doesn't expose ConnectTimeout

see https://pkg.go.dev/github.com/gocql/gocql#ClusterConfig. The ConnectTimeout field.

Gocql will fail to connect if the latency between the client and the CASSANDRA_SEED is high.

**Comment by wxing1292** [comment]
the cli actually provides the config for timeout: https://github.com/temporalio/temporal/blob/38c51a43be1c678820d5e62b68442bf5035e161b/tools/cassandra/main.go#L96-L101

**Comment by shiyao-afterpay** [comment]
> the cli actually provides the config for timeout:
> 
> https://github.com/temporalio/temporal/blob/38c51a43be1c678820d5e62b68442bf5035e161b/tools/cassandra/main.go#L96-L101

The flag you referred to is Timeout, not ConnectTimeout.

**Comment by wxing1292** [comment]
#1277
