### ISSUE TITLE
Add build steps for temporal-sql-tool

### ISSUE THREAD

**Issue by unfor19** [temporalio/temporal#1271]
Thank you for this tool, I thought it might be useful for others to build the binaries of this tool, without installing anything (except Docker).

**Is your feature request related to a problem? Please describe.**
I haven't found any git/Docker repo that holds the `temporal-sql-tool` binary. If there's such a repo, please add it as a comment and I'll close this "suggestion".

**Describe the solution you'd like**
Docs should state a clear way of how to build the binaries easily, without installing extra packages, or by storing the binaries somewhere (GitHub/DockerHub)

**Describe alternatives you've considered**
Here's how I built `temporal-sql-tool`, this is relevant to any other tool that is referenced in the Makefile

```bash
$ TEMPORAL_VERSION=1.6.3
$ wget -q -O temporal.tar.gz https://github.com/temporalio/temporal/archive/v${TEMPORAL_VERSION}.tar.gz && \
  tar -xzvf temporal.tar.gz && \
  docker run --rm -it -v $PWD/temporal-${TEMPORAL_VERSION}/:/go/src/internal/temporal --workdir="/go/src/internal/temporal" golang:1.15.7 make temporal-sql-tool
... # building ...
$ sudo chmod +x $PWD/temporal-${TEMPORAL_VERSION}/temporal-sql-tool
$ sudo mv $PWD/temporal-${TEMPORAL_VERSION}/temporal-sql-tool /usr/local/bin/

# test
$ temporal-sql-tool --help
```

The steps above can be added to a Dockerfile (need to remove `sudo`).

**Comment by wxing1292** [comment]
Cassandra /SQL tool is available here: https://hub.docker.com/r/temporalio/admin-tools
