### ISSUE TITLE
CASSANDRA_DATACENTER is hidden in temporal-cassandra-tool create

### ISSUE THREAD

**Issue by shiyao-afterpay** [temporalio/temporal#1278]
The environment variable CASSANDRA_DATACENTER: https://github.com/temporalio/temporal/blob/38c51a43be1c678820d5e62b68442bf5035e161b/tools/cassandra/main.go#L112

Is hidden by subcommand flags with the same name, e.g., create.

An implication is that, no way can we use autosetup:https://github.com/temporalio/temporal/blob/b3b3e7b5ada768a122cd383ed7d28b6383a1d217/docker/start.sh#L29
 with that environment variable.

**Comment by wxing1292** [comment]
> An implication is that, no way can we use autosetup:

auto setup is not intended for production, for production, manually setup your cassandra cluster
