### ISSUE TITLE
func VerifyCompatibleVersion blocks usage of different type of sql plugin

### ISSUE THREAD

**Issue by Lercher** [temporalio/temporal#1292]
... and it also introduces a hard dependency on the two pre-fabricated plugins in tools/sql/handler.go, normally it is only found in main.go files and in tests, where it is ok:

```go
	"go.temporal.io/server/common/persistence/sql/sqlplugin/mysql"
	"go.temporal.io/server/common/persistence/sql/sqlplugin/postgresql"
```

## Expected Behavior

Data schema checking should be handled by a plug-in's method via an interface: I suppose there is the server's expectation of a version number. If so, it should be checked against the used plugin's static version number (via a plugin interface method) and if that succeeds the plugin should be asked to check (or return) the database stored schema version number. If there is any mismatch an error (or a panic?) should be returned by `VerifyCompatibleVersion()` <https://github.com/temporalio/temporal/blob/ee8451102b2ce5b67dc2e3e5b8cb0b02a547ec6a/tools/sql/handler.go#L46>

Without a hard dependency on mysql and pg, their respective drivers and temporal plug-ins doesn't need to be downloaded, built, security checked and delivered for a temporal server built for a different sql plugin.

## Actual Behavior

Version checking is done via a type-switch anti-pattern (see e.g. <https://refactoring.guru/smells/switch-statements>). Moreover there is a panic if an unknown sql plugin type is recognized, effectively rendering the plug-in concept useless for `sql`-kind plug-ins. The hard dependency imports a lot of "dead" i.e. mostly unused code.

## Steps to Reproduce the Problem

  1. copy the server's main.go file
  1. remove the mysql and pg plugin imports
  1. add new plugin code
  1. change development.yaml to load and configure the new `sql` plugin
  2. build and start the server 
  3. notice the panic `"unknown sql store drier: %v"`

For more detailed insight (work in progress for an mssql server plugin, however):

1. clone <https://gitlab.com/lercher/temporal-sqls>
2. remove `replace go.temporal.io/server => ../../../github.com/temporalio/temporal` from `go.mod`
3. cd cmd/server
4. go build
5. ./server start
6. panic

## Specifications

  - Version: 1.5.1
  - Platform: any

## Request

Could you please consider a redesign of the `VerifyCompatibleVersion()` implementation.

**Comment by wxing1292** [comment]
let us try if #1299 can unblock you at least for now.
one thing to mention here, SQL persistence interface is mostly stable, we might make more minor changes in the future.

**Comment by Lercher** [comment]
Thanks for that. I‘m traveling today so that I can’t evaluate it right now, sorry.

Please note, that I wasn’t really blocked in constructing the sql Server plugin, however, I can’t reasonably publish it without such a patch that you provided. Furthermore, I guess I can deal with minor changes in the sql layer. Thanks again.

**Comment by wxing1292** [comment]
the above PR is landed, plz let me know if there are other potential blocking issue

**Comment by Lercher** [comment]
I've upgraded references to go.temporal.io/server@v1.7.0 now and it works with it. Thanks.

---

However @wxing1292, I'm not sure about this issue(?) in schema versioning: is there a flaw using the database name taken from the configuration file as an index into `TABLE schema_version`? Suppose you wanted to put main and visibility both to the same database, what would you insert into the table?

```sql
INSERT into schema_version
  (version_partition, db_name, creation_time, curr_version, min_compatible_version) 
VALUES 
  (0,                 DB_NAME(), GETDATE(),  '1.4',        '1.4') -- for main 1.4 and for visibility 1.1? Can't be both.
;
```

i.e. is `dbKind` a better index than `dbName`?

```go
func checkCompatibleVersion(
	cfg *config.SQL,
	r resolver.ServiceResolver,
	dbKind sqlplugin.DbKind,
) error {
	db, err := NewSQLAdminDB(cfg, r)
	if err != nil {
		return err
	}
	defer func() { _ = db.Close() }()

	// code currently. What about the service resolver (introduced in v1.6)?
	return schema.VerifyCompatibleVersion(db, cfg.DatabaseName, db.ExpectedVersion(dbKind)) 	

	return schema.VerifyCompatibleVersion(db, dbKind, db.ExpectedVersion(dbKind)) // dbKind only, better?
	return schema.VerifyCompatibleVersion(db, cfg.DatabaseName, dbKind, db.ExpectedVersion(dbKind)) // both, even better?
}
```

**Comment by wxing1292** [comment]
> Suppose you wanted to put main and visibility both to the same database
sorry, we only allow dedicated database for main (execution) / visibility

**Comment by wxing1292** [comment]
BTW, you need to use the master branch for the development, e.g. any commit after `c71d197c394aa440338ffd6f36f23a87ef9bad84` (will be part of 1.8)

go.temporal.io/server@v1.7.0 does NOT contain the above commit

**Comment by Lercher** [comment]
I see, concerning exclusive databases. I wasn't aware of this, sorry. It's a non-issue then.

Concerning master vs. v1.7.0: version checking is actually done by the driver in v1.7.0 as requested above. So in fact, I really don't know if your patch was effective or not. However v1.7.0 resolves my issue, so I'm closing this ticket. You may want to re-open it, of course. Thanks for your help and explanations @wxing1292, I appreciate it very much.

**Comment by wxing1292** [comment]
go get go.temporal.io/server@c71d197c394aa440338ffd6f36f23a87ef9bad84

The interface of sql admin db was changed
