### ISSUE TITLE
Feature: provide arm64 builds to Docker Hub

### ISSUE THREAD

**Issue by hazcod** [temporalio/temporal#1305]
**Is your feature request related to a problem? Please describe.**
Running amd64 builds on Apple Silicon is very slow and will trigger a qemu crash on Docker for Mac on Apple Silicon hardware.

**Describe the solution you'd like**
Push builds native to Apple Silicon and ARM in general.

**Additional context**
```
temporal_1    | 2021/02/19 07:15:42 Schema updated from 1.3 to 1.4
temporal_1    | 2021/02/19 07:15:42 UpdateSchemeTask done
temporal_1    | + VISIBILITY_SCHEMA_DIR=/etc/temporal/schema/postgresql/v96/visibility/versioned
temporal_1    | + temporal-sql-tool --plugin postgres --ep postgres -u root -p 26257 create --db temporal_visibility
temporal_1    | + temporal-sql-tool --plugin postgres --ep postgres -u root -p 26257 --db temporal_visibility setup-schema -v 0.0
temporal_1    | qemu: uncaught target signal 11 (Segmentation fault) - core dumped
temporal_1    | /start.sh: line 68:    64 Segmentation fault      temporal-sql-tool --plugin postgres --ep $POSTGRES_SEEDS -u $POSTGRES_USER -p $DB_PORT --db $VISIBILITY_DBNAME setup-schema -v 0.0
```

**Comment by houseofcat** [comment]
Not a Temporal Server issue.

https://github.com/docker/for-mac/issues/5123

**Comment by hazcod** [comment]
I guess it's still nice to be able to push native `arm64` builds now go `1.16` is out.

**Comment by hazcod** [comment]
FYI now temporal builds with Go 1.16, we should push arm64 builds.

**Comment by hazcod** [comment]
@wxing1292 FYI we're still not pushing arm64 builds to Docker hub.

**Comment by pquerna** [comment]
Also needs `temporalio/base-builder` to have an arm build: https://hub.docker.com/r/temporalio/base-builder

**Comment by alexshtin** [comment]
With #1575 merged it becomes easier to build ARM images. I did it locally with simple command:
```
docker buildx build --platform linux/arm64 --output type=image .
```

We will consider building adding ARM to our release images.

**Comment by hazcod** [comment]
Is there an ETA on this? :-)
I still can't run temporal on my development machines.

**Comment by feedmeapples** [comment]
there is a set of new GHA pipelines that build arm images:

build & release of base*-images
https://github.com/temporalio/docker-builds/actions/workflows/release-base-image.yml

build of `server`, `admin-tools` and `auto-setup` images:
https://github.com/temporalio/docker-builds/actions/workflows/docker.yml

release of `server`, `admin-tools` and `auto-setup` images:
https://github.com/temporalio/docker-builds/actions/workflows/release-temporal.yml
