### ISSUE TITLE
Allow only connect to the CASSANDRA_SEED nodes and not others

### ISSUE THREAD

**Issue by shiyao-afterpay** [temporalio/temporal#1309]
Given the CASSANDRA_SEEDS, Temporal-server/cassandra-tools will contact the seed nodes and then connect to **other** nodes returned from the seeds. However, some of the returned nodes cannot be connected due to network policy issues.

In our setup, we use a managed **multi-dc** Cassandra service. Due to regulation compliance, Cassandra application *client* residing in one area  cannot establish network connections to other data centers.

The problem is Temporal-server/Cassandra-tools is constantly making connections to the discovered nodes in Cassandra, including those in *the other* dc.

1. Can we tell Temporal-server/Cassandra to only connect to Cassandra nodes in a specific DC ?
2. If not, can we tell Temporal-server/Cassandra to only connect to the nodes specified in CASSANDRA_SEEDS as we can populate this variable with Cassandra nodes only in the current DC ?

**Comment by houseofcat** [comment]
I am just a user, but here's my two cents.

1) I don't think is possible by currently and partly by design - I will suggest an alternative. The design part has to do with service discovery, recovery of nodes, and additional nodes at runtime. This allows seamless integration and failover of individual nodes with a hands off approach.

2) Absolutely, you can restrict which nodes a cluster can see by removing or truncating the table and re-adding the only ones you want. The catch here is that the nodes that can still reach the Cassandra instance(s) will join back as available services for the same reasons I mention above.
     
In a multi-DC setup, you more than likely should have two Temporal Clusters pointing to two Cassandra instances based on your own restrictions `one area cannot establish network connections to other data centers`.

**Comment by houseofcat** [comment]
Possibly related to #1234

**Comment by shiyao-afterpay** [comment]
> 2\. Absolutely, you can restrict which nodes a cluster can see by removing or truncating the table and re-adding the only ones you want. The catch here is that the nodes that can still reach the Cassandra instance(s) will join back as available services for the same reasons I mention above.

Hi, let me clarify the current configuration: 
We have two DCs, DC-a, and DC-b.

The Cassandra nodes in DC-a and DC-b can connect to each other.  There is no network restriction. However, the Cassandra client (for example, Temporal) in one DC cannot make connection to Cassandra nodes in the other DC. 

Problem is Temporal will unconditionally make connections to the nodes return from CASSANDRA_SEEDS, which will contain nodes in **both* DC.

So the remedy I posted in the initial question is:
> Can we tell Temporal-server/Cassandra to only connect to Cassandra nodes in a specific DC ?
> 
> If not, can we tell Temporal-server/Cassandra to only connect to the nodes specified in CASSANDRA_SEEDS as we can populate this variable with Cassandra nodes only in the current DC ?

**Comment by shiyao-afterpay** [comment]
> Possibly related to #1234

The problem is not related to #1234. In #1234, two Temporal clusters can communicate with each other. In our problem, there is only one Temporal cluster but it connects to the Cassandra nodes in multiple DCs.

**Comment by shiyao-afterpay** [comment]
@wxing1292 I noticed that there is already a knob `Datacenter` to filter out hosts based on datacenter, see https://github.com/temporalio/temporal/blob/35a9646bf120e5b16afb7914a8e6424976f48f91/common/service/config/config.go#L267.  However, it seems it is not exposed here: https://github.com/temporalio/temporal/blob/cf2047195d424f13e38cb3880865d2be98e277a3/tools/cassandra/cqlclient.go#L147

**Comment by wxing1292** [comment]
@shiyao-afterpay let me know if #1315 can fix the issue you are facing.

**Comment by shiyao-afterpay** [comment]
@wxing1292 Thanks for the quick fix.

AFAIK, Temporal has two concepts of *datacenter*s, one is to create the keyspace with network aware topology (cassandra itself side), another is to filter hosts (gocql side).

The fix seems to combine the two concepts together.  Also see another related issue: https://github.com/temporalio/temporal/issues/1278


**That said, the fix should solve the connectivity problem.** But I haven't tested yet.  Is there any nightly docker image release for Temporal?

**Comment by wxing1292** [comment]
@shiyao-afterpay 

> AFAIK, Temporal has two concepts of datacenters, one is to create the keyspace with network aware topology (cassandra itself side), another is to filter hosts (gocql side).

not an cassandra configuration expert, but i assume #1315 will fix the issue, ref: https://github.com/temporalio/temporal/blob/v1.7.0/common/cassandra/cassandraCluster.go#L64

about docker, try:
`temporalio/server:latest`
`temporalio/auto-setup:latest`
`temporalio/admin-tools:latest`
`temporalio/tctl:latest`
or
```zsh
docker build . -t server-auto-setup:local --build-arg TARGET=auto-setup
docker build . -t server:local --build-arg TARGET=server
```

**Comment by shiyao-afterpay** [comment]
Thanks.

Will test it.

>
