### ISSUE TITLE
Temporal sends queries to workflows which are created but not started

### ISSUE THREAD

**Issue by robholland** [temporalio/temporal#1310]
## Expected Behavior

Temporal ignores queries to workflows which were created due to cron schedules not yet started.

## Actual Behavior

Temporal responds to poll requests with the query set and a history with only one event, WorkflowExecutionStarted.

## Steps to Reproduce the Problem

  1. Create a workflow using a cron schedule so it won't start immediately
  1. Send a query to the workflow before it's due to start
  1. Workers will receive the workflow via poll response

If the ruby SDK is being used this will currently raise an exception as it attempts to find a workflow task to begin but the expected history is not there.

## Specifications

  - Version: 1.6.0
  - Platform: Linux

**Comment by robholland** [comment]
Diagnosed with @wxing1292

**Comment by yiminc** [comment]
Fixed by https://github.com/temporalio/temporal/pull/2826
