### ISSUE TITLE
Provide a way to define searchAttributes on a per-namespace basis

### ISSUE THREAD

**Issue by skrul** [temporalio/temporal#1332]
**Is your feature request related to a problem? Please describe.**

Global mappings of searchAttributes can lead to collisions between namespaces.

**Describe the solution you'd like**

Have some way to define searchAttributes on a per-namespace basis

**Describe alternatives you've considered**

Prefixing each searchAttribute with a per-namespace string

**Comment by samarabbas** [comment]
Search attributes are scoped at cluster level.  Currently there are no plans for namespace level search attributes.
