### ISSUE TITLE
Remove namespace registration delay

### ISSUE THREAD

**Issue by mfateev** [temporalio/temporal#1336]
**Is your feature request related to a problem? Please describe.**
From a [forum post](https://community.temporal.io/t/how-to-tell-the-namespace-is-ready-to-be-polled-by-workers/1606):
>  Hi Temporal team!
I’m looking for ways to simplify Temporal development experience for new engineers from my organization. As part of that, I’ve created a small generic code that could automatically create a namespace on worker/starter application startup. The idea is to have it off for staging and production (so namespaces have to be manually created there) but be able to automatically create required namespaces on a local machine.
To do that, I make a DescribeNamespace call and it fails, make a RegisterNamespace call. This works fine in the sense that namespace is created and is visible in Temporal web, however, it’s not immediately “useful” as for ~10-15 seconds after namespace was created requests fail with `io.grpc.StatusRuntimeException: NOT_FOUND: namespace: basic_worker-namespace not found`
I tried to run another DescribeNamespace call after RegisterNamespace but it succeeds and indicated the namespace is already created. Same with ListNamespaces.
The best workaround I’ve found for now is to make a GetWorkflowExecutionHistory request for some fake workflow id. If it fails with status code NOT_FOUND I deduce the namespace is not propagated yet, once it fails with INVALID_ARGUMENT I assume the namespace is ready and I can let worker and client request go.
Is there a way to tell that the namespace is “ready” and other calls can be initiated? I feel I’m missing something pretty obvious.

**Describe the solution you'd like**
Namespace registration is synchronous. I.e. after the `RegisterNamespace` returned then it can be used without errors.

If it is not possible to implement at scale reduce the delay to at most a second in a locally deployed Temporal version.

**Comment by bergundy** [comment]
Experiencing the same issue with the NodeJS SDK integration tests.
Getting `NOT_FOUND: namespace: default not found` after a successful `describeNamespace()` call.

**Comment by bergundy** [comment]
Ideally there should be a way to reliably know if namespace registration is complete or not instead of the current workaround (which sometimes fails in CI as well).

**Comment by yiminc** [comment]
The namespace cache should read through (with proper rate limiting) if it cannot find the requested namespace.
There should be no delay between namespace is registered and become available for use. 
This is not only for local environment.

**Comment by bergundy** [comment]
It would be great if we could prioritize this, it seems like a small effort server-side and would result in better experience for anyone creating server environments for testing.
