### ISSUE TITLE
tctl: Make it easy to export JSON version of history

### ISSUE THREAD

**Issue by mfateev** [temporalio/temporal#1339]
**Is your feature request related to a problem? Please describe.**
It is very hard to discover how to export a workflow history in JSON format. It is not found anywhere in tctl help. You have to specify `--output_filename` parameter in `workflow show` command. And the file will contain JSON.

**Describe the solution you'd like**
Explicit flag that specifies output format. I would replace `--print_full` flag with `--outuput_format` that can be `short`, `full`, `json`, etc.

**Comment by GreyTeardrop** [comment]
I really like this idea. It would also simplify running tctl as a Docker container as one won't have to mount a volume into it.

**Comment by mikhailshilkov** [comment]
The `--output_filename` command does save the history as a JSON. However, the `data` properties are base64 encoded, it seems, so they aren’t human-readable at all.

```json
{
   "eventId": "17",
   "eventTime": "2021-03-01T09:48:53.967033371Z",
   "eventType": "WorkflowExecutionCompleted",
   "taskId": "1054959",
   "workflowExecutionCompletedEventAttributes": {
    "result": {
     "payloads": [
      {
       "metadata": {
        "encoding": "anNvbi9wbGFpbg=="
       },
       "data": "eyJIaXN0b2dyYW0iOnsiSnNvbiI6W3siU3RhcnRlZCI6NiwiQ2xvc2VkIjo2LCJCYWNrbG9nIjowfV0sIkNzdiI6IlRpbWUgKHNlY29uZHMpO1dvcmtmbG93cyBTdGFydGVkO1dvcmtmbG93cyBTdGFydGVkIFJhdGU7V29ya2Zsb3cgQ2xvc2VkO1dvcmtmbG93IENsb3NlZCBSYXRlO0JhY2tsb2dcbjYwOzY7MC4xMDAwMDA7NjswLjEwMDAwMDswIn19"
      }
     ]
    },
    "workflowTaskCompletedEventId": "16"
   }
```

**Comment by samarabbas** [comment]
@feedmeapples will this be addressed by your recent tctl enhancements?

**Comment by feedmeapples** [comment]
a unified `--output` flag is added in this proposal that applies to all commands that do print some sort of golang objects (lists, iteration), including the one for History https://github.com/temporalio/proposals/pull/31

It's also implemented in tctl repo
