### ISSUE TITLE
Report state transition number for workflows

### ISSUE THREAD

**Issue by mikhailshilkov** [temporalio/temporal#1352]
**Is your feature request related to a problem? Please describe.**
I want to evaluate a "complexity" metric of a workflow execution - how much load burden it puts on the Temporal server. See https://github.com/mikhailshilkov/temporal-bench/issues/4 for context.

**Describe the solution you'd like**
Temporal server should add this counting feature to the history service. So every workflow should return the number of state transitions it used and include it into the visibility record on close.

**Comment by samarabbas** [comment]
@mikhailshilkov @alexshtin I thought we already added support for reporting state transitions both as metric and visibility records.  Can this issue be closed now?

**Comment by alexshtin** [comment]
Yes, this field is added to workflow mutable state and also to advanced visibility.
