### ISSUE TITLE
temporal-history throws "unknown protocol version 80877102" for CockroachDB

### ISSUE THREAD

**Issue by deltasquare4** [temporalio/temporal#1369]
## Expected Behavior
It should not crash, and not throw the pg protocol error below.

## Actual Behavior
It crashes with error `unknown protocol version 80877102` when we enabled Archival. With Archival disabled, it runs fine. Seems to be related to use of cancel query. See https://github.com/cockroachdb/cockroach/issues/31763 for corresponding issue on CockroachDB repo.

## Steps to Reproduce the Problem

  1. Deploy Temporal using official Helm chart on Kubernetes 1.16. Configure cockroachdb as a backend to both the databases.
  1. Enable Archival by adding custom configuration.
 
## Specifications

  - Version: 1.7.0
  - Platform: Kubernetes 1.16 + CockroachDB 20.2.5

**Comment by wxing1292** [comment]
about `unknown protocol version 80877102`, can you provide the stack trace?

**Comment by fire** [comment]
Is there anything I can push for CockroachDB support here?

**Comment by wxing1292** [comment]
> Is there anything I can push for CockroachDB support here?

CockroachDB [claims](https://www.cockroachlabs.com/docs/v20.2/postgresql-compatibility) to be wire compatible with PostgreSQL 9.5

From my local unit testing, all queries used by Temporal works.
Right now the only reason that CockroachDB is not officially supported is we do not have CICD setup for CockroachDB.

about `unknown protocol version 80877102`, not entirely sure what happened here, at least if you do not use archival (which is experimental) you should be fine.

**Comment by samarabbas** [comment]
@wxing1292 is this still actionable?  Or should we close the issue?

**Comment by wxing1292** [comment]
We can choose to close this issue for now and welcome contribution due to the following reason:

* the error seems to be cockroach db not entirely compatible with postgresql 9.5 protocol?
* other oss & cockroach db users did not report this issue
* archival is still experimental
* we currently only officially support postgresql 9.6

**Comment by deltasquare4** [comment]
I'm sorry, I missed the email notifiactions from earlier. We have since moved on to using postgres backing Temporal, so I cannot provide a stacktrace at the moment. Closing this for now until we have more people wanting to use CockroachDB with Temporal.
