### ISSUE TITLE
Bad arguments to temporal-sql-tool should return non-zero status.

### ISSUE THREAD

**Issue by drewhoskins-stripe** [temporalio/temporal#1370]
## Expected Behavior
Bad arguments to temporal-sql-tool should return non-zero status.

## Actual Behavior
Returns 0.  This makes it impossible to integrate into a wrapping script that needs to react to whether it succeeds or fails.

## Steps to Reproduce the Problem

     temporal-sql-tool --ca tx_isolation='READ-COMMITTED' --ep myhost.com -p 3306 -u root -pw a_password create --plugin mysql --db temporal
    Incorrect Usage: flag provided but not defined: -plugin

    NAME:
       temporal-sql-tool create-database - creates a database

    USAGE:
       temporal-sql-tool create-database [command options] [arguments...]

    OPTIONS:
       --database value, --db value  name of the database

    echo $?
    0

## Specifications

  - Version: SHA: f46efbb1d85e5ab4bb88b28f12b595c89b95ee6c
  - Platform:

**Comment by yiminc** [comment]
https://github.com/temporalio/temporal/pull/5204
