### ISSUE TITLE
Docker config template should allow different DB address for main and visibility database

### ISSUE THREAD

**Issue by wxing1292** [temporalio/temporal#1388]
example:
https://github.com/temporalio/temporal/blob/42c114f55cbe13c27b177e8e5b0486b3ffbe6912/docker/config_template.yaml#L56
https://github.com/temporalio/temporal/blob/42c114f55cbe13c27b177e8e5b0486b3ffbe6912/docker/config_template.yaml#L71

**Comment by alexshtin** [comment]
Same for username and password.
