### ISSUE TITLE
Is there a way to reduce db queries?

### ISSUE THREAD

**Issue by freshtech2021** [temporalio/temporal#1406]
Temporal fires 3000 queries in a single minute? Is there a way to reduce db queries? It causes too much load on my db.

I guess it's scanning db for tasks, so can i adjust interval mannually?

**Comment by samarabbas** [comment]
Can you provide more details about the setup and workload you are running when this happens.  Which query are you talking about?

**Comment by freshtech2021** [comment]
I know it's tempral quering the database.  I want to see a config option to reduce the query intervals.

![image](https://user-images.githubusercontent.com/2658286/114311515-aaff0d80-9b21-11eb-99c0-d0f25874d707.png)

**Comment by wxing1292** [comment]
it will be easier to talk in our slack channel:
https://join.slack.com/t/temporalio/shared_invite/zt-onhti57l-J0bl~Tr7MqSUnIc1upjRkw
