### ISSUE TITLE
Allow server to track client language and version by namespace

### ISSUE THREAD

**Issue by rfwagner** [temporalio/temporal#1427]
It would be very useful to enhance the frontend gRPC protocol to be allow the server to track source language and client version being used by every client that connects to the frontend. This information should be tracked by namespace as well. 

Other useful information such as client IP and client identifier should be tracked also - basically any useful piece of information from the client should be considered as something to be tracked.

This information should be collected in such a way that it is relatively easy for operators to track down all users of version X of source language client Y, at the very least by namespace and ideally by more specific information including client identifier and IP.

This kind of tracking would be invaluable in situations where certain client versions are known to have buggy or insecure behavior, less-than-ideal performance etc. It will allow operators to more easily contact the owners of the associated worker apps and encourage them to upgrade.

This information should be accessible in such way that is possible to prevent connections - or refuse to authorize calls - from known bad client versions.

**Comment by yiminc** [comment]
This info is already available https://github.com/temporalio/temporal/blob/77f9af2994288b61a76a79217f1bbca0c0d5fb0b/common/rpc/interceptor/sdk_version.go#L63
