### ISSUE TITLE
Temporal Hangs Indefinitely When Use GCP Cloud SQL Sidecar Proxy

### ISSUE THREAD

**Issue by paymog** [temporalio/temporal#1451]
## Expected Behavior
I expect the temporal server to startup when running in GKE and using the GCP Cloud SQL Proxy 

## Actual Behavior
The temporal server hangs forever waiting for postgres to be available.

## Steps to Reproduce the Problem

1. Set up a kubernetes cluster in GKE
2. Set up a Cloud SQL instance in GCP
3. Run the `temporalio/auto-setup:1.8.1` image in GKE with a cloud sql side car. Make sure you set the env var `DB_ADDRESS` to `127.0.0.1` when running this deployment
4. Observe that if you tail the logs of the temporal pods you'll see them stuck with

```
+ echo 'waiting for postgresql to start up'
+ sleep 1
+ nc -z 5432
```

5. `kubectl exec` into the temporal pod
6. Run `nc -z localhost:5432` and see that it returns immediately
7. Run `nc -z 127.0.0.1:5432` and see that it returns immediately
8.  Run `nc -z 5432` and notice it hangs, just like in the temporal startup script

## Specifications

  - Version: 1.8.1
  - Platform: I believe the auto-setup 1.8.1 image runs on alpine linux

**Comment by paymog** [comment]
Ah, looks like I need to set `POSTGRES_SEEDS` to `localhost` for this to work: https://github.com/temporalio/temporal/blob/30c89b9f91dafc13d2d75fda266d81ce8bc72f3e/docker/start.sh#L133

**Comment by paymog** [comment]
Setting the postgres seed fixed this. It's confusing that `DB_ADDRESS` doesn't work. https://github.com/temporalio/temporal/blob/30c89b9f91dafc13d2d75fda266d81ce8bc72f3e/tools/cli/flags.go#L38

**Comment by wxing1292** [comment]
"db_address"  is used by CLI, not server, server use `POSTGRES_SEEDS`

ref: 
https://github.com/temporalio/temporal/blob/v1.8.1/docker/config_template.yaml
https://github.com/temporalio/temporal/blob/v1.8.1/docker/start-temporal.sh#L5
