### ISSUE TITLE
Low rate of MatchingClientAddActivityTask matching client errors

### ISSUE THREAD

**Issue by skrul** [temporalio/temporal#1454]
## Expected Behavior

Only see actionable errors in metrics :) 

## Actual Behavior

My matching service that gets ~160qps request traffic has a continuous stream of  ~10qps of operation:MatchingClientAddActivityTask client_errors. They all are service_role:matching (presumably matching -> matching requests). There are no corresponding logs emitted by the matching service.

Metric is `client_errors{namespace="all",operation="MatchingClientAddActivityTask",service_role="matching"}`

## Specifications

  - Version: 1.6.3
  - Platform: temporal + mysql + elasticsearch

**Comment by wxing1292** [comment]
i remember there are some metrics fix related to matching service in 1.7.x, so can you try upgrade to 1.7.2?

**Comment by skrul** [comment]
@wxing1292 i'll report back here after I do the upgrade!
