### ISSUE TITLE
Add ability to flush events to history for server side activity retries

### ISSUE THREAD

**Issue by samarabbas** [temporalio/temporal#1461]
**Is your feature request related to a problem? Please describe.**
Having detailed view of all retries captured in the workflow execution history could be valuable 
for visualization purpose.
<img width="989" alt="Screen Shot 2021-04-14 at 11 57 12 AM" src="https://user-images.githubusercontent.com/1766515/114764272-9769c780-9d18-11eb-91eb-8567e5474062.png">
 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yiminc** [comment]
Won't fix, may re-open in future if situation changes. 
Currently solution is to disable retry (set maxAttempt=1) and have workflow handle retries.

**Comment by yiminc** [comment]
Related issue https://github.com/temporalio/temporal/issues/1468
