### ISSUE TITLE
Support continue as new for cron workflows

### ISSUE THREAD

**Issue by mfateev** [temporalio/temporal#148]
Cron workflows use the _continue as new_ internally to schedule the next run. This doesn't play well with workflows that call _continue as new_ explicitly. 
The proposal is to allow calling continue as new explicitly and only schedule the next run automatically with a delay when a workflow completes.

**Comment by yckbilly1929** [comment]
wish to have this feature for this use case too:
a scheduled workflow like:
on human approval, schedule a workflow that execute at T-45 before end date of a contract,
on T-45 workflow completed, schedule another workflow that execute T-15 before end date,
on T-15 workflow completed, schedule another workflow that execute on end date,
on T-0 workflow completed, schedule another workflow that mark the contract expired

currently i can just do this by triggering an activity at the end of each workflow to create the next cron workflow
and to kill the previous workflow at the start of the following workflow

**Comment by yiminc** [comment]
The original request is supported. Internally, the cron now do not use continueAsNew to schedule next run. User workflow could do continue as new and next run is only scheduled when user workflow completed. 

The use case specified by @yckbilly1929 is not a regular cron use case. This is now supported by the new [schedule feature](https://github.com/temporalio/api/blob/master/temporal/api/workflowservice/v1/service.proto#L346)
