### ISSUE TITLE
Inject or plug in a customized Authorizer without having to build the temporal image by users

### ISSUE THREAD

**Issue by junjieli1** [temporalio/temporal#1496]
**Is your feature request related to a problem? Please describe.**
We need some namespace level authorization. The best bet currently is https://github.com/temporalio/temporal/blob/release/v1.8.x/cmd/server/main.go#L154. However, we'd have to implement our authorizer in temporal's repo and build the docker image from that.

**Describe the solution you'd like**
Ideally, as a customer, we don't have to build our own image. We can just use images like temporalio/auto-setup:1.8.2 and inject or plug in our own implementation of the authorizer somehow.

**Describe alternatives you've considered**
We're currently modifying temporal open source project and build our own image.

**Additional context**

**Comment by sergeybykov** [comment]
Instead of modifying Temporal code, have you looked at using server options as shown in the [extensibility/authorizer sample](https://github.com/temporalio/customization-samples/tree/master/extensibility/authorizer)?

**Comment by junjieli1** [comment]
HI @sergeybykov, yes. However, I assume your sample still require the users to compile our own image right? We currently just use the image "temporalio/auto-setup:1.8.2" and I couldn't figure out where to put [this](https://github.com/temporalio/customization-samples/blob/master/extensibility/authorizer/server/main.go#L51) without touching the compiled auto-setup image.

**Comment by robholland** [comment]
We are adding go-plugin support to tctl to help with this kind of issue. I'm not convinced about adding such things to the server though due to the performance and reliability implications of having to hit these interfaces over net/RPC or GRPC as they are out of the main process.

**Comment by junjieli1** [comment]
I see. This is basically what I'm doing now. Create my own Authorizer and feed to this [line](https://github.com/temporalio/temporal/blob/master/cmd/server/main.go#L154). Then build the auto-start image. The thing is we didn't want to own the process of maintaining our own clone, pulling update from upstream periodically, building our own image, and then releasing. I will take it though if this is the best shot we have. Let me know if the story changes. Thanks!

**Comment by sergeybykov** [comment]
I just want to be clear with terminology here. This approach doesn't require you to have a clone/fork of Temporal repo. In fact, it allowed some of our users to move away from forking Temporal code for customization. Instead, you reference Temporal as an upstream dependency and control which version you use, like with any other Go dependency (as in the [sample](https://github.com/temporalio/customization-samples/blob/8e769938d1814bede2499df48cdaa9e1d3d93a32/extensibility/go.mod#L10)).

We expect many if not most production users to leverage the server options approach eventually because everyone seems to need some level of customization, which is impossible to get with stock docker images.

**Comment by junjieli1** [comment]
Ah I see. Then I need to build an image that wraps around the server starting code? Currently, we use the auto-start image (temporalio/auto-setup:1.8.2). Is there any instruction/example/suggestion on how to build a similar image with this customized server starting code so that I can just replace the `temporalio/auto-setup:1.8.2` with my own image without changing anything else? I'm mainly concerned about missing some configurations that exist in the auto-setup image but not in my customized image.

**Comment by sergeybykov** [comment]
You can build a layer on top our image, copy your server binary, and replace [start-temporal.sh](https://github.com/temporalio/temporal/blob/master/docker/start-temporal.sh) with your version. We are looking to add a sample dockerfile for this exact use case after a minor refactoring very soon. /cc @alexshtin

**Comment by junjieli1** [comment]
Nice! Can't wait to see the sample dockerfile! I think authZ is an import topic in any application. So this solution should benefit a lot of people.

**Comment by junjieli1** [comment]
Reporting back, I'm able to create my customized Authorizer and replace the temporal server binary in the auto-start image with my own temporal server binary that has the customized Authorizer.

My dockerfile:
```
##### Temporal builder #####
FROM temporalio/base-builder:1.0.0 AS temporal-builder
WORKDIR /mycompany-temporal-image
COPY . .
RUN make bins
FROM temporalio/auto-setup:1.9.2
WORKDIR /etc/temporal
COPY --from=temporal-builder  /mycompany-temporal-image/temporal-server /usr/local/bin/temporal-server
```

My makefile:
```
bins:
    CGO_ENABLED=0 go build -o temporal-server cmd/main.go 
```

My cmd/main.go code
```
package main

import (
	"github.mycompany/authorizer"
	"go.temporal.io/server/common/dynamicconfig"
	tlog "go.temporal.io/server/common/log"
	"go.temporal.io/server/common/log/tag"
	_ "go.temporal.io/server/common/persistence/sql/sqlplugin/mysql"      // needed to load mysql plugin
	"log"

	"go.temporal.io/server/common/config"
	"go.temporal.io/server/temporal"
)

func main(){

	cfg, err := config.LoadConfig("docker", "./config", "")
	if err != nil {
		log.Fatal(err)
	}

	logger := tlog.NewZapLogger(tlog.BuildZapLogger(cfg.Log))
	dynamicConfigClient, err := dynamicconfig.NewFileBasedClient(&cfg.DynamicConfigClient, logger, temporal.InterruptCh())
	if err != nil {
		logger.Info("Unable to create file based dynamic config client, use no-op config client instead.", tag.Error(err))
		dynamicConfigClient = dynamicconfig.NewNoopClient()
	}

	s := temporal.NewServer(
		temporal.ForServices(temporal.Services),
		temporal.WithConfig(cfg),
		temporal.WithDynamicConfigClient(dynamicConfigClient),
		temporal.WithLogger(logger),
		temporal.InterruptOn(temporal.InterruptCh()),
		temporal.WithAuthorizer(authorizer.NewMyOwnMeshAuthorizer()),
	)

	logger.Info("Going to start Temporal server...")
	err = s.Start()
	if err != nil{
		log.Fatal(err)
	}

	logger.Info("All services are stopped.")
} 
```

**Comment by sergeybykov** [comment]
@junjieli1 Great! Can we close this issue now?

**Comment by junjieli1** [comment]
Yeah we can close it now
