### ISSUE TITLE
Feasibility of a BigTable based persistence implementation

### ISSUE THREAD

**Issue by ramielrowe** [temporalio/temporal#1514]
**Is your feature request related to a problem? Please describe.**
My team is currently in the research phase for a new workflow system, and temporal seems like a particularly good fit for our needs. But, we are not familiar with operating Cassandra. We are in the Google Cloud, which offers a similar row store to Cassandra. We would eventually be moving large scale existing workflows (100's of executions per second), so I'm assuming that the SQL persistence would not scale as easily as Cassandra or BigTable.

Casssandra provides more complex consistency guarantees than BigTable. BigTable can only atomically update a single row. And to further complicate things, can only atomically assert the value of a single column. I gave the Cassandra implementation a look, and it seems like the only query that may be a problem is [UpdateCurrentWorkflowExecutionForNewQuery](https://github.com/temporalio/temporal/blob/master/common/persistence/cassandra/cassandraPersistence.go#L150). It would be possible to read the row, assert the value of `current_run_id`, `workflow_last_write_version`, `workflow_state`, and then in a second atomic write, assert that the value of `current_run_id` hasn't changed before writing the new values. I am wondering if that would be consistent enough for the needs of this particular query.

**Describe the solution you'd like**
I am wondering if anyone has considered alternatives to Cassandra and traditional relational SQL databases, in particular BigTable? If there are any guidelines on necessary features for a database around consistency?

**Describe alternatives you've considered**
Google's Cloud Spanner is a large scale SQL database that offers even more flexible consistency than Cassandra. But, is significantly more expensive than BigTable for high write throughput applications.

**Additional context**
None

**Comment by wxing1292** [comment]
Have 0 exp using big table, so i need to ask few questions

does big table support multi-row transaction within a DB shard?
does big table support conditional updates?

from my understanding, spanner maybe more applicable?

**Comment by ramielrowe** [comment]
BigTable has no real concept of transactions, and it's sharding mechanisms are completely hidden from the end user. It only provides consistency at the row level.

BigTable does support conditional updates, but it is tricky to do so over multiple columns. One way to do this is to issue a read for columns X, Y and Z. Compare their values, and then issue an atomic write to X, Y and Z, if-and-only-if they haven't changed since the first read.

**Comment by wxing1292** [comment]
according to https://cloud.google.com/bigtable/docs/overview#other-storage-options
big table is not targeted as a OLTP database, so if your target is to use a google product, consider spanner or cloud sql

**Comment by ramielrowe** [comment]
Gotcha, I now see where y'all are using transactions. Which does exclude BigTable. Spanner is expensive enough that we will likely consider taking on running Cassandra. Thanks for looking into this!
