### ISSUE TITLE
Out-of-process Java Test Service

### ISSUE THREAD

**Issue by drewhoskins-stripe** [temporalio/temporal#1521]
**Is your feature request related to a problem? Please describe.**
Integrating with ruby (and soon, Go), it uses a local synchronous testing mode that is difficult to maintain and doesn't emulate production.  We regularly run into untestable things (replays, sleeps, versioning), and we worry that engineers won't be writing trustworthy tests.

**Describe the solution you'd like**
Java is the only SDK to have a high-fidelity test service (i.e. one does replays, skips sleeps).
If we wrap the java test service in a server executable, it can be used by all users of all SDKs for tests by being brought along as a lightweight sidecar.

**Describe alternatives you've considered**
* We considered reimplementing the test service in ruby, but this is expensive and doesn't benefit other languages like Go which we'll also want support for.

**Additional context**
@mfateev mentioned that a Core SDK version of a test service is months away at the earliest, and we need something sooner.

**Comment by vkoby** [comment]
Out-of-process test server temporalio/sdk-java#470 merged. Closing.
