### ISSUE TITLE
Terminate workflows based on its submitted time range.

### ISSUE THREAD

**Issue by shiyao-afterpay** [temporalio/temporal#1522]
We need to bulk terminated workflow based on its submitted time range.

Currently, we have to terminate workflow one by one, which is too slow.

**Comment by wxing1292** [comment]
if you are using ES as visibility backend try this: https://docs.temporal.io/docs/system-tools/tctl/#signal-cancel-terminate-workflows-as-a-batch-job

**Comment by shiyao-afterpay** [comment]
If I want to terminate 6M workflows, how much time will it take?

The data storage is three Cassandra replicas.

Please give me a ballpark number, and possibly the limiting factors so that we know how to increase the speed.  Thanks.

**Comment by shiyao-afterpay** [comment]
What about the performance if we want to delete all workflows under a NAMESPACE, seems like more of a one-shot database 
 operation without much filtering. Does temporal have some optimizations on this?

**Comment by wxing1292** [comment]
deletion of all workflow within a namespace is not a supported feature.
if you really want, one hack is to delete relevant records for that namespace from executions table

what is your real use case?

**Comment by shiyao-afterpay** [comment]
I see. Thanks.
