### ISSUE TITLE
MutableState cache should be configurable per host rather than per shard

### ISSUE THREAD

**Issue by samarabbas** [temporalio/temporal#1530]
**Is your feature request related to a problem? Please describe.**
Currently HistoryCache (MutableState) is created per shard and this makes it harder to configure
the size of the cache as it depends on total number of shard and total number of history hosts 
in the cluster.

**Describe the solution you'd like**
We should have a common cache per host which is shared by all shards in the cluster.  Same as 
EventsCache.

**Comment by wxing1292** [comment]
Event cache is currently per shard, we should also refactor this events cache.

**Comment by yiminc** [comment]
Done by https://github.com/temporalio/temporal/pull/4833
