### ISSUE TITLE
Server Side Encryption

### ISSUE THREAD

**Issue by etherops** [temporalio/temporal#1531]
**Is your feature request related to a problem? Please describe.**
My team is implementing a temporal cluster for several others team at my company. The teams we serve will build workflows in ruby, go and python.  We are providing both the hosted temporal cluster as well as SDK shim layers for workflow developers to use.  We are using a 3rd party vendor to host the database, Cassandra.  Due to compliance and regulation we require the data to be logically encrypted at rest (AWS EBS level encryption is not enough) on the vendor site.  After reviewing the docs and community forum it is clear that the only way to currently achieve this is through client/SDK side encryption - meaning that the client workers need to be aware of and choose encryption through the SDK `DataConverter` object.  

Another piece of context: we do _not_ need the data to be encrypted while in transit/memory while in the Temporal data center since we fundamentally trust our own selves with the data.  It is _only_ when it is in our 3rd party vendor site that we need additional logical encryption.

The problem with implementing client/SDK side encryption for our purposes is 3fold: 1 - we will have to reimplement the same custom DataConvert class/logic 3 times and keep those systems in parity since we support multiple SDK languages, 2 - we have to trust the clients to "do the right thing" in order to ensure that the server side encrypts at the database level and 3 - we do not need the added complexity/overhead of encryption while data is in transit in the Temporal cluster so this will make debugging harder for no return on investment.

**Describe the solution you'd like**
Ideally an out of the box solution where we can provide the backend server with a secret or secret and salt to encrypt data in the database with.  It is also acceptable if we need to write a custom DataConverter class for the backend/server side.

**Describe alternatives you've considered**
We investigate whether this is currently available and it is not.

**Additional context**
I reviewing the similar topics below I posted this topic https://community.temporal.io/t/server-side-encryption/2081 on the community forum and Wenquan Xing asked me to file this feature request, thanks Wenquan!  I also believe my company is in talks with your team about mutual support engagements, please reach out to me if you want more details on which company I am with.  Thanks!

**Similar posts:**
https://community.temporal.io/t/what-are-best-practices-for-making-temporal-gdpr-compliant/622
https://community.temporal.io/t/secrets-pii-in-request-response/1616
https://community.temporal.io/t/passing-sensitive-data-from-workflow-to-activity/505

**Comment by rylandg** [comment]
Hey etherops, thanks for such a well constructed and communicated feature request. I can say that I definitely agree that this is a high value feature that adds a lot of confidence to users looking for a secure Temporal deployment. We have discussed this feature internally in the past and it was always received quite positively.

There has never been a formal scoping of work to determine how much effort this feature would require. The current belief is that it requires minimal to moderate effort, which makes it quite appealing. I can't give you a concrete answer or idea of priority yet, but let us have some internal discussions and understand if we have time/resources to fit this in. I think I can safely say it will happen at some point, it's just a matter of when.

Will keep you updated and thanks again.

**Comment by etherops** [comment]
Per [discussion in Slack ](https://temporalio.slack.com/archives/CTQU95E84/p1621022297063300) w/ @wxing1292 and @mfateev the following will be needed to implement this issue:
* refactor the persistency layer, not using the hard code serializer / deserializer
* (optionally) refactor cassandra layer
* expose `PayloadSerializer` in `temporal/server_options.go`

**Comment by solongtony** [comment]
@rylandg @yiminc Can someone summarize the current state of this? It seems some work has been done but it is not finished. This is necessary for my company to be able to use temporal.

**Comment by yiminc** [comment]
There is no plan to add this support directly. However, you can achieve this by having a proxy in front of temporal server and do server side encryption there. This proxy solution works for both self-hosted server and temporal cloud. See samples of how to do that via proxy: https://github.com/temporalio/samples-go/tree/main/grpc-proxy
