### ISSUE TITLE
Unable to set frontend.keepAliveMaxConnectionAge dynamic config

### ISSUE THREAD

**Issue by CGreenburg** [temporalio/temporal#1538]
## Expected Behavior

Setting `frontend.keepAliveMaxConnectionAge` in the dynamic config should set the value:

```yaml
frontend.keepAliveMaxConnectionAge:
  - value: 600
    constraints: {}
```

## Actual Behavior

Setting `frontend.keepAliveMaxConnectionAge` in the dynamic config doesn't work. In the logs, I see:

```
{"level":"info","ts":"2021-05-10T21:10:19.942Z","msg":"Get dynamic config","name":"frontend.keepAliveMaxConnectionAge","value":300,"default-value":300,"logging-call-at":"config.go:79"}
``` 

## Steps to Reproduce the Problem

  1. Download docker-compose repository
  1. Update config/dynamicconfig/development.yaml to includ `frontend.keepAliveMaxConnectionAge` config.
  1. `docker-compose up`

## Specifications

  - Version: 1.9.2
  - Platform: macOS Big Sur 11.3

**Comment by wxing1292** [comment]
`600` -> `600s`
