### ISSUE TITLE
Add check that prohibits cross domain calls for global domains

### ISSUE THREAD

**Issue by mfateev** [temporalio/temporal#154]
Cross domain calls are supported for local domains which majority of users are using.
Cross domain calls for global domains are currently broken as domains can be active in different DCs.
This issue is to add validation that fails any attempt to do cross domain call for global domains. The validation will go away when cross domain calls for global domains are fully supported.

**Comment by wxing1292** [comment]
check is done here: 
https://github.com/temporalio/temporal/blob/d572abd/service/history/commandChecker.go#L641
