### ISSUE TITLE
ES Auto Setup does not use username and password

### ISSUE THREAD

**Issue by ajbeach2** [temporalio/temporal#1544]
https://github.com/temporalio/temporal/blob/3fd1fd800d04649a5c7a4119616e1e7e0b311245/docker/start.sh#L149
https://github.com/temporalio/temporal/blob/3fd1fd800d04649a5c7a4119616e1e7e0b311245/docker/start.sh#L87

the docker start.sh scripts, do not use username or password with curl. This means that you cannot use a username/password for elasticsearch when using the auto setup scripts.

The workaround i am using for now with kubernetes, is to mount a modified script to setup es within an init container for the frontend server.

This also means that the frontend container will never start, because the polling logic doesn't use a username/password

**Comment by wxing1292** [comment]
hi, 
currently the auto setup scripts are only aimed for dev / test purpose, not for production setup.

we do welcome community contribution

**Comment by alexshtin** [comment]
I recently refactor our scripts that we run in docker. Elasticsearch setup is now running only for auto-setup image (#1501). I also added k8s [server job](https://github.com/temporalio/helm-charts/blob/master/templates/server-job.yaml#L192-L246) which is responsible for index creation in k8s environment.
