### ISSUE TITLE
Polygot programming model with temporal

### ISSUE THREAD

**Issue by ysaakpr** [temporalio/temporal#1559]
I have still not adapted Temporal to any of my projects,  but i loved the work thats going on this area, and move from Cadance which i was closely following.

I would like to understand what is the support for polyglot programming in temporal. An Example would be
Activity A Written using Golang
Activity B Written In Java
Activity C Written in PHP
Workflow 1 - Written in Java/Golang, but has to use all the Above activities.

Is there a support for this?

If so, do we have guides defining how we have to define the activities,

For example Golang has multiple return value supported, but java has exceptions instead, so dealing with errors and things ?

Would like to add information related to this documentation, if not supported, then under limitation, already supported, a page describing such a use-case, if already existing such documentation, pardon me, share it please, and free to close this ticket.

**Comment by sw-yx** [comment]
Hi!

@tsurdilo has worked up a great sample repo showing communication between all 4 of our SDKs: https://github.com/tsurdilo/temporal-polyglot

We're working on docs now: https://github.com/temporalio/documentation/pull/443

**Comment by ysaakpr** [comment]
Thanks...looks like this is what exactly i was searching for.
