### ISSUE TITLE
tctl: update retention days to 0

### ISSUE THREAD

**Issue by yiminc** [temporalio/temporal#1592]
## Expected Behavior
Either reject the request and give clear error message
OR set the retention to 0 for real (May not be possible to do as proto does not differentiate 0 vs not set).

## Actual Behavior
Command went through with success message, but retention days not changes.

## Steps to Reproduce the Problem

  1. Update namespace retention days to 0 using tctl

## Specifications

  - Version:
  - Platform:

**Comment by yux0** [comment]
Set retention to 0 could cause replication issues as the replication from archival has not supported yet

**Comment by wxing1292** [comment]
target behavior:
* disallow 0 as retention
* allow tctl to specify > 0 retention time, e.g. 12h / 30m, etc for non global namespace
* for global namespace, min retention should be 24h
