### ISSUE TITLE
Decide right default for EmitMetric attribute of Domain Config

### ISSUE THREAD

**Issue by samarabbas** [temporalio/temporal#162]
Currently default of EmitMetric is set to 'false'.  Which means every time you register a Domain you need to specify the value for EmitMetric = true if metric needs to be enabled for domain.

Following are the options:
1. Default Value as "true": We could have the default value for this boolean as true.  This is not recommended practice with protobuf. 
2. Default Value as "false": User has to explicitly pass "true" to enable metric.  Might be bad experience if intention is to enable it for most of the domain.  
3. Rename attribute to "DisableMetric": Default value of false will cause it to enable metric by default for domains.

**Comment by mfateev** [comment]
+1 for (3)

**Comment by alexshtin** [comment]
I can't find any actual usage of this field.
