### ISSUE TITLE
Allow to remove/delete a namespace using tctl

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/temporal#1626]
**Is your feature request related to a problem? Please describe.**
Addition of a tctl command to remove a namespace

**Describe alternatives you've considered**
Keep it as it is now

**Additional context**
We don't have a good solution for this for the community at this time. 
Would be nice to add this capability in the future if possible.

**Comment by davidalpert** [comment]
this ability would be super duper helpful for people learning about temporalio as it is easy to create namespace before thinking through or even understanding consequences of a naming strategy.

the ability to rename or delete namespaces is pretty important in that sense to make experimentation cheaper.

**Comment by wxing1292** [comment]
let us track all namespace deprecation & deletion related features in this issue #1679
