### ISSUE TITLE
tctl admin commands should use same env vars as temporal-sql-tool

### ISSUE THREAD

**Issue by skrul** [temporalio/temporal#1644]
**Is your feature request related to a problem? Please describe.**

Some tctl commands (such as `tctl admin shard describe`) require database address, port, credentials, etc to be passed on the command line. 

**Describe the solution you'd like**

It would be nice if it used the same set of environment variables as temporal-sql-tool to pass these values so the commands are easy to use.

**Comment by feedmeapples** [comment]
thanks for the proposal!

**Comment by yiminc** [comment]
tctl is deprecated, should switch to use temporal CLI (https://github.com/temporalio/cli)
Also, tctl or temporal CLI no longer support directly connect to backend databases.
