### ISSUE TITLE
Parameters null with tctl workflow signal command when sending multiple inputs

### ISSUE THREAD

**Issue by maheshpec** [temporalio/temporal#1655]
## Expected Behavior

If I send a signal to a workflow from tctl and the signal takes in multiple parameters, the parameters should flow through correctly to the workflow

## Actual Behavior

If I send a signal to a workflow from tctl and the signal takes in multiple parameters, only the first parameter comes through fine. Rest come as null

## Steps to Reproduce the Problem

  1. Create a workflow with a signal with two or more parameters
  1. Send a signal via tctl
  1. You'll see that the second parameter and up are null

## Specifications

  - Version: 1.10.2
  - Platform: Mac osx x86 running temporal via docker

**Comment by samarabbas** [comment]
@feedmeapples can you look into this?

**Comment by feedmeapples** [comment]
@samarabbas sure sg

**Comment by adebisi-fa** [comment]
Experiencing same.

**Comment by feedmeapples** [comment]
@adebisi-fa Adding this to my upcoming items to work on

**Comment by yiminc** [comment]
TCTL is deprecated. Please switch to temporal/CLI https://github.com/temporalio/cli
