### ISSUE TITLE
Wrong name of EC sigining algorithm in the default token key provider

### ISSUE THREAD

**Issue by marcin-maciej-seweryn** [temporalio/temporal#1662]
## Expected Behavior
Temporal's default token key provider accepts tokens signed with key using ES256 algorithm.

## Actual Behavior
The default token key provider rejects tokens signed with ES256:
> {"level":"error","ts":"2021-06-22T14:52:01.125Z","msg":"Authorization error","error":"unexpected signing algorithm: ES256","logging-call-at":"interceptor.go:157","stacktrace":"go.temporal.io/server/common/log.(*zapLogger).Error\n\t/temporal/common/log/zap_logger.go:143\ngo.temporal.io/server/common/authorization.(*interceptor).logAuthError\n\t/temporal/common/authorization/interceptor.go:157\ngo.temporal.io/server/common/authorization.(*interceptor).Interceptor\n\t/temporal/common/authorization/interceptor.go:109\ngoogle.golang.org/grpc.getChainUnaryHandler.func1\n\t/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:1058\ngo.temporal.io/server/common/metrics.NewServerMetricsContextInjectorInterceptor.func1\n\t/temporal/common/metrics/grpc.go:66\ngoogle.golang.org/grpc.getChainUnaryHandler.func1\n\t/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:1058\ngo.temporal.io/server/common/rpc/interceptor.(*NamespaceCountLimitInterceptor).Intercept\n\t/temporal/common/rpc/interceptor/namespace_count_limit.go:90\ngoogle.golang.org/grpc.getChainUnaryHandler.func1\n\t/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:1058\ngo.temporal.io/server/common/rpc/interceptor.(*NamespaceRateLimitInterceptor).Intercept\n\t/temporal/common/rpc/interceptor/namespace_rate_limit.go:88\ngoogle.golang.org/grpc.getChainUnaryHandler.func1\n\t/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:1058\ngo.temporal.io/server/common/rpc/interceptor.(*RateLimitInterceptor).Intercept\n\t/temporal/common/rpc/interceptor/rate_limit.go:83\ngoogle.golang.org/grpc.getChainUnaryHandler.func1\n\t/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:1058\ngo.temporal.io/server/common/rpc/interceptor.(*TelemetryInterceptor).Intercept\n\t/temporal/common/rpc/interceptor/telemetry.go:108\ngoogle.golang.org/grpc.getChainUnaryHandler.func1\n\t/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:1058\ngo.temporal.io/server/common/rpc.ServiceErrorInterceptor\n\t/temporal/common/rpc/grpc.go:128\ngoogle.golang.org/grpc.chainUnaryServerInterceptors.func1\n\t/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:1044\ngo.temporal.io/api/workflowservice/v1._WorkflowService_PollWorkflowTaskQueue_Handler\n\t/go/pkg/mod/go.temporal.io/api@v1.4.1-0.20210429213054-a9a257b5cf16/workflowservice/v1/service.pb.go:1090\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:1217\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:1540\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:878"}

It looks like there's a typo in this `if` statement as it's referring to `ec256` instead of [`es256`](https://datatracker.ietf.org/doc/html/rfc7518#section-3.4):
https://github.com/temporalio/temporal/blob/36cd514da6a1333bcebd7c45bb99314a0e786bd0/common/authorization/default_token_key_provider.go#L99-L102

## Steps to Reproduce the Problem

  1. Start Temporal with default claims mapper, key provider and authorizer
  2. Point Temporal's key provider to endpoint providing EC public keys
  3. Generate a JWT token and send a request to Temporal

## Specifications

  - Version: 1.10.1
  - Platform: OSX

**Comment by sergeybykov** [comment]
@marcin-maciej-seweryn Thank you for bringing this to our attention!
I submitted #1664 to fix it.
