### ISSUE TITLE
Default claims mapper and authorizer don't support namespaces with uppercase characters

### ISSUE THREAD

**Issue by marcin-maciej-seweryn** [temporalio/temporal#1670]
## Expected Behavior
Default claims mapper and authorizer support namespace with uppercase characters.

## Actual Behavior
The default claims mapper converts all uppercase characters in namespace name to lowercase and passes them further to authorizer.
Authorizer compares the converted namespace name with the original value from the request and fails to find a match which follows to request rejection.

The conversion to lower case happens in line 112 and the converted namespace name gets stored in line 121:
https://github.com/temporalio/temporal/blob/56b464eb938688a0d50baa3177bd1686e1b84eef/common/authorization/default_jwt_claim_mapper.go#L112-L122

The comparison of converted and original namespace names happens in the map lookup in line 60:
https://github.com/temporalio/temporal/blob/56b464eb938688a0d50baa3177bd1686e1b84eef/common/authorization/default_authorizer.go#L60

The default claims mapper and authorizer work just fine with namespaces with only lowercase characters.

## Steps to Reproduce the Problem

  1. Start Temporal with a default claim mapper and authorizer
  2. Create a namespace with a uppercase letters
  3. Generate token for a namespace with uppercase letters
  4. Point worker to the namespace

## Specifications

  - Version: 1.10.1
  - Platform: OSX

**Comment by sergeybykov** [comment]
@marcin-maciej-seweryn Thank you for reporting this issue! I submitted #1671 to address it.
