### ISSUE TITLE
Enhance tctl to allow passing in header parameters

### ISSUE THREAD

**Issue by rgooch** [temporalio/temporal#1672]
**Is your feature request related to a problem? Please describe.**
It would be very convenient to be able to use `tctl` to pass in header parameters when starting and stopping workflows. This would allow for easy experimentation of using headers to carry metadata about the caller, such as authentication information.

**Describe the solution you'd like**
I would like to be able to pass in an optional flag specifying a file containing header parameters, either in JSON format or plain HTML format, for example:
```
Authenticated-User: adam
User-Groups: admins, engineering
```
These header parameters should then be made available to the workers, and in turn exposed to the workflows.

**Describe alternatives you've considered**
I've considered wrapping the parameter blob in a structure that has `headers` and `payload` fields, and then unwrapping that in each workflow, but this seems ugly.

**Additional context**
It would be extra nice if header parameters were automatically provided to workflows rather than needing to register a hook.

**Comment by mfateev** [comment]
I believe we can use tctl plugins to support pluggable ContextPropagators.

**Comment by rgooch** [comment]
I just discovered `--headers_provider_plugin` in the code (it wasn't in the version I installed with `Brew`, which was v`1.9.2`). It seems this might provide the means to pass in the headers?
However, it seems you're suggesting it's better to use a ContextPropagator in the client than passing headers explicitly?

**Comment by rgooch** [comment]
I've switched to using a `ContextPropagator` to carry metadata to workflows. They seem sufficient to my needs.
