### ISSUE TITLE
Support disabling and deletion of namespaces

### ISSUE THREAD

**Issue by rfwagner** [temporalio/temporal#1679]
Temporal should support different stages of namespace deletion.

It is inevitable over time that namespaces are created with typos, are abandoned etc. These namespaces clutter up the UI and can cause confusion over whether they are active.

Possible stages of namespace deletion:

1. Disable a namespace: make it no longer possible to submit new workflows to a namespace
2. Disable and hide namespace: same as above, but also suppress the namespace from the "namespace list" API's
3. Soft delete. Delete a namespace but do it in such a way that undelete is possible
4. Hard delete. Remove the namespace from the db with no possibility of undelete

4 (and maybe 3?) would require a crawl of the db to ensure there are no references to the namespace, in the form of active or unarchived workflows.

**Comment by davidalpert** [comment]
this ability would be super duper helpful for people learning about temporalio as it is easy to create namespace before thinking through or even understanding consequences of a naming strategy.

the ability to rename or delete namespaces is pretty important in that sense to make experimentation cheaper.

at this point it seems that my only option is to drop the temporal database and recreate it using the schema migration tools

**Comment by tristan-instacart** [comment]
Just having requirements 1 and 2 would be extremely beneficial for operations in larger organizations, even if we have to wait longer for requirements 3 and 4.

**Comment by calum-stripe** [comment]
Any update on this?

**Comment by antstorm** [comment]
+1

**Comment by franklinkim** [comment]
+1

**Comment by dwillett** [comment]
👍

**Comment by alexshtin** [comment]
Delete namespace functionality was released in [1.17.0](https://github.com/temporalio/temporal/releases/tag/v1.17.0).

**Comment by kenske** [comment]
Was this actually released? The release page for `1.17.0` says not to use it, and even on `1.18.0` there is no `delete` command for `tcl namespace`.
