### ISSUE TITLE
Temporal Server fail to start using TiDB

### ISSUE THREAD

**Issue by eastfisher** [temporalio/temporal#1684]
## Expected Behavior

Temporal Server successfully start.

## Actual Behavior

Temporal Server fail to start.

## Steps to Reproduce the Problem

  1. setup TiDB v4.0.x
  2. local build temporal server
  3. start temporal server

## Specifications

  - Version: master
  - Platform: macOS 11.4

## Possible Reason

TiDB default use optimistic transaction model. When Server start, it start a new transaction, insert one record into table namespaces, and update namespace_metadata, then commit the transaction. In pessimistic transaction model like MySQL, database ERROR 1062 (Duplicate Entry) is returned when INSERT SQL is called, but in optimistic transaction model, the ERROR is returned when the transaction COMMIT. Currently, Temporal Server cannot handle ERROR 1062 in COMMIT SQL.

**Comment by wxing1292** [comment]
Temporal currently officially support MySQL v5.7

---------
1. TiDB [claims](https://docs.pingcap.com/tidb/v4.0/mysql-compatibility) that `TiDB is fully compatible with the MySQL 5.7 protocol and the common features and syntax of MySQL 5.7.`

However, seems that TiDB (v4.0.13 & v5.0.2 & 5.1.0) does not seem to support shared lock? 
```zsh
function LOCK IN SHARE MODE has only noop implementation in tidb now, use tidb_enable_noop_functions to enable these functions
```

---------
2. We currently do not have the bandwidth to work on supporting TiDB's optimistic transaction model, but contribution is welcomed, if you want to proceed, let us sync first.

**Comment by wxing1292** [comment]
after setting both global variables to TiDB 4.0.13, seems that local canary (multiple test scenarios) can run without any issue.
* `SET GLOBAL tidb_enable_noop_functions=1;`
* `SET GLOBAL tidb_txn_mode="pessimistic";` 

according to TiDB documents below:
enabling `tidb_enable_noop_functions` will not break the existing SQL persistence layer logic (there might be edge cases), even if select for shared mode behaves differently, i.e. commit of a transaction will return an error causing business logic layer to retry.

Ref: 
* [tidb_enable_noop_functions](https://docs.pingcap.com/tidb/stable/system-variables#tidb_enable_noop_functions-new-in-v40)
* [behavior difference between TiDB vs MySQL inno DB](https://docs.pingcap.com/zh/tidb/dev/pessimistic-transaction#%E5%92%8C-mysql-innodb-%E7%9A%84%E5%B7%AE%E5%BC%82)
* [handling of commit transaction](https://github.com/temporalio/temporal/blob/v1.10.5/common/persistence/sql/common.go#L59-L86)
