### ISSUE TITLE
Support error free upgrade when new activities are added to existing workflows

### ISSUE THREAD

**Issue by rfwagner** [temporalio/temporal#1689]
It's a common scenario for users to enhance their existing workflows by adding new activities.

The SDK offers a Versioning API that allows these new activities to be called in a way that preserves non-determinism and allows for deployment of the new workflow code while workflows using the old code are still running.

However, when the new worker code is rolled out (let's assume we have workers that implement both the workflow and activity code), you will experience transient errors related to activity tasks for the newly added activity being routed to workers that are running the old workflow/activity code that don't have implementations of the new activity.

Once the new code is rolled out completely and no more old workers are running, these transient errors will disappear.

However this is still less than ideal from two perspectives:

1) This is a common scenario (new activities) and the transient errors result in confusion and ignoring them must be baked into users playbooks, they must be distinguished from real errors caused by any new code being deployed

2) There may be scenarios where you want to roll out the new worker code to a canary region or cluster while leaving the old code running for an extended period. At this point, dealing with the errors becomes more problematic

It would be a cleaner experience all around if the system could somehow understand which workers - all listening on the same task queue - implement which activities and routed the activities accordingly.

Note that it is possible to use separate task queues for the old and new code to avoid this situation, but this is pretty involved  operationally and comes with its own headaches (setting properties to configure task queue names etc)

**Comment by wxing1292** [comment]
Support error free upgrade of workflow / activity logic / SDK is part of our feature road map.

**Comment by yiminc** [comment]
Now supported via worker versioning: https://docs.temporal.io/workers#worker-versioning
