### ISSUE TITLE
Support user-centric namespace based rate-limiting in the server

### ISSUE THREAD

**Issue by rfwagner** [temporalio/temporal#1690]
As an operator, when we onboard new users, we have them project their load for us in terms of:

- number of workflows/s
- number of activities/s
- number of signals/s
- number of timers/s

We think it makes sense to estimate load in these terms because they are concepts that directly correlate to API calls that users make in their code.

However, when it comes time to enforce limits on their load, we don't really have sufficient controls in server to do so.

The server does offer some nice rate limiting options, but these controls are generally at a much lower level, e.g: `history.persistenceMaxQPS`, `frontend.rps`, etc

The best we can do is translate the users projected max load, expressed in SDK-centric terms above, into these low level system rate limits.

It would be ideal if the system offered direct control on the rates of these SDK-centric events, at the namespace level.

**Comment by samarabbas** [comment]
Currently the most relevant knob which allows you to set different limits for namespaces on the cluster is `frontend.namespaceRPS`.  But I agree it won't support the granularity you described in the issue.

**Comment by yiminc** [comment]
There are several per-namespace rate limit options available, for example, the best one probably is 
frontend.globalNamespaceRPS -- limit RPS to a given namespace for the entire cluster.
