### ISSUE TITLE
admin-tools Docker images from Dockerhub have Elasticsearch schemas at a wrong place

### ISSUE THREAD

**Issue by GreyTeardrop** [temporalio/temporal#1702]
## Description

Looking at some scripts at this repository and at the Helm chart, it all expects Elasticsearch indexes to be found at `schema/elasticsearch/visibility/index_template_{elastic_version}.json`. However, the Docker images published to the Docker hub have it at `schema/elasticsearch/{elastic_version}/visibility/index_template.json`.

```
$ docker run  -it --rm --entrypoint '/bin/bash'  temporalio/admin-tools:1.10.5 -c 'apk add tree >/dev/null 2>&1 && tree -D schema/elasticsearch'
schema/elasticsearch
├── [Jun 24 22:24]  v6
│   └── [Jun 24 22:24]  visibility
│       └── [Jun 24 22:24]  index_template.json
└── [Jun 24 22:24]  v7
    └── [Jun 24 22:24]  visibility
        └── [Jun 24 22:24]  index_template.json

4 directories, 2 files
```

Oddly enough, the image built directly from the repo has it at the expected location

```
$ docker build . -t temporalio/admin-tools:local --build-arg TARGET=admin-tools
...
$ docker run  -it --rm --entrypoint '/bin/bash'  temporalio/admin-tools:local -c 'apk add tree >/dev/null 2>&1 && tree -D schema/elasticsearch'
schema/elasticsearch
└── [Jul  2 13:52]  visibility
    ├── [Jun 25 15:59]  index_template_v6.json -> versioned/v1/index_template_v6.json
    ├── [Jun 25 15:59]  index_template_v7.json -> versioned/v1/index_template_v7.json
    └── [Jul  2 13:52]  versioned
        ├── [Jul  2 13:52]  v0
        │   ├── [Jun 15 11:12]  index_template_v6.json
        │   └── [Jun 15 11:12]  index_template_v7.json
        └── [Jul  2 13:52]  v1
            ├── [Jun 25 15:59]  index_template_v6.json
            ├── [Jun 25 15:59]  index_template_v7.json
            ├── [Jun 25 15:59]  reindex.json
            ├── [Jun 25 15:59]  reindex.painless
            └── [Jun 25 15:59]  reindex.sh

4 directories, 9 files
```

## Steps to Reproduce the Problem

  1. Deploy new Temporal cluster via official Helm chart, with Elasticsearch enabled
  2. Watch that the `es-index-setup` job logs warnings saying it can't find `index_template_v7.json` and then Elasticsearch responds to curls saying that POST body is required.

**Note**: this might as well be an issue with the Helm chart, but looking at the scripts at this repository, it also seems to refer to `schema/elasticsearch/visibility/index_template_{elastic_version}.json`, so I thought the Helm chart is fine, it's just 

## Specifications

  - Version: 1.10.3, latest master; seems to be the case for images since 1.6.0

**Comment by alexshtin** [comment]
Yes, directory structure was changed recently and `master` on this repo should match `master` on https://github.com/temporalio/helm-charts repo. To run latest server release docker image you should use [this commit](https://github.com/temporalio/helm-charts/commit/803035f5dfeb07191b1563c118d4340a8ff0aa2a) in a helm-chart repo.

**Comment by GreyTeardrop** [comment]
Hey @alexshtin, sorry for the potential confusion. I was using the latest `master` commit of the Helm chart, and was deploying the latest Temporal server release (1.10.5). 

The commit you've mentioned refers to the [index template](https://github.com/temporalio/helm-charts/blob/803035f5dfeb07191b1563c118d4340a8ff0aa2a/templates/server-job.yaml#L244) at 
```
schema/elasticsearch/visibility/index_template_{{ .Values.elasticsearch.version }}.json
```

However, the latest `temporalio/admin-tools` image does not have anything at that location. The structure seems to be
```
schema/elasticsearch/{{ .Values.elasticsearch.version }}/visibility/index_template.json
```

Just to be extra safe, I've removed my local copy of the `temporalio/admin-tools:1.10.5` image and re-fetched it again from the Docker Hub, but the result is still the same:
```
$ docker run  -it --rm --entrypoint '/bin/bash'  temporalio/admin-tools:1.10.5 -c 'apk add tree >/dev/null 2>&1 && tree -D schema/elasticsearch'
Unable to find image 'temporalio/admin-tools:1.10.5' locally
1.10.5: Pulling from temporalio/admin-tools
801bfaa63ef2: Already exists
6e1a583cde77: Already exists
9b459354069f: Already exists
87d54885203a: Pull complete
564771d995e0: Pull complete
2bff426974f8: Pull complete
1b85724672ea: Pull complete
a7ffcccf924c: Pull complete
Digest: sha256:b5bbbb465720221da6f87ce32882a6760bd554f103416f83b296330fc0394699
Status: Downloaded newer image for temporalio/admin-tools:1.10.5
schema/elasticsearch
├── [Jun 24 22:24]  v6
│   └── [Jun 24 22:24]  visibility
│       └── [Jun 24 22:24]  index_template.json
└── [Jun 24 22:24]  v7
    └── [Jun 24 22:24]  visibility
        └── [Jun 24 22:24]  index_template.json

4 directories, 2 files
```
