### ISSUE TITLE
Add support for MySql/Aurora failover

### ISSUE THREAD

**Issue by Rastusik** [temporalio/temporal#1703]
**Is your feature request related to a problem? Please describe.**
We’ve been testing temporal with Aurora DB and there were problems when we were doing failovers to new master. Temporal services were still connected to the former master and we had to restart all the services to make the cluster work again. The usual setup is to have a virtual IP which is used by the application, and the IP is pointing to the write instance of the mysql (mysql master).

**Describe the solution you'd like**
The temporal services should be able to discover that the there is a new master (which means that they are currently connected to a read only slave) in the mysql cluster and they should be able automatically reconnect to the new master.

**Describe alternatives you've considered**
I don't think there is an alternative solution with MySql.

**Additional context**

**Comment by wxing1292** [comment]
additional background
https://community.temporal.io/t/temporal-with-mysql-how-to-survive-master-slave-failovers/2496

**Comment by wxing1292** [comment]
@Rastusik 

can you provide more details about the Aurora failover behavior?

is the new active / master aurora behind a different DNS?
is the old active / master aurora returning any error if read only?

any link to aurora behavior or code sample is welcomed

**Comment by leowmjw** [comment]
@wxing1292 Set rejectReadOnly=true to support Aurora MySQL failover --> https://github.com/go-sql-driver/mysql#rejectreadonly

**Comment by wxing1292** [comment]
the potential fix #1705 is included in v1.11.2
