### ISSUE TITLE
POSTGRES_PWD env variable is not escaped correctly when combined into a URL

### ISSUE THREAD

**Issue by pquerna** [temporalio/temporal#1719]
## Expected Behavior
Running temrpoal-server in a k8s container, setting environment variable `POSTGRES_PWD=31VKrnpbtrYW3y9rP:j7}N(VD=v_3vNw` to use as Postgres Password

## Actual Behavior

Server fails to start:
```
Unable to start server. Error: sql schema version compatibility check failed: 
parse "postgres://temporal:31VKrnpbtrYW3y9rP:j7}N(VD=v_3vNw@xxxxxx.yyyyyyyy.us-west-2.rds.amazonaws.com:5432/temporal?sslmode=disable": 
net/url: invalid userinfo
```

## Steps to Reproduce the Problem

  1. Run temporal-server with `POSTGRES_PWD` containing special characters

**Comment by yiminc** [comment]
should be fixed https://github.com/temporalio/temporal/blob/b99986f05982cbe7184f6d5ff84fa946ac94a840/common/persistence/sql/sqlplugin/postgresql/session/session.go#L110
