### ISSUE TITLE
Go over all dynamic configs and see if possible to make it truly dynamic (no restart required)

### ISSUE THREAD

**Issue by wxing1292** [temporalio/temporal#1758]
**Is your feature request related to a problem? Please describe.**
Go over all dynamic configs and see if possible to make it truly dynamic (no restart required)

**Describe the solution you'd like**
Decrease the number of dynamic config which is not truly dynamic.
Ref: #1757

**Comment by yiminc** [comment]
This is case by case. We have since changed many configs to be truly dynamic and not require restarts.
