### ISSUE TITLE
WorkflowTaskTimeout ignores RetryPolicy

### ISSUE THREAD

**Issue by munir131** [temporalio/temporal#1848]
## Expected Behavior
WorkflowTaskTimeout error should respect the retry policy.

## Actual Behavior
We set MaximumAttempts to 1 and when WorkflowTaskTimeout error occurred it keep retrying that workflow for infinite time.

## Steps to Reproduce the Problem

  1. Create one workflow with default WorkflowTaskTimeout
  2. Create 100s of child workflow from that workflow.  

## Specifications

  - Version: 1.7.0
  - Platform: Docker Alpine

**Comment by yiminc** [comment]
@munir131 , which retry policy are you referring to? Is it activity retry policy or workflow retry policy?
We don't expect WorkflowTask to fail or timeout. Any failure or timeout in workflow task indicate some kind of bug that should be fixed.
And so, it is by design always retied for workflow tasks.
What is the use case that you want to stop retrying your workflow task?

**Comment by munir131** [comment]
@yiminc It is workflow retry policy. 
Yes. Parent workflow keeps seeing workflow task timeout.

[output.txt](https://github.com/temporalio/temporal/files/7044086/output.txt)

`What is the use case that you want to stop retrying your workflow task?`
Use case is just to avoid infinite retry. So, it will not block other workflows or will not eat resources. 
If workflow fails then it will be inpect later when we need. Infinite retry creates overloads. 

`We don't expect WorkflowTask to fail or timeout. Any failure or timeout in workflow task indicate some kind of bug that should be fixed.
And so, it is by design always retied for workflow tasks.`
Does that mean that WorkflowTaskTimeout is not respecting workflow retry policy is by design. if it is by design then I will redesign my workflow. If it is a bug then we can continue on this issue.

**Comment by munir131** [comment]
@yiminc Looks like `If you have retry policy of MaximumAttempts = 1 on workflow, then it won't be retried when workflow failed or timed out.` is not true in case of timeout. It keeps the workflow in `Running` state. But, Now I will change my workflow. So, closing this issue.
