### ISSUE TITLE
Can't start workflow with custom search attribute

### ISSUE THREAD

**Issue by klundby** [temporalio/temporal#1899]
## Expected Behavior
Workflow should be started with the provided custom search attribute 

## Actual Behavior
`io.grpc.StatusRuntimeException: INVALID_ARGUMENT: TestBusinessKey is not a valid search attribute name`

## Steps to Reproduce the Problem

  1. Start up temporal and ES
  2. Add custom search attribute
  3. Start workflow

## Specifications

  - Version: 1.12.0
  - Platform: using auto-setup docker image

  Just want to point out that this was working fine in version 1.11.2

**Comment by yiminc** [comment]
Custom search attributes needs to be registered. Probably a more clear error message is needed.

**Comment by klundby** [comment]
I missed [this](https://github.com/temporalio/temporal/pull/1764) in the 1.12 release. So our upgrade to 1.11.2 was working fine and our issues started once we went to 1.12. Sorry for the inconvenience
