### ISSUE TITLE
Collect SDK version info and include it in version reports

### ISSUE THREAD

**Issue by Sushisource** [temporalio/temporal#1929]
Currently we collect & report home server version info for usage tracking purposes, but we aren't doing this with SDK versions. We should collect and report that info so we can track what SDKs are being used and at what versions.

See https://github.com/temporalio/temporal/pull/823 for the initial implementation that needs to be expanded upon.

No schema changes should be needed to the RDS database, except perhaps a `connection_count` field which would allow us to track number of connections per sdk type/version pair, rather than just that such a pair did connect at some point since the last report.

**Comment by yiminc** [comment]
We need to report sdk version as metrics on server first.

**Comment by Sushisource** [comment]
> We need to report sdk version as metrics on server first.

I don't see why that needs to be first, but I agree we should also do it.
