### ISSUE TITLE
[Feature Request] Setting to Suppress validation/errors for Custom Searchable Attributes

### ISSUE THREAD

**Issue by swyxio** [temporalio/temporal#1963]
**Is your feature request related to a problem? Please describe.**

with https://github.com/DataDog/temporalite, we have a very lightweight way to run CI/CD for Temporal, except that it doesn't have Elasticsearch, therefore all workflows that use CSA APIs will error.

**Describe the solution you'd like**

have a SKIP_CSA_VALIDATION environment variable or setting that does it? alex has ideas

**Additional context**

this was brought up in meeting with @rylandg @mfateev and @jlegrone today

**Comment by yiminc** [comment]
SQLite now support custom search attribute. Please try out temporal/CLI https://github.com/temporalio/cli
