### ISSUE TITLE
 ListClosedWorkflowExecutions failed. failed to create query: For input string: "Running"

### ISSUE THREAD

**Issue by ajbeach2** [temporalio/temporal#1992]
I am currently upgrading a temporal cluster from 1.9 -> 1.12 and search is no longer working. It seems that the ListClosedWorkflowExecutions query cannot be created. I created a brand new index and brand new namespaces in the upgraded cluster, and there are no workflows in this namespace.

## Expected Behavior
Working Search

## Actual Behavior
<img width="1789" alt="Screen Shot 2021-09-29 at 3 32 24 PM" src="https://user-images.githubusercontent.com/1581726/135337815-c691aa26-d3ba-4a2b-9670-c3237e5dc777.png">

## Steps to Reproduce the Problem

  1. Spin up helm chart with version 1.12.1
  2. Enable auto setup of ES
  3. Observe Error

## Specifications
  - Version: 1.12.1, 1.11 for web
  - ES version: Open Distro 7.10.2

**Comment by ajbeach2** [comment]
It looks like the query changed? its now using a string instead of an int
```go
// old
	query := elastic.NewBoolQuery().Must(elastic.NewMatchQuery(searchattribute.ExecutionStatus, int(enumspb.WORKFLOW_EXECUTION_STATUS_RUNNING)))
	
//new
boolQuery := elastic.NewBoolQuery().Filter(elastic.NewTermQuery(searchattribute.ExecutionStatus, enumspb.WORKFLOW_EXECUTION_STATUS_RUNNING.String()))
```

https://github.com/temporalio/temporal/blob/master/common/persistence/visibility/store/elasticsearch/visibility_store.go#L230

**Comment by yiminc** [comment]
For any version below 1.11, you need to go through this manual process to upgrade to 1.11 first.
https://github.com/temporalio/temporal/releases/tag/v1.11.2

**Comment by ajbeach2** [comment]
Thanks. I was able to resolve. I am maintaining a separate helm chart from the official in order to control the setup scripts and i have a job that creates the index mapping in the utils image.

```
  SCHEMA_FILE=${TEMPORAL_HOME}/schema/elasticsearch/visibility/index_template_${ES_VERSION}.json;
  ES_SERVER=$(echo "${ES_SEEDS}" | awk -F ',' '{print $1}');
  TEMPLATE_URL="${ES_SCHEME}://${ES_SERVER}:${ES_PORT}/_template/temporal_visibility_v1_template";
  INDEX_URL="${ES_SCHEME}://${ES_SERVER}:${ES_PORT}/${ES_VIS_INDEX}";
  curl --user "${ES_USER}":"${ES_PWD}" -X PUT "${TEMPLATE_URL}" -H 'Content-Type: application/json' --data-binary "@${SCHEMA_FILE}" --write-out "\n";
  curl --user "${ES_USER}":"${ES_PWD}" -X PUT "${INDEX_URL}" --write-out "\n";
  ```
