### ISSUE TITLE
Provide ServerOption for custom frontend service rate limiting 

### ISSUE THREAD

**Issue by rfwagner** [temporalio/temporal#1996]
We would like to see a new extension point in the form of a ServerOption that lets us plug in our own gRPC request rate limiting logic to the frontend service.

The basic scenario is that we are running a multi-tenant service at scale and we need to enforce RPS limits on various aspects of namespace-specific customer workload in order to guarantee a good experience for all customers. Examples of such RPS rate limiting would be limits on new workflows/sec, new activities/sec, new signals/sec, new timers/sec.

Our thought is that we would enforce rate limiting at this relatively high level of abstraction - directly related to the API calls that customers are making in their app level code - so that customers can tell us in advance expected loads in terms that they can easily understand and project, and we can enforce limits at these levels with no additional (and potentially fuzzy) math involved in translating to lower level numbers like persistence requests/sec or overall gRPC requests/sec.

As an initial strawman proposal we were thinking of adding a new ServerOption that looked like:

```
func WithRateLimiterInterceptor(rateLimiterInterceptor grpc.UnaryServerInterceptor) ServerOption {
	return newApplyFuncContainer(func(s *serverOptions) {
		s.rateLimiterInterceptor = rateLimiterInterceptor
	})
}
```

If supplied, this interceptor would be used in place of the one that is currently configured here: https://github.com/temporalio/temporal/blob/64ef4e223785fd5ba77c51de9101157e53092820/service/frontend/service.go#L241

The idea behind allowing operators to plug in an actual gRPC `UnaryServerInterceptor` is that this gives us the ultimate flexibility to inspect the inbound gRPC request. We can inspect not only the endpoint being called but also the payload. For example, we could inspect a `RespondWorkflowTaskCompletedRequest` protobuf and look at the included `Commands` to see new activities and signals being requested.

**Comment by rfwagner** [comment]
@yiminc yes, this looks good thanks! I like the generality if this. Allowing operators to supply arbitrary interceptors will come in handy for sure. And it should suit at least our initial needs for custom frontend rate-limiting. Thanks.

**Comment by yiminc** [comment]
https://github.com/temporalio/temporal/pull/2156
