### ISSUE TITLE
describeWorkflow()#pendingActivity#lastWorkerIdentity is empty if it's the first attempt to execute activity

### ISSUE THREAD

**Issue by Spikhalskiy** [temporalio/temporal#1999]
## Expected Behavior
`describeWorkflow#pendingActivity#lastWorkerIdentity` has an identity of the activity worker that picked up the activity task.

Test in Java SDK PR https://github.com/temporalio/sdk-java/pull/784/files passes for Temporal server docker-compose.

## Actual Behavior
`lastWorkerIdentity` is empty if the activity is picked up by the worker, pending and it's the first attempt.

Test in Java SDK PR https://github.com/temporalio/sdk-java/pull/784/files fails for Temporal server docker-compose.

## Root Cause
If it is the first attempt to execute the activity task, Temporal server takes an identity of the activity worker from the long poll request here:
https://github.com/temporalio/temporal/blob/ff069578a44dac7f39d7454771e88a989f62fe61/service/history/historyEngine.go#L1296

But it persists the identity into `ActivityInfo#StartedIdentity` only and not into `ActivityInfo#RetryLastWorkerIdentity`:
https://github.com/temporalio/temporal/blob/ff069578a44dac7f39d7454771e88a989f62fe61/service/history/workflow/mutable_state_impl.go#L1915

`describeWorkflow` implementation in turn doesn't use `ActivityInfo#StartedIdentity` at all and uses `ActivityInfo#RetryLastWorkerIdentity` only:
https://github.com/temporalio/temporal/blob/ff069578a44dac7f39d7454771e88a989f62fe61/service/history/historyEngine.go#L1196

As the result, if the activity is picked up by the worker the first time and is in-progress, `describeWorkflow` returns an empty `pendingActivity#lastWorkerIdentity`.

## Proposed Fix
If we consider that activity on the server always has a retry policy and retry information, the best fix is probably to write the worker identity to `ActivityInfo#RetryLastWorkerIdentity` right after `ActivityInfo#StartedIdentity` on the first attempt.
An alternative solution could be to resolve it inside `describeWorkflow` implementation: if there wasn't a retry yet, take LastWorkerIdentity from  `ActivityInfo#StartedIdentity` and if there was a retry, take it from `ActivityInfo#RetryLastWorkerIdentity`.

**Comment by yiminc** [comment]
Fixed with https://github.com/temporalio/temporal/pull/2007
