### ISSUE TITLE
Handling private repos with DockerFile

### ISSUE THREAD

**Issue by ntayyab** [temporalio/temporal#20]
The DockerFile was updated to work with temporal repo as it is currently private. 
https://github.com/temporalio/temporal/pull/14
However the repo is eventually going to be public. This issue is to investigate a better way to support this in DockerFile (perhaps keeping multiple versions of the DockerFile or using the Makefile to have a docker target which takes care of specifying the keys if needed)

**Comment by rylandg** [comment]
From what I can tell the Dockerfile has since been refactored and it seems like this might not be relevant anymore. @samarabbas it seems like you've touched that file the most recently so can you confirm this is relevant or not?

**Comment by alexshtin** [comment]
Yes, it is not relevant anymore.
