### ISSUE TITLE
Expose cluster operator API as a part of server API

### ISSUE THREAD

**Issue by vkoby** [temporalio/temporal#2040]
**Is your feature request related to a problem? Please describe.**
Java SDK needs to be able to properly parse and test SearchAttributes.

**Describe the solution you'd like**
Expose cluster operator API as a part of server API. This API should include the calls to register search attributes, so this functionality can be covered with SDK level unit tests and be used by Temporal users in their tests

**Describe alternatives you've considered**
Enable SearchAttribute in-memory testing only

**Comment by yiminc** [comment]
This has been addressed by the Operator APIs.
