### ISSUE TITLE
ParentClosePolicy not working cross-namespace

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/temporal#2043]
Parent workflow on namespace A and taskQueue X
Child workflow on namespace B and taskQueue Y

Parent can start a child on a different namespace and task queue by setting this in ChildWorkflowOptions. 

The ParentClosePolicy setting however seems to be ignored completely in this case (if set in ChildWorkflowOptions by parent). If it is set to PARENT_CLOSE_POLICY_TERMINATE the child workflow is not terminated when the parent completes.

The child workflow still does have the parent info like 

parentWorkflowNamespace
parentWorkflowExecution.workflowId
parentWorkflowExecution.runId
parentInitiatedEventId

but ParentClosePolicy seems to be ignored

I can provide reproduce with Java SDK if needed. 

ParentClosePolicy works as expected if parent and child are in the same namespace.

**Comment by sp13ceg** [comment]
@yiminc Any chance if this can be picked up sooner ?

**Comment by sp13ceg** [comment]
Hi, Any updates on this ?

**Comment by sp13ceg** [comment]
@Ardagan Hi, Any chance this will be fixed sooner ? Thanks.

**Comment by Ardagan** [comment]
should be fixed by https://github.com/temporalio/temporal/pull/2224
