### ISSUE TITLE
Possible race condition when loading new namespace

### ISSUE THREAD

**Issue by wxing1292** [temporalio/temporal#2060]
Current master branch will allow loading new namespace directly: 
https://github.com/temporalio/temporal/blob/master/common/namespace/registry.go#L478-L486
the behavior change may affect how history engine works, e.g. only trigger failover for non seen namespace failover:
https://github.com/temporalio/temporal/blob/master/common/namespace/registry.go#L267
https://github.com/temporalio/temporal/blob/master/service/history/historyEngine.go#L359

meaning
T = 0s namespace A's failover with notification 100 is in DB, to be seen by namespace cache in 5s.
T = 1s namespace B (newly created namespace, with notification 101) is directly loaded by namespace cache by [link](https://github.com/temporalio/temporal/blob/master/common/namespace/registry.go#L478-L486), then history shard will record "all notifications <= 101) are seen, and skip the failover notification of namespace A later.

Last release: 1.12.x will check if namespace exists, and force reload all namespace: https://github.com/temporalio/temporal/blob/release/v1.12.x/common/cache/namespaceCache.go#L529

**Comment by mmcshane** [comment]
> failover with notification 100 is in DB

How can this happen ... does namespace failover _not_ go through the namespace package but rather update the database underneath?
