### ISSUE TITLE
Make linux/arm64 images available in Dockerhub

### ISSUE THREAD

**Issue by h7kanna** [temporalio/temporal#2073]
**Is your feature request related to a problem? Please describe.**
I am trying to run temporal server on Mac M1 and want to use linux/arm64 images.

**Describe the solution you'd like**
Push multi-arch docker images to Docker hub.

**Describe alternatives you've considered**
Run linux/amd64 image

**Additional context**
Trying to see if arm64 image of Temporal is the problem for
https://github.com/airbytehq/airbyte/issues/2017
https://github.com/airbytehq/airbyte/blob/master/docker-compose.yaml#L172

**Comment by yiminc** [comment]
arm64 image is available in docker hub since 1.14.
