### ISSUE TITLE
Support for PostgreSQL v10+

### ISSUE THREAD

**Issue by jammerful** [temporalio/temporal#2080]
**Is your feature request related to a problem? Please describe.**
PostgreSQL v9.6 will no longer be receiving updates updates starting from Nov 11, 2021, the [temporal documentation](https://docs.temporal.io/docs/server/versions-and-dependencies/#persistence) mentions that v9.6 is supported.

**Describe the solution you'd like**
Temporal supports PostgreSQL v10+

**Describe alternatives you've considered**
N/A

**Additional context**
https://www.postgresql.org/support/versioning/
https://docs.temporal.io/docs/server/versions-and-dependencies/#persistence

**Comment by jammerful** [comment]
People are saying that v10-v12 work, but are not officially supported: https://community.temporal.io/t/does-temporal-only-support-postgres-v9-6/1755
Can we please have this officially supported?

**Comment by dnr** [comment]
We now officially support PostgreSQL versions 10–13 (and 9.6 until EOL). Details here: https://docs.temporal.io/docs/server/versions-and-dependencies/#persistence

**Comment by joebowbeer** [comment]
https://docs.temporal.io/clusters/#dependency-versions

> PostgreSQL v10.18 and v13.4
