### ISSUE TITLE
Support SQL connection attributes in tctl

### ISSUE THREAD

**Issue by robzienert** [temporalio/temporal#2081]
**Is your feature request related to a problem? Please describe.**
When trying to use the admin commands that interface with the database directly, users who have a custom `tx_isolation` level cannot use the commands. Example:

```
Error: Failed to initialize shard manager
Error Details: Error 1193: Unknown system variable 'transaction_isolation'
```

**Describe the solution you'd like**
`tctl` should support setting transaction isolation levels.

**Describe alternatives you've considered**
No alternatives that I'm aware of - inspecting the database directly (which doesn't work well since many things are stored as proto binaries).

**Comment by yiminc** [comment]
Tctl is moving away from direct connection to database. We will be removing all direct database dependencies from tctl. All request will be routed through admin API. Here is the first PR in that direction for get shard info: https://github.com/temporalio/temporal/pull/2075
