### ISSUE TITLE
Invalidate custom search attributes cache

### ISSUE THREAD

**Issue by alexshtin** [temporalio/temporal#2094]
**Is your feature request related to a problem? Please describe.**
After custom search attributes are added to the system, it takes 1 minute for cache to be invalidated. It is ok for production scenarios but doesn't work for automated integration tests and might be confusing for first time users. To make things even worse frontend cache invalidates immediately and `tctl cluster get-search-attributes` command in single cluster setup returns updated information but any actual request to start workflow with search attributes will fail because history cache is not invalidated.

**Describe the solution you'd like**
I see 3 possible ways:
1. Send message using gossip protocol to all nodes and services in the cluster to invalidate internal caches right after search attributes are updated.
2. Move search attributes cache to the server level and solve the problem for single node deployments (local testing fits it).
3. Make cache invalidate interval configurable (currently 1 min) and set to some lower number (i.e. 1s) using environment variable for test environments (i.e. docker-compose).

**Comment by yiminc** [comment]
Option 4), make the cache read through (when a search attribute is not in the cache, reload from db), and only enable that read through if a dynamic config is enabled. Default that dynamic config to false, and enable it in test  environment.

**Comment by paulnpdev** [comment]
I'm with Yimin

**Comment by meiliang86** [comment]
Take a look at this with Yimin. There are places in code that we read from the list other than validation. To make sure we always read the up to date information, we will add a dynamic config to bypass cache for the read. This config should only be turned on for testing.
