### ISSUE TITLE
replace gRPC health check implementation with standard package

### ISSUE THREAD

**Issue by krousey** [temporalio/temporal#2096]
**Is your feature request related to a problem? Please describe.**

gRPC health checks don't support empty queries. The implementation also prevents health checking of multiple gRPC services running on the same server.

Using https://github.com/grpc-ecosystem/grpc-health-probe, `grpc_health_probe -addr localhost:7233` fails, but `grpc_health_probe -addr localhost:7233 -service temporal.api.workflowservice.v1.WorkflowService` succeeds. This works, but it means I have to craft separate health probes commands for the workflow, history, and matching services.

**Describe the solution you'd like**

Health checking without specifying a service should respond with the overall health of the server. The gRPC project provides a default implementation that supports empty querying, multiple services, and even the Watch api.

https://pkg.go.dev/google.golang.org/grpc@v1.41.0/health

**Comment by jbreiding** [comment]
I’m not sure empty is really valid but the default service for health checks should be

grpc.health.v1.Health

that is the service for “system” health status

**Comment by krousey** [comment]
Yea, so there are two issue here. 

1. The `grpc_health_probe` tool does not default the service to `grpc.health.v1.Health`. They probably never hit this because https://pkg.go.dev/google.golang.org/grpc@v1.41.0/health defaults to handling the empty service.

2. In some cases, we explicitly check against our service and ignore all others. We could also handle the `grpc.health.v1.Health` in these handlers. https://github.com/temporalio/temporal/blob/fcd3148ba6fc8d24d81e5bd375edbb8df089ec2b/service/matching/handler.go#L123-L127

**Comment by jbreiding** [comment]
Okay, I see now.
The health checks do work if the service that is deployed is specified?
But empty works for frontend only?

It looks only the frontend uses health server from the grpc package.

**Comment by krousey** [comment]
Yes, the health check works if we specify each service individually. At the time I tested, I don't think no specifying the service worked on any of the components, but I could be mistaken.

What I want is to be able to have a single `grpc_health_probe` command that works for all components. So `grpc_health_probe -addr localhost:7223 -service grpc.health.v1.Health` would be fine. It would be even nicer if `grpc_health_probe -addr localhost:7223` worked by handling the empty string.

Using the standard package (as the title suggests) is just a possible way to do this.

**Comment by jbreiding** [comment]
This will require a deeper look, because frontend does simply use the standard health server

[here](https://github.com/temporalio/temporal/blob/704a9331502dc061c5fdefe6e9de1c224a0907c3/service/frontend/fx.go#L363
)
[and here](https://github.com/temporalio/temporal/blob/6fa5b4a00e996711860886157d2b553b44aece62/service/frontend/service.go#L250)

**Comment by yiminc** [comment]
Just checked, this is working now. Verified using https://github.com/temporalio/cli/releases/tag/v0.10.5
```
~/go/bin 16:06:55
$ ./grpc-health-probe -addr localhost:7233 -service temporal.api.workflowservice.v1.WorkflowService
status: SERVING
~/go/bin 16:07:20
$ ./grpc-health-probe -addr localhost:7233
status: SERVING
```
