### ISSUE TITLE
DNS resolution failed on temporalio/docker-compose example

### ISSUE THREAD

**Issue by bkniffler** [temporalio/temporal#2097]
## Expected Behavior
Example works without issue.

## Actual Behavior
Accessing localhost:8088 works fine, but shows a little box "DNS resolution failed" in the lower right corner as soon as I'm trying to insert text in the textbox. Commandline shows this error:

<img width="859" alt="Bildschirmfoto 2021-10-27 um 00 18 17" src="https://user-images.githubusercontent.com/4349324/138974437-38bbb3e3-6732-40d4-95c9-84e62d6ed353.png">

## Steps to Reproduce the Problem

  1. Clone the https://github.com/temporalio/docker-compose.git
  2. docker-compose up
  3. open localhost:8088

## Specifications

  - Version: temporalio/auto-setup:1.13.0, temporalio/web:1.12.0, temporalio/admin-tools:1.13.0
  - Platform: Mac (M1)

**Comment by yiminc** [comment]
Verified that this is no longer repro on v1.24 at least.
