### ISSUE TITLE
getWorkflowExecutionHistory for archival namespace returns an incorrect status code 

### ISSUE THREAD

**Issue by Spikhalskiy** [temporalio/temporal#2130]
## Actual Behavior

`getWorkflowExecutionHistory` for archival namespace returns “INVALID_ARGUMENT: requested workflow history does not exist” error.

## Expected Behavior

It looks like the status code is mismatched and NOT_FOUND should be returned for this situation.

Reproduces on v1.13.0

**Comment by MichaelSnowden** [comment]
Thanks for raising this issue! Should be closed with https://github.com/temporalio/temporal/pull/3340
