### ISSUE TITLE
Timeline for Cassandra 4 upgrade

### ISSUE THREAD

**Issue by johanforssell** [temporalio/temporal#2132]
**Is your feature request related to a problem? Please describe.**
I would like to use Cassandra 4 instead of 3. 

In Cassandra 4 you are free to set the connection port to what you want on different hosts in the same cluster - not so in Cassandra 3 - https://stackoverflow.com/a/17048730

**Describe the solution you'd like**
I'd like a plan for moving from Cassandra 3 to 4.

**Comment by yiminc** [comment]
Cassandra 4.0 is supported: https://docs.temporal.io/clusters#dependency-versions
