### ISSUE TITLE
Unable to configure only one JWKS provider URI in configuration template

### ISSUE THREAD

**Issue by 7eben** [temporalio/temporal#2134]
## Expected Behavior
Configure only one keySourceUURI in jwtKeyProvider, through variable TEMPORAL_JWT_KEY_SOURCE1

## Actual Behavior
When a URI is configured through TEMPORAL_JWT_KEY_SOURCE1, and authorization and the default JWT claim mapper are enabled, no request can be authenticated since the second variable in the template (TEMPORAL_JWT_KEY_SOURCE2) is left with an empty value ("") and the code that updates the keys from URIs fails trying to fetch the empty string.

## Steps to Reproduce the Problem

  1. Configure authentication and authorization in the configuration template
  2. Set JWT configuration
```
TEMPORAL_JWT_KEY_SOURCE1=https://host/jwks.json
TEMPORAL_AUTH_AUTHORIZER=default
TEMPORAL_AUTH_CLAIM_MAPPER=default
```
  3. Try to make a authentication request:
  
`$ docker run --rm -it -v /etc/certs:/etc/certs --entrypoint tctl --network host --env-file dev-environment.env temporalio/admin-tools:1.12.2`

```
 $cat dev-environment.env
TEMPORAL_CLI_ADDRESS=localhost:7233
TEMPORAL_CLI_TLS_SERVER_NAME=localhost
TEMPORAL_CLI_TLS_CERT=/etc/certs/server.crt
TEMPORAL_CLI_TLS_KEY=/etc/certs/server.key
TEMPORAL_CLI_TLS_CA=/etc/certs/ca.crt
```
Server logs will show:

> kf-temporal             | {"level":"error","ts":"2021-11-04T13:07:45.520Z","msg":"error while refreshing token keys: ","error":"Get \"\": unsupported protocol scheme \"\"","logging-call-at":"default_token_key_provider.go:123","stacktrace":"go.temporal.io/server/common/log.(*zapLogger).Error\n\t/go/pkg/mod/go.temporal.io/server@v1.12.2/common/log/zap_logger.go:143\ngo.temporal.io/server/common/authorization.(*defaultTokenKeyProvider).timerCallback\n\t/go/pkg/mod/go.temporal.io/server@v1.12.2/common/authorization/default_token_key_provider.go:123"}

## Specifications

  - Version: 1.12.2
  - Platform: Linux

**Comment by 7eben** [comment]
Bug code:

[https://github.com/temporalio/temporal/blob/0917c302b6e4463a48844a3a12b19168e9779312/common/authorization/default_token_key_provider.go#L157](https://github.com/temporalio/temporal/blob/0917c302b6e4463a48844a3a12b19168e9779312/common/authorization/default_token_key_provider.go#L157)

**Comment by sergeybykov** [comment]
@7eben Thank you for reporting this!
Definitely an issue we need to address.
