### ISSUE TITLE
how temporal support dsl

### ISSUE THREAD

**Issue by Allentent** [temporalio/temporal#2153]
we have deployed temporal, how to support dsl workflow ?

**Comment by tsurdilo** [comment]
Go sample: https://github.com/temporalio/samples-go/tree/main/dsl
Java sample: https://github.com/temporalio/samples-java/tree/main/src/main/java/io/temporal/samples/dsl
Demo: https://github.com/tsurdilo/swtemporal

Hope this can get you started in the right direction.

**Comment by Allentent** [comment]
> Go sample: https://github.com/temporalio/samples-go/tree/main/dsl Java sample: https://github.com/temporalio/samples-java/tree/main/src/main/java/io/temporal/samples/dsl Demo: https://github.com/tsurdilo/swtemporal
> 
> Hope this can get you started in the right direction.
does dsl workflow and coding workflow type are the same model in temporal system ? dsl workflow type seems like just a additional layer of converting dsl.
by the way, how to support lambda function ?
thank

**Comment by tsurdilo** [comment]
Any dsl has an extra translation step from its markup to some object model representation that defines execution instructions that have to be executed by a runtime (programming language). Depending on the dsl you create or intend to use, as well as it's capabilities, you have to create a mapping to Temporal workflows/activities/etc constructs for the dsl to be executable. 


> by the way, how to support lambda function ?

Depends on the dsl really. If yours supports rest invocation, it would most likely translate into a Temporal activity that can invoke the 3rd party function. Some dsls support standards like openapi or asyncapi, in which case it would then translate into again an activity that knows how connect to the service given those definitions.
Temporal does not restrict you in any way here, as you define your activities as you wish.

**Comment by Allentent** [comment]
> Any dsl has an extra translation step from its markup to some object model representation that defines execution instructions that have to be executed by a runtime (programming language). Depending on the dsl you create or intend to use, as well as it's capabilities, you have to create a mapping to Temporal workflows/activities/etc constructs for the dsl to be executable.
> 
> > by the way, how to support lambda function ?
> 
> Depends on the dsl really. If yours supports rest invocation, it would most likely translate into a Temporal activity that can invoke the 3rd party function via rest. Some dsls support standards like openapi, asyncapi, and/or grpc, in which case it would then translate into again an activity that knows how connect to the service given those definitions. Temporal does not restrict you in any way here, as you define your activities as you wish.

thank for your answer

**Comment by yiminc** [comment]
@Allentent , please use our community forum or public slack for further questions. This is not the right place to ask questions. Thank you. 
Community forum: https://community.temporal.io/
Public slack: https://temporal.io/slack
