### ISSUE TITLE
I have used mysql database, how to see the blob field detail ?

### ISSUE THREAD

**Issue by Allentent** [temporalio/temporal#2157]
I have used mysql database, how to see the blob field detail ?

for example:
![image](https://user-images.githubusercontent.com/88436658/141063871-e74b4961-a99a-4750-84d3-655b2921877b.png)

**Comment by Allentent** [comment]
does anybody help ?

**Comment by yiminc** [comment]
The blob data is proto encoded. You can use tctl admin shard command to show shard info data. 

BTW, @Allentent , please use our community forum or public slack for further questions. This is not the right place to ask questions. Thank you. 
Community forum: https://community.temporal.io/
Public slack: https://temporal.io/slack

**Comment by Allentent** [comment]
> The blob data is proto encoded. You can use tctl admin shard command to show shard info data.
> 
> BTW, @Allentent , please use our community forum or public slack for further questions. This is not the right place to ask questions. Thank you. Community forum: https://community.temporal.io/ Public slack: https://temporal.io/slack

OK, thanks
