### ISSUE TITLE
does execution db and history tree/node db are in different db?

### ISSUE THREAD

**Issue by Allentent** [temporalio/temporal#2172]
does execution db and history tree/node db are in different db ?

because I have seen different shard db algorithm，so are they in different db ?

**Comment by yiminc** [comment]
They are in same DB. What are the different shard db algorithm?

**Comment by Allentent** [comment]
> They are in same DB. What are the different shard db algorithm?

where do history service process this field 'range_id', I have not seen it from execution table or transferTask table .
![image](https://user-images.githubusercontent.com/88436658/141711445-ad669ba7-7fa8-4c79-9de3-c6b4ab7740cb.png)
