### ISSUE TITLE
Mutable workflow metadata

### ISSUE THREAD

**Issue by bergundy** [temporalio/temporal#2191]
There are some attributes in the workflow metadata that we know should be mutable, some examples are:

- A common user request is to update the workflow's cron schedule
- Workflow task timeout - if a task takes too long to process the workflow is stuck never being able to complete (this is made worse when replaying workflows with long histories)
- Run / execute timeouts
- Retry policy

The most critical one is workflow task timeout at the moment because it is impossible to recover from in some cases.

**Comment by yiminc** [comment]
Duplicate of #1499
