### ISSUE TITLE
SQLite persistence not returning WorkflowExecutionInfo.task_queue

### ISSUE THREAD

**Issue by cretz** [temporalio/temporal#2207]
## Expected Behavior

When executing a workflow and then calling `ListClosedWorkflowExecutions` with Postgres and Elastic, the `task_queue` field is populated on each `WorkflowExecutionInfo`.

## Actual Behavior

When executing a workflow and then calling `ListClosedWorkflowExecutions` using https://github.com/DataDog/temporalite (i.e. Sqlite in memory and no Elastic), the `task_queue` field is _not_ populated on each `WorkflowExecutionInfo`.

## Steps to Reproduce the Problem

Run a workflow against https://github.com/DataDog/temporalite and then call `ListClosedWorkflowExecutions` there.

**Comment by cretz** [comment]
@jlegrone - FYI (sorry, forgot to notify you in description)

**Comment by yiminc** [comment]
Looks like the TaskQueue was not define in our SQL persistence data model, but fortunately it is defined in db schema. So I think this could be a simple change to wire up request to persistence in both write and read path.
Add TaskQueue to in memory [data model](https://github.com/temporalio/temporal/blob/57cdbe3e00fec04c50326cff25ae8e31e60b06d6/common/persistence/sql/sqlplugin/visibility.go#L35) 
Find where the other fields of that VisibilityRow is used (for example workflow_type_name), and try to copy for TaskQueue. Make sure you update the SQL statement for both write and read to include for this extra field.
