### ISSUE TITLE
Validate dynamic configuration initialization

### ISSUE THREAD

**Issue by samarabbas** [temporalio/temporal#226]
Make sure dynamic config works correctly on local dev setups.  Currently logs are getting spammed with errors like the following:
```
{"level":"warn","ts":"2020-03-17T10:57:04.577-0700","msg":"Failed to fetch key from dynamic config","key":"matching.idleTasklistCheckInterval","error":"unable to find key","logging-call-at":"config.go:61"}
```

**Comment by shawnhathaway** [comment]
Appears we get 1 error per ServiceRole and subsequent errors are hidden behind

https://github.com/temporalio/temporal/blob/0748a7ca49f18ab3f88f01aafd639363e6528d47/common/service/dynamicconfig/config.go

However, the path referenced by development.yaml did not appear to resolve correctly, this was updated in #234
