### ISSUE TITLE
Keep Go dependencies in-sync with the Go SDK

### ISSUE THREAD

**Issue by tminusplus** [temporalio/temporal#2321]
**Is your feature request related to a problem? Please describe.**
We are trying to import the server and Go SDK into a single mono-repo, but ran into a dependency conflict with OpenTelemetry being on separate versions. Temporal server runs v1.1.0 / v0.24.0 for metrics, and the Go SDK runs v1.2.0 / v0.25.0 for metrics. Because of this we had to fork the server release and update OpenTelemetry.

**Describe the solution you'd like**
I wanted to request keeping these dependencies in-sync. Even if the OpenTelemetry dependency is the only one kept in-sync that will be a huge help. That module has several breaking changes every minor version update, which is really what leads to this problem.

I am happy to put up a PR for the OpenTelemetry v.1.2.0 update too. Let me know if that would be helpful.

**Describe alternatives you've considered**
This might be heavy-handed, or too much effort but if the OpenTelemetry related-code could be put into it's own module and then an interface introduced for metrics within Temporal and the Go SDK that would be awesome. Then we can decouple the OpenTelemetry version from these two repos.

**Additional context**
N/A

**Comment by cretz** [comment]
> We are trying to import the server and Go SDK into a single mono-repo

The server already has a dependency on the Go SDK, so the safest approach here may be to always just use the version of the SDK the server uses in its `go.mod`.

**Comment by yiminc** [comment]
@tminusplus , yes, feel free to put up a PR to upgrade otel to 1.2.0, contribution is always welcome.

**Comment by tminusplus** [comment]
Awesome will do, thanks!

**Comment by tminusplus** [comment]
https://github.com/temporalio/temporal/pull/2385 was merged in, closing the issue. Thanks everyone!
