### ISSUE TITLE
docker-compose.yml does not start PostgreSQL

### ISSUE THREAD

**Issue by Strunevskiy** [temporalio/temporal#2322]
## Expected Behavior
temporal is up and running

## Actual Behavior
the error is shown that PostgreSQL is not up

Waiting for PostgreSQL to startup.
temporal                | + echo 'Waiting for PostgreSQL to startup.'
temporal                | + sleep 1
temporal                | + nc -z postgresql 5432
temporal                | nc: bad address 'postgresql'
temporal                | + echo 'Waiting for PostgreSQL to startup.'
temporal                | + sleep 1

## Steps to Reproduce the Problem
git clone https://github.com/temporalio/docker-compose.git
cd  docker-compose
docker-compose up or docker-compose -f docker-compose-postgres.yml up

## Specifications

docker info
Server Version: 17.06.0-ce
Kernel Version: 3.10.0-1127.el7.x86_64
Operating System: Oracle Linux Server 7.8
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.522GiB
Registry: https://index.docker.io/v1/

Notes: everything works if I run temporal with MySQL.

**Comment by suparnaj3** [comment]
@Strunevskiy, I have also come across this issue.

In my case, it was due to an existing temporal-postgresql container in the exited state.
When I removed that, it worked perfectly.

**Comment by Strunevskiy** [comment]
@suparnaj3  thanks. Let me try it.

**Comment by yiminc** [comment]
@Strunevskiy , could you confirm if your problem is fixed?

**Comment by Strunevskiy** [comment]
@yiminc  the issue is not fixed. Also, I did not notice any container in the exited state as mentioned.

**Comment by aureeaubert** [comment]
@Strunevskiy I had the same issue but I fixed it by adding the links property in the temporal container definition to allow the containers to communicate with postrgresql, 
```
links:
  - postgresql
```
Let me know if it fixes your issue

**Comment by Strunevskiy** [comment]
@aureeaubert  thanks, let me try and see.

**Comment by basharkhatib** [comment]
I had the same issue. @suparnaj3 solution worked for me. Thanks.
