### ISSUE TITLE
Allow extension of dynamicconfig keys

### ISSUE THREAD

**Issue by robzienert** [temporalio/temporal#2360]
**Is your feature request related to a problem? Please describe.**
We have built extensions into Temporal and would like to gate some features with dynamic configuration feature flags. The current dynamicconfig functionality appears to expect that all keys are defined in the upstream enum, which makes use of custom dynamicconfigs impossible.

**Describe the solution you'd like**
I'd like to be able to register new dynamicconfig keys as part of initialization of the dynamicconfig client, or after the fact via a function call.

**Describe alternatives you've considered**
- Forking the dynamicconfig client to use our own `Keys` slice.
- Refactoring our use of Temporal's dynamicconfig client, and using our own dynamicconfig client that doesn't depend on upstream's Keys.

**Additional context**
Happy to be informed that there's another, easier way to approach this.

**Comment by yiminc** [comment]
https://github.com/temporalio/temporal/pull/2462

**Comment by robzienert** [comment]
Thank you! 😍
