### ISSUE TITLE
Replace elastic with zinc ( golang )

### ISSUE THREAD

**Issue by gedw99** [temporalio/temporal#2380]
**Is your feature request related to a problem? Please describe.**

just like we have SQLite db we can use zinc which is a drop in replacement / alternative for Elastic 

https://github.com/prabhatsharma/zinc

There is a go client now too :

https://github.com/opensearch-project/opensearch-go

**Comment by mobiletoly** [comment]
Isn't it Zinc states that "Note: Zinc and all its APIs are considered to be alpha stage at this time. Expect breaking changes in API contracts and data format before at this stage."

Not sure that Temporal team should do something under this stage of Zinc development.

**Comment by irab** [comment]
List of things that Zinc doesn't support 👀 :
- High availability
- Distributed reads and writes
- Geospatial search.
- Index storage in memory
- Index storage in s3

**Comment by gedw99** [comment]
Totally true . My point was that it will be possible once it matures

**Comment by gedw99** [comment]
> List of things that Zinc doesn't support 👀 :
> 
> * High availability
> * Distributed reads and writes
> * Geospatial search.
> * Index storage in memory
> * Index storage in s3

https://github.com/mosuka/phalanx

It’s aim is not to imitate the Elastic Search API though.

**Comment by gedw99** [comment]
@irab yes Zinc is not ready yet. But it is progressing. 

They have the same things that you raised on their roadmap at: https://github.com/prabhatsharma/zinc#roadmap-items

@prabhatsharma and I spoke about some of these things, and he is open to collaboration...

**Comment by gedw99** [comment]
It uses Minio s3 now, in order to have scale and HA. 

Its has Geospatial search.

All these aspects are reasonable new but are used by users.

**Comment by yiminc** [comment]
No immediate plan to work on this.
