### ISSUE TITLE
add migration tool to tctl

### ISSUE THREAD

**Issue by wenerme** [temporalio/temporal#2383]
**Is your feature request related to a problem? Please describe.**

temporal/cadence prod bootstrap and upgrade is very HARD without auto-setup, by add migration tool to tctl, just use one tool to rule them all, current migration tool need the source, tctl can embed all migration sql/artifact to binary, make life easier.

**Describe the solution you'd like**

tctl migration

**Describe alternatives you've considered**

1. just embed sql to migration tools, but have to compile from source.
2. auto-setup have a migration only mode - do not start server

**Additional context**

**Comment by yiminc** [comment]
@wenerme could you be more specific on what you are asking? What is migration here mean? Migrate what from where to where?

**Comment by wenerme** [comment]
@yiminc migration tool  I mean `temporal-*-tool`, and the depended migration files. Currently have to enter the docker image to do the migration job, setup-schema & update, or run from source, the migration files is not bundled in `temporal-*-tool`.

I think tctl can integrate `temporal-*-tool`'s function, reduce the setup work.

For later, temporal may introduce sqlite, may even add tools to migration data from sqlite to other db. tctl contain all these tool's functions, one tool for all job.

**Comment by yiminc** [comment]
This is a dup of https://github.com/temporalio/temporal/issues/2059
