### ISSUE TITLE
Add a temporal cluster label into the exported metric

### ISSUE THREAD

**Issue by andrey-dubnik** [temporalio/temporal#2430]
**Is your feature request related to a problem? Please describe.**

Currently the cluster metric feed does not include the Temporal cluster name label which is not very convenient when managing multiple clusters as each cluster should be explicitly labeled OR metric feed transformed.

**Describe the solution you'd like**

Include temporal_cluster label into the exported metric

**Describe alternatives you've considered**

Labeling the service deployment with a cluster name

**Comment by underrun** [comment]
At least in kubernetes with prometheus it's easy to add a label for cluster - what is the advantage to including this in temporal itself?

**Comment by andrey-dubnik** [comment]
The advantage is in consistency I guess. If the label is integrated into the exported it would not matter if I run on k8s or VM as prom scraper would work irrespectively and consistently. 

It also clearly identifies the cluster based on the configuration value cluster was started with rather than the label assigned.

**Comment by Ardagan** [comment]
You can also add label into temporal server config. This label will be injected into all the metrics reported by server.
```
global:
  metrics:
    tags:
      <tagname>:<tagvalue>
```

**Comment by andrey-dubnik** [comment]
This is good enough, thanks for the pointer. In this case we only need to modify the config template to have both the tag and the current cluster following the same pattern.

Having the metrics labeled with a cluster by default would still be worth it as such label is an essential filtering attribute when the multi-tenant observability is in play.
