### ISSUE TITLE
Option not to create DB in auto-setup

### ISSUE THREAD

**Issue by AndreevDm** [temporalio/temporal#2447]
**Is your feature request related to a problem? Please describe.**
Hello. I use managed DB cloud, which does not allow creating a database using sql. But auto-setup.sh script [tries](https://github.com/temporalio/temporal/blob/master/docker/auto-setup.sh#L180) to create it via sql-tool, which in my case leads to a crash. And I can't use it to apply DB schema.

**Describe the solution you'd like**
Add option SKIP_CREATE_DB to auto-setup.sh witch will skipp `temporal-sql-tool create` commands

**Describe alternatives you've considered**
The only alternative I can imagine is to write my own script. Which of course doesn't look like a good solution.

**Comment by yiminc** [comment]
There is SKIP_SCHEMA_SETUP, did you try that?

**Comment by AndreevDm** [comment]
I need ** to** skip `temporal-sql-tool create` commands (cause db already exists), but run all other (setup-schema and update-schema) to create tables.

**Comment by yiminc** [comment]
@AndreevDm , do you want to use an existing temporal db instance and have the auto setup to be able to upgrade the schema? Or it it just an empty db that you just need to skip the create step? If so, why is there an empty db, how was it get created?

**Comment by AndreevDm** [comment]
> Or it it just an empty db that you just need to skip the create step?
This option.


>If so, why is there an empty db, how was it get created?
It is created via database management console (cli or UI). But no sql create database available.
Documentation about the cloud https://cloud.yandex.com/en-ru/docs/managed-postgresql/operations/databases#add-db

**Comment by AndreevDm** [comment]
Thanks a lot!
