### ISSUE TITLE
listArchivedWorkflowExecutions method lists unarchived workflows

### ISSUE THREAD

**Issue by VikasNS** [temporalio/temporal#2457]
## Expected Behavior
1. When I call `listArchivedWorkflowExecutions`, I must only see workflows which have been archived(ie: passed the retention period)

## Actual Behavior
2. When I call `listArchivedWorkflowExecutions`, I am able to see both archived and unarchived workflows in the result.

## Steps to Reproduce the Problem

  1. Invoke listArchivedWorkflowExecutions on the service library for a given wfid.
  2. You will see worklfows which aren't archived yet.
  
## Specifications

  - Version: 1.1.12
  - Platform: Java

**Comment by tsurdilo** [comment]
Associated forum thread: https://community.temporal.io/t/listarchivedworkflowexecutions-lists-unarchived-workflows-aswell/3899

I think it would be great to fix the current issue with archival to archive both wf history and visibility data when the retention period kicks in. Currently visibility info is archived as soon as workflow execution completes which I believe causes this issue.

**Comment by yiminc** [comment]
@VikasNS , I would like to understand more about the use case. What are you trying to do with that requirement? If you want to limit the result to certain time window, you can do so by filter on closed time.

**Comment by VikasNS** [comment]
Hi @yiminc,
Here's our usecaes.

We are using search attr to store our application datapoints.
We archvie our workflows every 7 days.

Given a workflow id, I must be able return the search attrs associated with that workflow.
For this,
1. I first search for unarchived workflows with that wfid id using describeWorkflowExecution. If I'm able to find it, I'll pull search attr from that workflow and return.
2. If I don't find it then I'll use listArchivedWorkflowExecutions to see if there are any archived worklfows with that wfid, if I find one, I pull out the search attrs from that workflow and return.

In this usecase, it doesn't hurt if listArchivedWorkflowExecutions  returns both archived and unarchived workflows but I just found that its a little misguiding to return both.


However, You will see a big problem with this faulty behaviour in Archival Tab of Temporal UI.
When I open the archival tab, I belive internally it calls listArchivedWorkflowExecutions to pull out the workflows. However, given the faulty behaviour, archival tab will show both archived and unarchived workflow creating a lot of confusions. It took me 20 mins to explain my QA that just because a workflow appears in archival tab, it doesn't mean that it is archived because of the faulty behaviour of listArchivedWorkflowExecutions function :)

**Comment by yiminc** [comment]
@VikasNS thanks for the explanation. The archival feature is still experimental. We will revisit it holistically when we are ready to productionize it.

**Comment by yiminc** [comment]
Archival would upload workflow history data to cloud storage (like S3). When archival is enabled, workflow history data will be uploaded to cloud storage soon after workflow is closed. It is not tie to workflow's retention time. So data available in archival storage does not mean workflow is already out of retention.
