### ISSUE TITLE
Do not cancel or terminate the cron workflow if runID is specified

### ISSUE THREAD

**Issue by mfateev** [temporalio/temporal#246]
A customer requested ability to terminate/cancel a single run of a cron. Currently it always kills not only the currently running run, but the whole cron.

The strawman proposal is to not kill the whole cron if runID is specified.

**Comment by adamjedrzejec** [comment]
seems reasonable

**Comment by yiminc** [comment]
This is handled by the new [schedule feature](https://docs.temporal.io/concepts/what-is-a-schedule). The target workflow is separate from the scheduler. Terminate an individual workflow run won't stop the scheduler.
