### ISSUE TITLE
Need a metric to understand that there is no workers on non-empty queue

### ISSUE THREAD

**Issue by Spikhalskiy** [temporalio/temporal#2463]
**Is your feature request related to a problem? Please describe.**
If for any reason there is a task queue with tasks and just no workers listening on this queue, there is no way to detect it.

The absence of workers on a task queue can be caused by misconfiguration of tasks queues on the worker side or by one of the versioning schemas where users keep workers with old code implementation on old task queues and spawn new workers on a new task queue.

**Describe the solution you'd like**
Some metrics detect that the queue is not empty, but there are no workers on it.

**Describe alternatives you've considered**
The closest metric is the number of task timeouts, but it can be 1. delayed if timeouts are set large 2. unprecise, because doesn't allow to distinguish between slow workers vs absent workers

**Comment by yiminc** [comment]
Metrics no_poller_tasks was added to support this.
