### ISSUE TITLE
Archival attempted for already archived workflow

### ISSUE THREAD

**Issue by VikasNS** [temporalio/temporal#2464]
## Expected Behavior
1. When the inline archival of history fails, it will be archived by signaling the temporal system archival workflow.
2. If the signaling fails, no archival should be attempted and neither the deletion of execution history.
3. Archival should be reattempted. 

## Actual Behavior
1. When the signaling fails from the perspecitive of the caller due to context deadline exceeded(300ms), the temporal system workflow somehow gets the signal and it archives and deletes the history.
2. From the perspecitive of the caller, as the signal failed, the archival will be reattempted. In the subsequest attempt, archival fails stating that the execution history is unavailable (obvious reason : it was deleted in the last attempt)
3. I believe the root cause of this problem is the small value for context deadline (300ms)

## Steps to Reproduce the Problem

  1. Fail the inline history archival so that it will take the signal route
  2. Have the timeout set to 300ms (default) or less
  3. Run temporal with some load to introduce latency

## Specifications

  - Version: 1.1.12
  - Platform: Java

**Comment by yycptt** [comment]
The linked PR should mitigate this issue. 

It's possible that history archiver get multiple duplicated requests for the same workflow and process them in parallel.
So history not found error should be treated as an expected error and skip archival instead of fatal non-retryable error.

**Comment by VikasNS** [comment]
@yycptt 
Want to understand what this means to the ressiliency of archival.

Say the first time I attempt to signal the archival workflow, it fails.  What if it was geninue failure where the archival workflow didn't really recieve the signal?

In this case, post signal failure, previously the task would fail and would be retried, howoever with this PR, what's gona happen.?

The reason I'm asking this is, Our wf history is very important. If I'm deleting wf history from persistance db falsly assuming that the workflow has been archvied, it would be a data loss we can't afford.

**Comment by yycptt** [comment]
The linked pr won't change the ressiliency of archival. It only changes how workflow history not found is handled while doing archival (return nil error instead of reporting non-retryable since history not found is an expected case). Regardless of how we can handle the history not found case, there's nothing we can upload because the history is already gone.

The PR doesn't touch the signaling part at all and transfer task will be retried until the archival request is delivered to the system workflow.

**Comment by VikasNS** [comment]
Got it Thanks.
With this change, the archival activity will no longer fail if the history is not found?
