### ISSUE TITLE
Regression in/undocumented networking changes between Temporal v1.13 and 1.14

### ISSUE THREAD

**Issue by sw-yx** [temporalio/temporal#2539]
## Expected Behavior

When I [run `docker-compose up` in Gitpod](https://gitpod.io/#https://github.com/temporalio/samples-typescript/) with Temporal v1.13, Temporal (with auto-setup) starts up properly. I rely on this behavior for teaching Temporal.

## Actual Behavior

When I do the same thing with Temporal v1.14 and 1.15, Temporal fails to auto-setup properly, because running `tctl cluster health` now returns this error

```
Error: Unable to get "temporal.api.workflowservice.v1.WorkflowService" health check status.
Error Details: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: lookup temporal on 127.0.0.11:53: no such host"
```

This error doesn't happen when I run `docker-compose up` on my local desktop, which leads me to suspect that this is a networking dependency that was changed between v1.13 and 1.14

## Steps to Reproduce the Problem

  1. Run https://gitpod.io/#https://github.com/temporalio/samples-typescript/ with Temporal v1.14 or v1.15 (you need to edit it locally since i'll pin it to v1.13 for now) and observe that Temporal Server does not start properly.

**Comment by sw-yx** [comment]
Quick video bug report to elaborate the above: https://www.loom.com/share/a3126a935c3c4039b8696121e41f9fd5

**Comment by jbreiding** [comment]
@sw-yx 
port 53 is dns, this is likely something with gitpod not temporal.

```
Error: Unable to get "temporal.api.workflowservice.v1.WorkflowService" health check status.
Error Details: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: lookup temporal on 127.0.0.11:53: no such host"
```

**Comment by sw-yx** [comment]
my thinking is that the change between v1.13 and v1.14 (which i can consistently replicate) is behavior that is being broken somehow and if it affects gitpod it probably affects other networking setup - still have to figure out what it is

**Comment by jbreiding** [comment]
The error message is around failing to lookup the host `temporal` and the local dns service responding with no host.
It's entirely possible the containers are not connected to the same network that would allow for that dns resolution to happen.

I suppose its possible the docker-compose file that is being used changed between those versions.

**Comment by sw-yx** [comment]
i am taking a working docker-compose file and only thing i am doing is changing the temporal version number up to 1.14 or 1.15 and that breaks it. i dont know what else to do but at this point happy to just stop at 1.13 indefinitely until this becomes a real problem. appreciate the time.

**Comment by jbreiding** [comment]
I am not familiar with gitpod enough to help deeper.
But to dive further into this I would suggest trying to resolve the name temporal from a shell from the auto-setup container.

you can ping, openssl connect, dig, or nslookup if it's available.

with local docker you can inspect the attached network of the containers to see the connected ips and the names the can be resolved with.
