### ISSUE TITLE
Cassandra schema bootstrap fails when applying the migration 1.0 to the intial schema

### ISSUE THREAD

**Issue by vaclavbroz** [temporalio/temporal#2551]
## Expected Behavior

Temporal bootstraps Cassandra schema.

## Actual Behavior

The initial schema is created but then the first migration at:
https://github.com/temporalio/temporal/blob/30c89b9f91dafc13d2d75fda266d81ce8bc72f3e/schema/cassandra/temporal/versioned/v1.0/schema.cql
fails probably because of syntax: 

```
CREATE TYPE serialized_event_batch (
  encoding_type text,
  version       int,
  data          blob,
);
```
has one comma at the end while the syntax should be:
https://docs.datastax.com/en/cql-oss/3.3/cql/cql_reference/cqlCreateType.html

## Steps to Reproduce the Problem

  1. Clone the docker-compose repo version 1.13
  1. Select the Cassandra version in config
  1. Bring it up

## Specifications

  - Version: 1.13 docker-compose repo

**Comment by vaclavbroz** [comment]
```
temporal                | 2022-02-25T22:16:44.483Z      INFO    Processing schema file: /etc/temporal/schema/cassandra/temporal/versioned/v1.6/cluster_metadata_info.cql   {"logging-call-at": "updatetask.go:232"}
temporal                | 2022-02-25T22:16:44.483Z      DEBUG   ---- Executing updates for version 1.0 ----     {"logging-call-at": "updatetask.go:150"}
temporal                | 2022-02-25T22:16:44.483Z      DEBUG   CREATE TYPE serialized_event_batch (encoding_type text,version int,data blob,);    {"logging-call-at": "updatetask.go:152"}
temporal                | 2022-02-25T22:16:44.552Z      ERROR   Unable to update CQL schema.    {"error": "error executing statement:line 1:92 no viable alternative at input ') (... (encoding_type text,version       int,data          blob,)...)", "logging-call-at": "handler.go:82"}
t
```

**Comment by yiminc** [comment]
I have never encounter this issue. What version of Cassandra are you using?

**Comment by vaclavbroz** [comment]
Azure CosmoDB Cassandra API. But it's inline with the specs see above, there should not be any trailing comma in the list of fields.
