### ISSUE TITLE
Continue as new continually copies over prev_auto_reset_points

### ISSUE THREAD

**Issue by cretz** [temporalio/temporal#2558]
**Is your feature request related to a problem? Please describe.**

Continue as new copies over prev_auto_reset_points (causes interminable growth?)

**Describe the solution you'd like**

TBD. Maybe an option to purge this, or maybe we only need the previous run's values, etc.

**Comment by yiminc** [comment]
Looks like we already have MaxAutoResetPoints default at 20:
https://github.com/temporalio/temporal/blob/716b3cd23514da0a259e01086926b157b848c704/service/history/configs/config.go#L271

**Comment by rpmoore** [comment]
Got it, so it shouldn't grow without bound. I'm still curious why it's copied over with Continue-As-New, but I can go digging to figure that out.

**Comment by cretz** [comment]
I'm gonna go ahead and close this issue as by-design. @rpmoore - feel free to comment and/or reopen is there is something to tackle here.
