### ISSUE TITLE
Reset sticky queue after some time before workflow task is scheduled

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/temporal#2600]
If a workflow task is scheduled after a specified (configurable?) time after a previous workflow task then sticky queue shouldn't be used (it should reset to "Normal" kind).

example:

    {
          "eventId": "20",
          "eventTime": "2022-03-10T18:22:00.176291717Z",
          "eventType": "WorkflowTaskCompleted",
          ....
    }
     .... inactivity for 5 hours
    {
       "eventId": "21",
       "eventTime": "2022-03-10T23:33:10.270782473Z",
       "eventType": "WorkflowTaskScheduled",
       .... "kind": "Sticky"
     }

event 21 should have been reset to kind:  "Normal" after some time (less than 5 hours)

**Comment by zhishi** [comment]
I think the better way is check if the sticky worker id still running to avoid sending the task to an outdated worker? the timeout issue can happens when I restart everything in several minutes.

**Comment by yiminc** [comment]
This is a dup of https://github.com/temporalio/temporal/issues/2363
