### ISSUE TITLE
Workflow execution history not showing up in the Temporal UI with Persistence Volume Claim

### ISSUE THREAD

**Issue by sidharthsunilkumar** [temporalio/temporal#2603]
I added Persistence Volume Claim to my Cassandra Pod in my Temporal setup. So I expected it to retain the execution history even if the whole setup is killed and restarted. But when I restart the setup, I can see that the executions are retained in the 'history_node' table in Cassandra. But the executions do not show up in the Temporal UI.
What do I need to do to make this happen?

I have attached the PVC part of the statefulset.yaml file of Cassadra Pods.

 volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "my-storage-class2"
        resources:
          requests:
              storage: 1Gi

**Comment by jbreiding** [comment]
To my knowledge here I would expect the result of this change would have been to attach a new and empty volume.

Is it possible the statefulset is still just using the previous dynamic volume claim?

But the UI displays executions from the visibility store, how have you configured visibility?

**Comment by sidharthsunilkumar** [comment]
The issue has been resolved. To fix it, the volume mount path needs to be changed from "var/lib/elasticsearch" to "/usr/share/elasticsearch/data".
