### ISSUE TITLE
consider report all service_errors as one metric with error type as tag

### ISSUE THREAD

**Issue by yiminc** [temporalio/temporal#2628]
Currently, services errors are reported as separate metrics one per error type, for example [here](https://github.com/temporalio/temporal/blob/f7ed3949134883ba7633e72933bf9be835f78a34/common/metrics/defs.go#L2234-L2250). Same for persistence_errors. 
This makes it very hard to have a metrics query for dashboard to show all service_errors. 
Should consider having one metric for all service_errors with error type tag for each error type.

**Comment by jbreiding** [comment]
@yiminc 
This is the metric where the conversation ended with a new metric and deprecation plan for the old metric?

**Comment by yiminc** [comment]
Yes, we want to create a new metrics, say service_errors_with_type, and emit it with error_type tag. In 1.17, we will keep the old metrics untouched (those service_errors_xxx), but in release note of 1.17 we would warn that those metrics will be gone and in 1.18 we would remove those old metrics. But we will keep service_errors as separate metrics untouched as it is used to calculate SLO etc, i'm not fully clear how exactly it is used.
