### ISSUE TITLE
Fresh install and workflow results in ListClosedWorkflowExecutions, Elasticsearch error

### ISSUE THREAD

**Issue by nshazly** [temporalio/temporal#2649]
## Expected Behavior
Running `tctl workflow list` should respond with a list of running works flows or an empty list. Not an error.

## Actual Behavior

```
$ tctl workflow list                                                       
Error: Failed to list closed workflow.
Error Details: context deadline exceeded
('export TEMPORAL_CLI_SHOW_STACKS=1' to see stack traces)
```
And the web interface shows the following error:

![image](https://user-images.githubusercontent.com/1079547/160196915-1dd3f65e-a214-4e30-8f06-a551f23c216b.png)

Additionally, 
```
$ tctl wf start --tq fake.queue --wt fake.workflow
Started Workflow Id: bf730e6e-5f21-476f-a0ae-7b2e39707326, run Id: 00356ebe-2a10-4034-844e-735cfa2f2b16

$   tctl wf term -w bf730e6e-5f21-476f-a0ae-7b2e39707326     
Error: Terminate workflow failed.
Error Details: sql: no rows in result set
```

## Steps to Reproduce the Problem

  1. Fresh install of temporal IO using elasticsearch/postgresql, version 1.15.2
  2. Run the command `tctl n re default` to create a namespace
  3. Start a workflow `tctl wf start --tq fake.queue --wt fake.workflow --et 10`
  4. Run `tctl workflow list`
OR
   Log into the WEB Interface

## Specifications

  - Version: 1.15.2
  - Platform: K8s

**Comment by alexshtin** [comment]
You didn't create schema in Elasticsearch. How did you deploy your cluster? If you don't use `auto-setup` image or helm charts, you need to run similar steps manually: https://github.com/temporalio/docker-builds/blob/main/docker/auto-setup.sh#L268-L276.

**Comment by nshazly** [comment]
The helm chart was used to deploy and the cron that creates the schema ran. Querying the ES cluster shows 2 indexes. So the schema looks to be properly created.

**Comment by nshazly** [comment]
@alexshtin Running the auto-setup scripts shows the indexes are alr4eady created and the error persists. Can this ticket be re-opened ?
```
$ curl -X PUT "${INDEX_URL}" --write-out "\n"
{"error":{"root_cause":[{"type":"resource_already_exists_exception","reason":"index [temporal_visibility/KbYZaZBjTuucfbR0z8si4g] 
already exists","index_uuid":"KbYZaZBjTuucfbR0z8si4g","index":"temporal_visibility"}],"type":"resource_already_exists_exception","reason":"index [temporal_visibility/KbYZaZBjTuucfbR0z8si4g] already exists","index_uuid":"KbYZaZBjTuucfbR0z8si4g","index":"temporal_visibility"},"status":400}
```
