### ISSUE TITLE
using sqlite introduces CGO dependency for (only) tests

### ISSUE THREAD

**Issue by Lercher** [temporalio/temporal#2657]
## Expected Behavior

Build succeeds with `CGO_ENABLED=0`, `go test ./...` should at least compile.

## Actual Behavior

Tests don't build, see next section for details.

## Steps to Reproduce the Problem

  1.  `set CGO_ENABLED=0`
  1. `go build .\cmd\server\`  -> succeeds
  1. `go test ./...` -> fails with this build error:

```txt
package go.temporal.io/server/common/persistence/persistence-tests
     imports go.temporal.io/server/common/persistence/sql/sqlplugin/sqlite: 
        build constraints exclude all Go files 
        in C:\git\src\github.com\temporalio\temporal\common\persistence\sql\sqlplugin\sqlite
```

(reformatted for better readability)

## Specifications

  - Version: On branch release/v1.15.x
  - Platform: go version go1.18 windows/amd64 (Windows 10)

## Why it is Important

Operating a CGO compatible C/C++ compiler on Windows is a non-trivial task with many (installation) hurdles and quite a lot of probably incompatible C/C++ variants. Furthermore, I'm personally favoring a "pure" Go build.

## More Information to Consider

The sources already address CGO with build constraints, as this global search indicates. It's probably an idea to use these for the test components too:

<img width="394" alt="image" src="https://user-images.githubusercontent.com/5909334/160384761-12e7f66d-7426-4172-aee0-993d328bcbeb.png">

The _impact_ is probably low: Opting out from CGO intentionally turns off sqlite support, so there is probably no personal need to test the sqlite driver package. 

As an _alternative_, https://pkg.go.dev/modernc.org/sqlite advertises itself as _Package sqlite is a CGo-free port of SQLite._ I don't use it, however, and of course I don't know about its stability or fitness for temporal.

Thanks for considering,
Martin

**Comment by jbreiding** [comment]
Thanks for the issue, I have been planning to move to this library and now have a PR for it.

However our tests are meant to be run with the race detector for go which also requires CGO.

Until that requirement is removed our tests, to be complete, will need CGO to execute using the race detector.

https://go.dev/doc/articles/race_detector
