### ISSUE TITLE
Identity parameter for child workflow is empty(Identity ="") for event id=1. for other events is showing correct

### ISSUE THREAD

**Issue by sumit-maurya-maersk** [temporalio/temporal#2682]
## Expected Behavior
In ClientOptions there is Identity option available that I am using to set an Identity. so that for workflow as well as for child work identity should shown in workflow history.
## Actual Behavior
But here in child work flow there is an issue. for each child workflow event id=1 in that identity is shown empty(identity="") . but for other event id it's showing correct identity.

## Steps to Reproduce the Problem

  1. create a client with the client option identity.
  2.Run for child workflow .
  3.check the workflow history for event number =1;

**Comment by cretz** [comment]
Didn't see this when I created #2687. That one is a bit clearer, closing this one.
