### ISSUE TITLE
Guarantee signal is delivered to current workflow during continue as new

### ISSUE THREAD

**Issue by wxing1292** [temporalio/temporal#2694]
Currently, when signaling current workflow (run ID being empty), the logic will
1. get current run ID from DB
2. using above current run ID for workflow lock
3. check if workflow is still running
  a. if still running, signal workflow
  b. if completed, return not found error

above logic can encounter race condition if target workflow does continue as new, e.g.
T = 0: current run ID is '1234-5678'
T = 1: (signal caller) get current run ID from DB: '1234-5678'
T = 2: current run '1234-5678' does continue as new to 'abcd-efgh'
T = 3: (signal caller) using above current run ID '1234-5678' for workflow lock
T = 4: (signal caller) see target workflow '1234-5678' is finished, while the actually current workflow is 'abcd-efgh'

one way to solve above issue is to swap the logic of this `if block`https://github.com/temporalio/temporal/blob/2ebc73eedfd0a096568ed6c15f0bc26776f22d87/service/history/historyEngine.go#L1976-L1978 with 
```go
if !mutableState.IsWorkflowExecutionRunning() {
	_, status := mutableState.GetWorkflowStateStatus()
	if status == enumspb.WORKFLOW_EXECUTION_STATUS_CONTINUED_AS_NEW && currentWorkflow {
		return nil, serviceerror.NewUnavailable("try again")
	}
	return nil, consts.ErrWorkflowCompleted
}
```

the idea is, retry if workflow is continued-as-new & run ID is empty

**Comment by yycptt** [comment]
I believe the logic [here](https://github.com/temporalio/temporal/blob/master/service/history/historyEngine.go#L3629) already cover this case.

The link logic will first get current runID from DB, lock the execution and then check if the workflow is running or not. If it's not running, the logic will query current runID again and make sure the current runID doesn't change before returning. 

This basically means at T = 4, the logic will realize the workflow is not running and query the current ID again, and see 'abcd-efgh'
