### ISSUE TITLE
Unsuccessful build when GOOS=freebsd

### ISSUE THREAD

**Issue by abdulbudiaji** [temporalio/temporal#2703]
## Expected Behavior

It should build successfully when GOOS=freebsd

## Actual Behavior

It throws this error when compiling using `GOOS=freebsd`

```
../../../go/pkg/mod/github.com/uber/tchannel-go@v1.22.2/sockio_unix.go:41:33: undefined: getSendQueueLen
```

## Steps to Reproduce the Problem

  1. git clone --depth 1 --branch v1.15.1 https://github.com/temporalio/temporal.git
  1. GOOS=freebsd GOARCH=amd64 go build -o temporal-server ./cmd/server

## Specifications

  - Version: v1.15.1
  - Go compiler: go1.18 darwin/arm64
  - Compilation Platform: darwin/arm64
  - Target Platform: freebsd/amd64

**Comment by yiminc** [comment]
We plan to remove tchannel anyway.

**Comment by ehaupt** [comment]
Any updates? I'd create an official FreeBSD port once it builds on FreeBSD 😉

**Comment by robholland** [comment]
@ehaupt are you still interested in creating a FreeBSD port for Temporal?

**Comment by ehaupt** [comment]
> @ehaupt are you still interested in creating a FreeBSD port for Temporal?

I'm looking into it.
