### ISSUE TITLE
Add event to history for Workflow.sleep(0)

### ISSUE THREAD

**Issue by Ryan-Thomas** [temporalio/temporal#2714]
When using Workflow.sleep(0) with Java SDK, no event is added to the workflow history. This can lead to a pitfall when people write Workflows where the sleep duration is controlled by a dynamic property. If the property value is changed to or from 0, the workflow history will have changed and this causes nondeterminism errors. 

I think it would make more sense if calling Workflow.sleep(0) added an event to the history to avoid this pitfall. I know this is difficult to change now because it seems like something that would not be backwards-compatible, but it's worth thinking about.

**Comment by yiminc** [comment]
Imaging you want to load a dynamic config to get concurrent size and start concurrent number of activities based on that config, you will run into the same problem as it is non-deterministic. 
You should use side effect (or mutable side effect) to fetch your dynamic config so it is replay safe.

**Comment by flazx** [comment]
thanks for you reply. I tried as you said, the error as below image.
![image](https://user-images.githubusercontent.com/122400/173485029-4d45114e-638d-43f5-b9a9-7c693011a35a.png)
