### ISSUE TITLE
We did not manage to connect Temporal with a postgresql database through a proxy (Haproxy)

### ISSUE THREAD

**Issue by laurentBT** [temporalio/temporal#2727]
## Expected Behavior

Currently we have the following configuration in our environment:

Temporal ------------ no TLS ---------------> Haproxy --------------------- mTLS ------------------> postgresql database

|________________________ K8s cluster________________|_____________________ Outside _____________________________________|

When Temporal wants to communicate with a postgresql database, a connection (no TLS) is created between the Haproxy and Temporal (it could be temporal directly or temporal-sql-tool).
Then the data is sent to the Haproxy and Haproxy will create a new mTLS connection between Haproxy and the postgresql database.

In that case, it works.

But we would like to set up a mTLS connection between Temporal and the Haproxy.

## Actual Behavior

When we try to  set up a mTLS connection between Temporal and the Haproxy, we receive a plain error message that says just TLS handshake fails without more details. We did not manage to have a more detailed message from Temporal or Haproxy.

Nevertheless, we manage to call our databse postgresql from the Temporal worker container through the Haproxy by doing a GET call with curl in mTLS.

Our question is :

Is Temporal designed to communicate with a postrgresql server through haproxy in mTLS ?

## Steps to Reproduce the Problem

For example the following command which is executed inside the temporal worker container, does not work

  1. temporal-sql-tool --tls --tls-cert-file ourCert.crt --tls-key-file ourPrivateKey.key --tls-ca-file ca.crt --plugin postgres --ep hp -u admin -p ourPort create --db temporal
  
hp is the hostname to contact haproxy inside the k8s cluster

In the same container (temporal worker), the following curl works:
  2. curl https://hp:ourPort --cacert ca.crt --cert ourCert.crt --key ourPrivateKey.key

## Specifications

  - Version: 1.11.2
  - Platform: Temporal worker

**Comment by tsurdilo** [comment]
Forum thread: https://community.temporal.io/t/we-did-not-manage-to-connect-temporal-with-a-postgresql-database-through-a-proxy-haproxy/4441

**Comment by yiminc** [comment]
Replied in the forum thread.
