### ISSUE TITLE
Race condition on shard state transition 

### ISSUE THREAD

**Issue by yux0** [temporalio/temporal#2777]
## Expected Behavior
No error

## Actual Behavior
Unexpected panic

## Steps to Reproduce the Problem

`go test -race -testify.m ^TestShardControllerClosed$ 1000`

## Specifications

Found in build test: https://buildkite.com/temporal/temporal-public/builds/3488#e9fe11ad-9cd3-47dc-a810-4cd68646063a

I am not 100% if this is test issue or actual code bug. We need to investigate.

**Comment by dnr** [comment]
It looks like the race is between `s.state = contextStateStopped` and something in gomock that's trying to print the value of an object. So this seems like a test/mock artifact. The shard context explicitly calls `s.engineFactory.createEngine` outside of the rwlock, but there's no reason that should touch `s.state` directly.

**Comment by yux0** [comment]
I tried commented out an unlock/lock logic and seems like no error after that. Do you know what use case we are optimized to have the unlock/lock?

`if !s.engineFuture.Ready() {
	//s.wUnlock()
	s.maybeRecordShardAcquisitionLatency(ownershipChanged)
	engine := s.createEngine()
	//s.wLock()
	if s.state >= contextStateStopping {
		engine.Stop()
		s.engineFuture.Set(nil, errStoppingContext)
		return errStoppingContext
	}
	s.engineFuture.Set(engine, nil)
}`

**Comment by yux0** [comment]
I only run the test not test the service.

**Comment by dnr** [comment]
fixed by #2879
