### ISSUE TITLE
[Bug] Worker in tutorial is timing out

### ISSUE THREAD

**Issue by ManrajT** [temporalio/temporal#2805]
**Describe the bug**
I can't complete the introduction tutorial  (https://docs.temporal.io/docs/go/run-your-first-app-tutorial).  The "Running the Worker" section has problems.  The execution of "go run worker/main.go" results in error "Task processing failed with client side error Namespace default TaskQueue TRANSFER_MONEY_TASK_QUEUE WorkerID 88909@Manrajs-MacBook-Air.local@ WorkerType ActivityWorker Error context deadline exceeded" 

**To Reproduce**
1. Run temporal by running "docker-compose up" 
2. Follow all steps in tutorial "https://docs.temporal.io/docs/go/run-your-first-app-tutorial" 

**Expected behavior**
It's expected that the worker polls the queue and that the task completes, like the tutorial.  The UI shows its stuck on withdraw task.  

**Desktop (please complete the following information where relevant):**
 - OSX Big Sur 11.5.1
 - 1.15.0
 - MacBook Air (M1, 2020) 
 - Docker

**Additional context**
It looks like Docker starts ok.  I've attached logs.  I understand that the task may be failing because it cannot communicate to some dependent server.   
[docker-output.txt](https://github.com/temporalio/web/files/8624876/docker-output.txt)

This is complete error from running worker. 

Withdrawing $54.990002 from account 001-001. ReferenceId: 68b1673f-ec4e-49a3-98a4-abc5b29f9807
2022/05/04 13:40:42 INFO  Activity complete after timeout. Namespace default TaskQueue TRANSFER_MONEY_TASK_QUEUE WorkerID 88909@Manrajs-MacBook-Air.local@ WorkflowID transfer-money-workflow RunID 9d5b8e73-7f11-45d7-9e24-f88caf20a9f5 ActivityType Withdraw Result nil Error <nil>
2022/05/04 13:40:42 INFO  Task processing failed with client side error Namespace default TaskQueue TRANSFER_MONEY_TASK_QUEUE WorkerID 88909@Manrajs-MacBook-Air.local@ WorkerType ActivityWorker Error context deadline exceeded

**Comment by yiminc** [comment]
This is due to the tutorial sample uses way too old sdk version (v1.0.0). After upgrade temporal sdk-go version to 1.14.0, it worked. Please pull latest code from https://github.com/temporalio/money-transfer-project-template-go and try again.
