### ISSUE TITLE
Slack channel Url in Readme is outdated/invalid 

### ISSUE THREAD

**Issue by jimitndiaye** [temporalio/temporal#2812]
## Expected Behavior
The slack channel invitation Url in the readme should be valid

## Actual Behavior
Following the link leads to a Slack error message saying "This link is no longer active". 

## Steps to Reproduce the Problem

  1. Simply click on the slack link in the readme. 
  1. Will display error message about link no longer being active. 
  1.

## Specifications

  - Version:
  - Platform:

**Comment by yiminc** [comment]
fixed
