### ISSUE TITLE
histogram metrics conflict

### ISSUE THREAD

**Issue by yiminc** [temporalio/temporal#2817]
run from master branch, got this error:
`{"level":"warn","ts":"2022-05-06T22:46:42.185-0700","msg":"error in prometheus reporter","error":"a previously registered descriptor with the same fully-qualified name as Desc{fqName: \"history_size_total\", help: \"history_size_total histogram\", constLabels: {}, variableLabels: [operation namespace service_name]} has different label names or a different help string","logging-call-at":"config.go:408"}`

The culprit is this line: https://github.com/temporalio/temporal/blob/4767cd4e506ece32af7f17bb94bd86f7cff795f5/service/frontend/workflowHandler.go#L3116

The reason is the tags are [operation namespace service_name], but same metrics was registered already with tags of [operation namespace service_name stats_type]. The line above does include that tag.

The root cause is tally scope is using rootScope instead of that tagged child scope to report the histogram.
https://github.com/temporalio/temporal/blob/4767cd4e506ece32af7f17bb94bd86f7cff795f5/common/metrics/tally_scope.go#L125

**Comment by yux0** [comment]
This error from  SizeStatsTypeTagValue has been fixed.
