### ISSUE TITLE
An attempt to cancel a workflow that is completed returns without an error

### ISSUE THREAD

**Issue by Spikhalskiy** [temporalio/temporal#2860]
## Expected Behavior

From the API doc:
```
// RequestCancelWorkflowExecution is called by workers when they want to request the cancellation of
// a workflow execution.
//
// This result in a new `WORKFLOW_EXECUTION_CANCEL_REQUESTED` event being written to the
// workflow history and a new workflow task created for the workflow. Fails with `NotFound` if
// the workflow is already completed or doesn't exist.
rpc RequestCancelWorkflowExecution (RequestCancelWorkflowExecutionRequest) returns (RequestCancelWorkflowExecutionResponse) {
}
```

Also, JavaSDK docstring on `#cancel` states:

```
@throws WorkflowNotFoundException if the workflow execution doesn't exist or is already completed
```

I would expect a cancel request for a workflow that is already finished with any status.

*I personally prefer a cancel request to workflows with CANCELLED status to be successful. But this is not aligned with the doc and it is also not aligned with `terminate` behavior. Terminate request to a terminated workflow currently fails.*

## Actual Behavior

`RequestCancelWorkflowExecution` call for a successfully completed workflow returns OK no matter what, not following the documentation of the method.

## Specifications

  - Version: master@ 7d4265457a27a630d8f4400c85188b185ca91d7d

**Comment by yiminc** [comment]
This is expected behavior. There is major difference between terminate and cancel. For terminate, it is a forceful operation, but for cancel it is a request thus the name RequestCancelWorkflowExecution. 
We need to update the doc.

**Comment by Spikhalskiy** [comment]
@yiminc It depends on how you look at it. Yes, it's a request. But if a workflow is already in a state that doesn't allow a cancellation (like completed), it's more expressive to return an error. A user/SDK can always ignore/swallow this error, but it gives more information.
I will update JavaSDK docs after the server does if it's the route we want to approach it.

**Comment by yiminc** [comment]
The behavior is correct, the issue with with incorrect doc. Both API doc and method comments are updated to reflect the actual behavior.
