### ISSUE TITLE
Disappearing workers from task-queue

### ISSUE THREAD

**Issue by Alex-Tideman** [temporalio/temporal#2882]
From temporal slack:
 
Also, if workers are there but are already filled up with activities and therefore do not actively poll atm. They do not appear in the Workers tab (understandably because temporal probably doesn't know they are there?). This took me a while to understand (I have some long running activities that filled up one of my workers completely). It was still working fine but the UI made me think there was something wrong there.

(https://temporalio.slack.com/archives/C011AAP3GFP/p1653033120725859)

## Expected Behavior
task-queue endpoint should return all pollers

## Actual Behavior
task-queue endpoint does not return all pollers

## Steps to Reproduce the Problem
Reach out to @Alex-Tideman for more info

## Specifications

  - Version:
  - Platform:

**Comment by yiminc** [comment]
The workers list from task queue is collected when worker poll from task queue. The info is keep for 5m. If worker stops polling for that task queue for more than 5m, that worker will disappear from that task queue. As soon as the worker starts polling again, it would show up again.
