### ISSUE TITLE
Namespace lookup is case sensitive

### ISSUE THREAD

**Issue by darewreck54** [temporalio/temporal#289]
It looks like when you create a namespace ex. ("Derek_Test") and go to the UI to see, it will list it in all lower case.  When you click on the link, 

![image](https://user-images.githubusercontent.com/16171726/79011702-6d843080-7b19-11ea-827f-71bba464bacc.png)

When you click on it, https://<host>/namespaces/derek_test/workflows?.  This will throw an internal error:
 
![image](https://user-images.githubusercontent.com/16171726/79011743-855bb480-7b19-11ea-9a1a-83c448014086.png)

This is because it expects https://<host>/namespaces/Derek_Test/workflows?

With guessing the namespace is unqiue and should not diff based on upper case or lower case an.

**Comment by feedmeapples** [comment]
I also tried invoking ListOpenWorkflowExecutions for default domain, just starting with uppercase. 
![image](https://user-images.githubusercontent.com/11838981/79026192-dd57e280-7b3c-11ea-8776-9c6f0c2e23cd.png)
The request fails with "5 NOT_FOUND: Namespace Default does not exist."

**Comment by feedmeapples** [comment]
this is not an issue anymore since the namespace names are actually fetched from the temporal service
