### ISSUE TITLE
{feature request} (history|visibility)Achriver reads aws credentials from a file path for s3 archiving

### ISSUE THREAD

**Issue by zzhu-bison** [temporalio/temporal#2894]
**Is your feature request related to a problem? Please describe.**
Currently historyArchiver and visibilityArchiver reply on global aws credentials to access s3 archive buckets. There are a number of issues with this approach.

1. works for ec2, an IAM role can directly attach to instance profile, but it opens a security hole, a shared ec2 would allow all services running on the host to gain access.
2. works for ecs, but would not work for k8s workload, which requires role attaches to a service account, involves additional complicated setups

**Describe the solution you'd like**
Would like historyArchiver & visibilityArchiver offers first lookup on aws secret from a path, then fall back to global environment vars or aws profiles or instance profiles.

The credential file path approach should work for both ec2 workloads and k8s workloads where a secret can be set at a mount volume.

**Describe alternatives you've considered**
K8s alternative would be attaching IAM role to service account which requires OIDC setup, will not work if there is no existing OIDC provider in the cluster

Secrets can also be passed in as environment vars to a container, however this defeats the purpose of having one centralized secret repo in many organizations. 

**Additional context**
Service secret should limit its visibility to just service alone, exposing or assuming secret availability in global environment is not a safe approach.

**Comment by jontro** [comment]
I think you can just set the AWS_SHARED_CREDENTIALS_FILE environment variable if you want to specify a specific file. 
I think we are following aws best practices here by not interfering with the defaults.
https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/configuring-sdk.html#specifying-credentials
