### ISSUE TITLE
DescribeWorkflowExecution does not work with archival

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/temporal#2919]
DescribeWorkflowExecution does not play well with archived workflows (filestore, s3, gcloud providers).

It should be able to display results for archived workflows. On the other hand GetWorkflowExecutionRawHistoryV2 does display histories of archived workflows.

**Comment by yiminc** [comment]
Archival only saved history events, not mutable states. DescribeWorkflow reads info from mutable state. For archived workflow, there is no mutable state anymore. So this is expected behavior.
