### ISSUE TITLE
what happens to uber cadence now?

### ISSUE THREAD

**Issue by listaction** [temporalio/temporal#296]
hi @mfateev , 
 with this change - could you please share what would happen to uber cadence?

**Comment by mfateev** [comment]
I would ask this question to the Uber Cadence team. This is what they posted to the Cadence Slack Channel:

> I’m Emrah from the Cadence team at Uber. I joined the community about a year ago while working for another company and then had the privilege to join the Cadence team at Uber back in January as the tech lead. Liang, the Engineering Manager for the Cadence team, and I wanted to share an update about the Cadence project.
> We want to reinforce that Uber’s Cadence team is committed to the growth and open source development of the Cadence project. Today, Cadence powers 100+ different use cases within Uber and that number grows quickly. Collectively, there are 50M+ ongoing executions at any moment on average and our customers finish 3B+ executions per month. Outside of Uber, we also know that many engineering teams at various companies have already adopted Cadence for their business-critical workflows. We are excited to continue evolving Cadence as an open-source project in a backward-compatible way with an increased focus on reliability, scalability, and maintainability in the near term. 
> Stay tuned for more updates and additions to the Cadence project from our team!
> Going forward, we look forward to collaborating with Maxim and Samar and the rest of the open-source community!  
> If you have any questions, please feel free to reach out to us here in Slack or via email at emrah@uber.com and meiliang@uber.com.

**Comment by listaction** [comment]
good story - nicely cleaned up :)
