### ISSUE TITLE
Port Go service and client to the new error handling

### ISSUE THREAD

**Issue by mfateev** [temporalio/temporal#30]
https://github.com/golang/go/wiki/ErrorValueFAQ

The most important part is that checks of error types should use the newly added methods `errors.Is` and `errors.As` instead of comparison and type assertions.

**Comment by alexshtin** [comment]
This is almost done in `go-sdk`. Server should be slowly updated also.

**Comment by wxing1292** [comment]
let us sync before any work to this issue.

server already has error type conversion in place, which makes `errors.Is` and `errors.As` verbose.

**Comment by samarabbas** [comment]
@alexshtin and @wxing1292 this issue is active for too long.  We should make a call and decide if anything is needed here.  Otherwise let's close the issue.
