### ISSUE TITLE
Temporal server setup with mysql

### ISSUE THREAD

**Issue by shiva0612** [temporalio/temporal#3007]
## Expected Behavior
Temporal server should have been started with Mysql running on another server in the same network

## Actual Behavior
Temporal server says "`invalid default value for session_start (a column in cluster_membership table created during schema setup)`"

## Steps to Reproduce the Problem
1. Run the Mysql on another server in the same network

2.Run the docker-compose file for mysql -> docker-compose-mysql-es.yml, by editing the Temporal container settings as follows
 temporal:
    container_name: temporal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DB=mysql
      - DB_PORT=3306
      - MYSQL_USER=TemporalUser
      - MYSQL_PWD=mypsw
      - MYSQL_SEEDS=14.20.202.155
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
      - ENABLE_ES=false
      - SKIP_DB_CREATE=true
      - SKIP_SCHEMA_SETUP=true
     
    image: temporalio/auto-setup:${TEMPORAL_VERSION}
    networks:
      - temporal-network
    ports:
      - 7233:7233
    volumes:
      - ./dynamicconfig:/etc/temporal/config/dynamicconfig
  

## Specifications

  - temporal Version:1.16.2 
  - Mysql version : 8.0.29

**Comment by alexshtin** [comment]
I believe this is fixed in #3012.
