### ISSUE TITLE
Temporal Cassendra Failing issue in Kubernetes

### ISSUE THREAD

**Issue by benji18son** [temporalio/temporal#3010]
Hi Team,

Reported a issue in this below mentioned thread kindly please help us to resolve this issue.

https://community.temporal.io/t/temporal-cassendra-failing-issue-in-kubernetes/4891

**Comment by benji18son** [comment]
Any update

**Comment by yiminc** [comment]
Based on the community thread, it seems like a environment setup issue. The helm chart, as the name `temporaltest` suggest, is not meant to be used as production environment. It may be because there was only one cassandra node. But clearly the cassandra was having trouble starting up.
