### ISSUE TITLE
Reduce the memory footprint of docker-compose-es

### ISSUE THREAD

**Issue by mfateev** [temporalio/temporal#308]
From slack:

> Working on integrating Cadence+ES+Kibana into our existing dev docker-compose constellation. The entire stack is getting pretty heavy to run on our dev machines. Without yet knowing much of anything about Cassandra or ES config, just wondering if it would be feasible for us to tune the configs for those to get them to consume less RAM (hoping we might be able to cut their RAM utilization in half)?

**Comment by markmark206** [comment]
This change reduced ElasticSearch container's (and the overall `docker-compose-es`'s memory requirements): https://github.com/temporalio/temporal/commit/729c8e458ac0fd3bf6d6f1ad509b2e20300e2bd9#diff-88f33e8e16988f6f86017093884fb3aaR27 

Some details on "before" and "after" memory usage: https://github.com/temporalio/temporal/pull/311#issuecomment-615548811

**Comment by mfateev** [comment]
Awesome!
