### ISSUE TITLE
clean up history_node and history_tree

### ISSUE THREAD

**Issue by CarlosEssun** [temporalio/temporal#3122]
## Expected Behavior
i used Mysql Engine ,I don't know if there is a command or tool to periodically clear the history node table and history tree table.  I would like to periodically clean up history_node and history_tree.

## Actual Behavior
history_node and history_tree tables continue to increase, no cleaning method found.

## Specifications

  - Version: temporal 1.16.2
  - Platform: kubernets

**Comment by yiminc** [comment]
Data in history tables will be removed after workflow retention time. You may want to reduce your retention time to a shorter duration if the storage become a concern.

**Comment by CarlosEssun** [comment]
thx
