### ISSUE TITLE
Assert shard ownership against source of truth when acquireShards is invoked

### ISSUE THREAD

**Issue by wxing1292** [temporalio/temporal#3135]
acquireShards function right now only assert shard (in mem) data structure is in valid state, additional assertion should also be performed against DB (source of truth), e.g. using `AssertShardOwnership` persistence API 

https://github.com/temporalio/temporal/blob/v1.17.1/service/history/shard/controller_impl.go#L344

**Comment by dnr** [comment]
In order to `AssertShardOwnership` you need to have the current `RangeID`, right? So this is only for shards that are already loaded?
