### ISSUE TITLE
History service: use a separate context when IO

### ISSUE THREAD

**Issue by wxing1292** [temporalio/temporal#3178]
**Is your feature request related to a problem? Please describe.**
History shard will override the context to ensure minimal timeout, however, this [checking / overriding logic](https://github.com/temporalio/temporal/blob/v1.17.2/service/history/shard/context_impl.go#L1967) does not prevent caller from cancelling the call, potentially causing shard instability (assert shard whenever see non shard ownership lost error)

thanks @nagl-temporal for finding this potential issue

**Comment by nagl-temporal** [comment]
To repro: Insert a short (I used 10ms) sleep in UpdateWorkflowExecution to increase the chances that context cancellation occurs during the persistence operation. start a reasonably chatty (parallelism=4) maru workload against temporal running locally. Ctrl-c your bench-go worker - you should see rangeID updates in the log from reliable-shard. You may have to do this a few times to get unlucky (or increase the sleep).

It's definitely weird that a badly behaved client can trigger rangeID updates.
