### ISSUE TITLE
Statsd docker volume growth 

### ISSUE THREAD

**Issue by mfateev** [temporalio/temporal#319]
Reported by a customer:

> After 4/5 days having left the system IDLE, without doing anything, the graphite/statsd container volume grew to 7/8GB size

IMHO we should not include statsd container in the default development docker-compose.

**Comment by markmark206** [comment]
Good point. I have recently removed `statsd` from `docker-compose-es.yml` (when cleaning it up while looking into `ElasticSearch` helm integration):

https://github.com/temporalio/temporal/pull/311/files#diff-88f33e8e16988f6f86017093884fb3aaL7-L13

I will address this in the remaining docker compose files in the near future.

**Comment by markmark206** [comment]
apparently, removing statsd from docker-compose breaks things, as reported by Pedro (thank you for the report!) https://community.temporal.io/t/issues-running-docker-compose-for-mysql-in-local-environment/123

**Comment by kkcmadhu** [comment]
is custom coding required for extracting metrics through prometheus or  will temporal include this by default?

**Comment by markmark206** [comment]
> is custom coding required for extracting metrics through prometheus or will temporal include this by default?

@kkcmadhu – i think the answer is there is no custom coding to enable prometheus metrics scraping, but there is a bit if config.

Some details:

Temporal's "batteries included' "demo" helm chart [configures temporal for prometheus scraping](https://github.com/temporalio/helm-charts/blob/520c0db6f5bf3413c00453064550bd00c8a2d785/templates/server-configmap.yaml#L103-L105) and [includes a few dashboard](https://github.com/temporalio/helm-charts/blob/520c0db6f5bf3413c00453064550bd00c8a2d785/values.yaml#L290-L298).

In docker-compose world, one should be able to configure a prometheus endpoint [by providing `PROMETHEUS_ENDPOINT`  environment variable](https://github.com/temporalio/temporal/blob/3fb0ca84bb39948f407dbd40b16a0671c5dcbbdb/docker/config_template.yaml#L100-L105), but I don't think we have any `docker-compose` examples of that. 

In non-docker world, when running temporal natively, we have a [config file with a sample prometheus configuration](https://github.com/temporalio/temporal/blob/3fb0ca84bb39948f407dbd40b16a0671c5dcbbdb/config/development_prometheus.yaml#L28-L31). However, I am not sure how much testing that file gets, so be aware. ;)  

Please let me know if this doesn't answer your question!
