### ISSUE TITLE
Add sentry support

### ISSUE THREAD

**Issue by mlcdf** [temporalio/temporal#3203]
Hello,

**Is your feature request related to a problem? Please describe.**
Errors get lost in the logs.

**Describe the solution you'd like**
Report errors and panics to Sentry using the [Go sdk](https://docs.sentry.io/platforms/go/). 

**Describe alternatives you've considered**
None. It seems like Sentry is the industry standard for this.

**Comment by qiuyuzhou** [comment]
https://github.com/sdcxtech/sentrytemporal
sentry interceptor for go sdk
@mlcdf

**Comment by yiminc** [comment]
No plan to do so in near future.
