### ISSUE TITLE
Make Dynamic Config File Injectable

### ISSUE THREAD

**Issue by sunjiawen** [temporalio/temporal#321]
Can we Make Dynamic Config File Injectable! @samarabbas

**Comment by samarabbas** [comment]
@markmark206 we need to evaluate if dynamic config for the server can be injected into Temporal docker image.  Maybe we can expose it as an environment variable for the server.

**Comment by mfateev** [comment]
Can the user attach a volume to the docker image and pass the path to the config file using the existing environment variable?

**Comment by anz-rfc** [comment]
based on what's currently in the `docker-compose.yml` file, this appears to have been resolved earlier by https://github.com/temporalio/temporal/commit/2a4449cc764dc4d24e226525e85ce0a05539dfab

**Comment by samarabbas** [comment]
Closing this issue as dynamic config file path is configurable.
