### ISSUE TITLE
Admin API should query history tasks from source of truth

### ISSUE THREAD

**Issue by wxing1292** [temporalio/temporal#3211]
**Is your feature request related to a problem? Please describe.**
Admin API should query history tasks from source of truth, i.e. history service, instead of query DB directly, in case history service cache tasks in memory.

[Reference](https://github.com/temporalio/temporal/blob/v1.17.2/service/frontend/adminHandler.go#L592)

**Comment by yycptt** [comment]
https://github.com/temporalio/temporal/pull/5426
