### ISSUE TITLE
SQL indexes improvement

### ISSUE THREAD

**Issue by javiercanillas** [temporalio/temporal#3222]
**Is your feature request related to a problem? Please describe.**
I’m testing a helm deployment using a postgresql instance as persistance (schema I used: [temporal/schema.sql at master · temporalio/temporal · GitHub 1](https://github.com/temporalio/temporal/blob/master/schema/postgresql/v96/temporal/schema.sql)).

Doing some analysis on stress testing results, I came across heavy load over the table history_node.
The queries with lots of executions and heavy IO were:

INSERT INTO history_node (shard_id, tree_id, branch_id, node_id, prev_txn_id, txn_id, data, data_encoding) VALUES (?) ON CONFLICT (shard_id, tree_id, branch_id, node_id, txn_id) DO UPDATE SET prev_txn_id=$9, data=$10, data_encoding=$11
DELETE FROM history_node WHERE shard_id = $1 AND tree_id = $2 AND branch_id = $3 AND node_id >= $4
SELECT node_id, prev_txn_id, txn_id, data, data_encoding FROM history_node WHERE shard_id = $1 AND tree_id = $2 AND branch_id = $3 AND ((node_id = $4 AND txn_id > $5) OR node_id > $6) AND node_id < $7 ORDER BY shard_id, tree_id, branch_id, node_id, txn_id LIMIT $8

**Describe the solution you'd like**
From my simple logic, creating an index with the corresponding values (shard_id, three_id, branch_id, node_id and txn_id) can help to get rid some of the inconvenience, but it will add some little pressure over the inserts.

**Describe alternatives you've considered**
- Maybe partitioning those tables based on shard_id, but it requires manual effort to configure and keep sync with the `numShards` config attribute.

**Comment by yiminc** [comment]
What do you mean by shard those table on shard_id? MySQL is not sharded. There is other cloud based SQL like vitess that provide sharded MySQL and you can specify shard_id as their sharding key.

**Comment by yiminc** [comment]
The index you proposed is already the primary key.
PRIMARY KEY (shard_id, tree_id, branch_id, node_id, txn_id)

**Comment by javiercanillas** [comment]
> The index you proposed is already the primary key. PRIMARY KEY (shard_id, tree_id, branch_id, node_id, txn_id)

True, My bad.
