### ISSUE TITLE
Add server capability for worker versioning

### ISSUE THREAD

**Issue by Sushisource** [temporalio/temporal#3230]
We need to add a server-side capability flag for worker versioning here: https://cs.github.com/temporalio/temporal/blob/aadbbacf1a84e1d2c0970842c4e92175a90a3b59/service/frontend/workflowHandler.go?q=capabilities#L2955

After, or as part of, #3127

**Comment by dnr** [comment]
api change: https://github.com/temporalio/api/pull/219/
