### ISSUE TITLE
Add option to allow activities to fail without failing workflow

### ISSUE THREAD

**Issue by BruceNocentini** [temporalio/temporal#3272]
**Is your feature request related to a problem? Please describe.**
We have workflows that contain activities where their completion being "best effort" is enough. 
There is no way for a workflow to skip a failed activity.

**Describe the solution you'd like**
In some scenarios we still want to catch and report activity failures, but even if the activity runs out of retries or times out, we do not want the workflow to fail entirely, instead we just want it to be skipped after their allotted retries.

Is there a specific reason for this type of behavior not the be available?

**Describe alternatives you've considered**
So far the only alternative to the problem is to ignore failures and return "nil", even if an activity fails.
Although this works, the UI displays the activity as "succeeded" and our best alternative to see these cases is to log it and use metrics to quantify these cases.

**Comment by yiminc** [comment]
I'm confused. In your workflow, after you get the error from activity, you can decide what you wanna do with it, you can ignore that error and keep going.

**Comment by BruceNocentini** [comment]
That is what we are doing.
The option above would allow us to have something like the following:

- Workflow triggers activity1 and it fails
- Workflow retries activity1 according to the ActivityOptions(which includes the "skip if out of retries/timeout" option)
- Activity1 runs out of retries/times out
- Mark activity1 as failed
- Workflow continues on to the next activity

With the solution you suggested, I fail to understand how we'd be able to accomplish the scenario above.
That is what I meant with "best effort". Try as many times as we want, but if it still fails, move on without failing the entire workflow. In our case, these activities are not required, but a "nice to have" if they complete successfully.

**Comment by yiminc** [comment]
You are able to do so already. Here is a sample code:
```
func MyWorkflow(ctx workflow.Context) error {
  ...
  // setup proper retry policy for activities...
  f1 := workflow.ExecuteActivity(ctx, "MyBestEffortActivity", ...)
  err1 := f1.Get(nil)
  // here you can ignore err1 from MyBestEffortActivity and keep going 
  f2 := workflow.ExecuteActivity(ctx, "OtherActivity", ...)
  ...
}

```

**Comment by BruceNocentini** [comment]
Ok, that makes sense. We were already doing that and I just wondered if this could be a new flag/feature.
Thank you for your input. I'll close this issue.
