### ISSUE TITLE
[Flaky Test] TestIntegrationSuite/TestArchival_ArchiverWorker

### ISSUE THREAD

**Issue by yux0** [temporalio/temporal#3277]
## Expected Behavior
[Flaky Test] TestIntegrationSuite/TestArchival_ArchiverWorker

## Actual Behavior
https://buildkite.com/temporal/temporal-public/builds/5311#0182eae0-ea7d-4770-80f0-15775c30252c

**Comment by MichaelSnowden** [comment]
Won't fix because archival is being rewritten, and we have simply disabled this test for now.
