### ISSUE TITLE
Add TLS config support for es-visibility

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/temporal#3292]
Currently we support username/password config for es-visibility, but seems not TLS.
Please add if possible.

**Comment by Danprot** [comment]
TLS is a must for infrastructure, add it please

**Comment by johnkm516** [comment]
Please add support for this... 

TLS is a basic requirement in production and currently we cannot connect to Elasticsearch if it has TLS with self signed certs.

**Comment by rahul799** [comment]
Any updates on this? Please add a support.

**Comment by SerheoReutty** [comment]
Hello! Please, help me. How i can connect temporal on ElasticSearch over tls?
