### ISSUE TITLE
StartTime is used as LastHeartbeatUpdateTime

### ISSUE THREAD

**Issue by yiminc** [temporalio/temporal#3358]
For activity that never heartbeat, if you DescribeWorkflow the PendingActivity will have LastHeartbeatUpdateTime set to same value as StartTime. It should be nil if it never received a heartbeat.

**Comment by MichaelSnowden** [comment]
Looks like the bug is here: https://github.com/temporalio/temporal/blob/09c2051766959716bc80ddc2bdf932c411b046a0/service/history/workflow/mutable_state_impl.go#L2049

And maybe elsewhere. I can take a look if you'd like
