### ISSUE TITLE
Auth interceptor - add ability to pull auth info from custom headers

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/temporal#3362]
Currently auth interceptor requires tls or authorization header present: https://github.com/temporalio/temporal/blob/master/common/authorization/interceptor.go#L91

Users would like to be able to define custom headers where this info is present instead.

**Comment by belokrylov** [comment]
This feature would be great because it will allow to use custom security headers defined by a company instead of hardcoded "authorization" and "authorization-extras" that is forced today by the code. I would love to configure my custom security header and trigger authorization based on it with or without "authorization" header.

**Comment by steveandroulakis** [comment]
Any update on this one? Thank you!

**Comment by belokrylov** [comment]
I can provide more details on this if needed.

**Comment by dnr** [comment]
Hi @belokrylov, would it be acceptable to allow overriding those two header names (in static config), or do you want the ability to examine an arbitrary number of headers? The latter would require changing the interface which is a little more involved.

**Comment by belokrylov** [comment]
Yes, that would be fine.

**Comment by belokrylov** [comment]
Please check for second header as well. First or second should be checked.

**Comment by dnr** [comment]
Could you check if PR #4935 works for you?

**Comment by belokrylov** [comment]
My developers did review the change.
Would it be possible to add into if statement on line 102 code  "||
len(authExtraHeaders) >0"

We use authheaders or authextraheaders or both together.
Example use case:
One is for jwt. Second for client certificate that is passed as a custom
header.

**Comment by dnr** [comment]
Would you be able to use this feature?
https://github.com/temporalio/temporal/blob/4be14dd3308031219db02945a12a2cf7d29614b3/common/authorization/claim_mapper.go#L60-L65
You can implement `AuthInfoRequired` and return `false` and the ClaimMapper will be called in all cases.

(I know it's a little awkward, but I'm trying to avoid making drastic changes to the interface or semantics to avoid breaking existing custom ClaimMappers.)

**Comment by belokrylov** [comment]
Yes. That will work for us!
Thank you for bringing this to our attention.
We are good with the PR.

Thank you so much for working on it and checking in with us!

**Comment by belokrylov** [comment]
Thank you so much!
