### ISSUE TITLE
Use dashes in CLI arguments

### ISSUE THREAD

**Issue by feedmeapples** [temporalio/temporal#338]
Usually CLIs use dashes instead of _ . That way is easier to type the arguments as you only use one special character instead of switching between two separators

so ex instead of --execution_timeout, suggesting we do --execution-timeout and follow that pattern everywhere?

**Comment by samarabbas** [comment]
@feedmeapples can you close this issue?  Looks like it should be addressed by the recent CLI work.

**Comment by feedmeapples** [comment]
@samarabbas right!
here is the proposal, it's approved and implemented https://github.com/temporalio/proposals/pull/30
