### ISSUE TITLE
Failed to execute script docker-compose

### ISSUE THREAD

**Issue by gaurav9822** [temporalio/temporal#3407]
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

Solution - start docker

Suggestion - Error message should be docker is not running

**Comment by mindaugasrukas** [comment]
Hi, could you provide reproduction steps? Thanks.

**Comment by mindaugasrukas** [comment]
External tool issue.
