### ISSUE TITLE
Workflow reset is broken for child/parent relationships

### ISSUE THREAD

**Issue by Aayyush** [temporalio/temporal#3437]
## Expected Behavior
When I reset a child workflow, the parent workflow should not register a `ChildWorkflowExecutionTerminated` event. 

## Actual Behavior
When I reset a child workflow, the parent workflow should understand that the child workflow was reset to a certain event instead of registering a `ChildWorkflowExecutionTerminated` event.

## Steps to Reproduce the Problem

  1. Create a temporal workflow and spin up a child workflow that simply sleeps for 5 minutes, and waits for the child workflow to finish execution before exiting the parent workflow. 
  2. While the child-workflow is in progress, reset the child workflow to the beginning of the event history. 
  3. The parent workflow should see a `ChildWorkflowExecutionTerminated` event when the child-workflow was reset. As a result, the parent workflow exits leaving the child workflow orphaned.  

## Specifications

  - Version: 1.16.2
  - Architecture: x86_64
  - Platform: Ubuntu 18.04.6 LTS

**Comment by yiminc** [comment]
This is fixed in https://github.com/temporalio/temporal/pull/2913, and available in v1.17
