### ISSUE TITLE
problems happened with `go.temporal.io/sdk/internal.(*commandsHelper).getNextID`

### ISSUE THREAD

**Issue by zhamdoctor** [temporalio/temporal#3446]
![image](https://user-images.githubusercontent.com/29030455/193173002-085459da-dd74-4181-bd1e-a338fb604da6.png)

![image](https://user-images.githubusercontent.com/29030455/193173093-4898b868-dc04-4836-abe0-29f797f0f032.png)
something happened with temporal,strace reports that  context deadline exceeded.how can i debug or find out what is wrong with this?

**Comment by zhamdoctor** [comment]
![Uploading image.png…]()

**Comment by yiminc** [comment]
Error: Attempt to generate a command before processing WorkflowTaskStarted event.
