### ISSUE TITLE
Range queries do not work with sqlite driver (temporalite)

### ISSUE THREAD

**Issue by joelmarty** [temporalio/temporal#3454]
## Expected Behavior

It should be possible to list workflows using range queries.

## Actual Behavior

Running `tctl workflow list --query "WorkflowId >= 'test-workflow-' and WorkflowId < 'test-workflow-zzzzzzz'"` yields the following error:
```
Error: Failed to list workflow.
Error Details: invalid query: unable to convert filter expression: operator '>=' not allowed in comparison expression
```

## Steps to Reproduce the Problem

1. Run temporalite: `./temporalite start --ephemeral -n default`
2. Run query: `tctl workflow list --query "WorkflowId >= 'test-workflow-' and WorkflowId < 'test-workflow-zzzzzzz'"`

## Specifications

- Version: 0.2.0
- Platform: darwin-amd64

**Comment by yiminc** [comment]
This will be fixed when the advanced visibility API is supported on SQL. We are actively working on that. Will update (close) when that is done.

**Comment by joelmarty** [comment]
> This will be fixed when the advanced visibility API is supported on SQL. We are actively working on that. Will update (close) when that is done.

Advanced visibility for SQL was released if I am not mistaken, is there something else that needs to be done to close this issue ?
