### ISSUE TITLE
Grouping workers and setting tag to a workflow execution, so that workflows with a specific tag run on a specific worker group

### ISSUE THREAD

**Issue by abexamir** [temporalio/temporal#3506]
I want some executions of a workflow run on a specifc worker (e.g a worker in another geographical location, for less latency, specific hardwers or access control).
**Suggested solution**
A feature to group or tag workers, so that they're distinguishable from other workers, and a way to set a tag or class id on a specific workflow  execution that  can be matched with a worker group.

**Comment by yiminc** [comment]
Could you use different task queue for each group of workers?

**Comment by yiminc** [comment]
Using task queue should meet your needs.
