### ISSUE TITLE
Config 1 single database for default and visibility schema

### ISSUE THREAD

**Issue by hoangtrongphuc** [temporalio/temporal#3522]
**Is your feature request related to a problem? Please describe.**
Why temporal need to 2 other database for default and visibility ?

**Describe the solution you'd like**
I would like to know how to use 1 mysql database for  default and visibility (maybe elasticsearch for advance visibility)

**Comment by yiminc** [comment]
You still need 2 configuration for default and visibility, but they can point to the same database instance.
