### ISSUE TITLE
System worker fails to connect to a Frontend in the TLS enabled cluster after removing the publicClient settings

### ISSUE THREAD

**Issue by andrey-dubnik** [temporalio/temporal#3527]
## Expected Behavior

System worker should be able to connect to a Frontend service resolved by a new service discovery when a publicClient configuration is removed and a Temporal cluster is TLS enabled

## Actual Behavior

Worker fails to connect to the cluster with a message below

```
{“level”:“warn”,“ts”:“2022-10-20T08:51:40.097Z”,“msg”:“error creating sdk client”,“service”:“worker”,“error”:“failed reaching server: context deadline exceeded”,“logging-call-at”:“factory.go:116”
```

The probably cause can be in a service discovery returning IP while the Client SDK TLS host validation failing on a cert DNS not matching the IP

More details on the problem is in the [community post](https://community.temporal.io/t/temporal-worker-failing-to-connect-to-frontend-in-1-18-2-post-removing-publicclient-from-config/6262)

## Steps to Reproduce the Problem

1. enable TLS on the cluster
2. start all services

## Specifications

  - Version: 1.18.2
  - Platform: Linux

**Comment by yiminc** [comment]
@andrey-dubnik , the v1.18.2 has an issue during startup that will see similar error like what you posted. We have fixed that with [1.18.3](https://github.com/temporalio/temporal/releases/tag/v1.18.3), could you try it and see if that solve your problem?
