### ISSUE TITLE
Issue with timestamp for UI.  Always shows the last event timestamp for all jobs

### ISSUE THREAD

**Issue by darewreck54** [temporalio/temporal#353]
![image](https://user-images.githubusercontent.com/16171726/81086180-04d86b80-8ead-11ea-9c57-80e282685fb0.png)

Multiple workflows get triggered within different times of the day, but it looks like it just sets everything to the newest date.  I think this is a bug.

**Comment by feedmeapples** [comment]
There was a similar issue filed in temporal-web repo almost at the same time https://github.com/temporalio/temporal-web/issues/33 . 
I will mark the current one as duplicate since the issue come from temporal-web
