### ISSUE TITLE
Upgrade OTel Go dependencies

### ISSUE THREAD

**Issue by liustanley** [temporalio/temporal#3556]
**Is your feature request related to a problem? Please describe.**
I'm trying to use the [MeterProvider](https://pkg.go.dev/go.opentelemetry.io/otel/sdk/metric@v0.33.0#MeterProvider) introduced in v0.32.0 for the otel metrics sdk, but my project imports Temporal which uses v0.31.0. This causes a dependency conflict because the newer versions deprecate some folders and I can't use the new version of the sdk.

**Describe the solution you'd like**
I wanted to request to keep the OTel dependencies in sync, or upgraded to v0.32.0 if v0.33.0 causes breaking changes.

**Additional context**
Seems to be the same problem described in https://github.com/temporalio/temporal/issues/2321

**Comment by yiminc** [comment]
The v0.32 upgrade removes the ability to specify custom histogram buckets boundaries. We are waiting for this to be fixed before we could upgrade. See this discussion: https://github.com/open-telemetry/opentelemetry-go/discussions/3412

**Comment by liustanley** [comment]
@yux0 @yiminc [opentelemetry-go v0.34.0](https://github.com/open-telemetry/opentelemetry-go/releases/tag/v1.11.2) just got released today which should fix this issue, would it be possible to upgrade now?

**Comment by mx-psi** [comment]
@yux0 do you have a rough idea on when the next release will happen?

**Comment by bogdanov1609** [comment]
@yux0 friendly reminder on this one

**Comment by yux0** [comment]
I will try to have the upgrade in the next server release 1.20. The rough guess about the next release is around the end of January 2023.

**Comment by bogdanov1609** [comment]
> I will try to have the upgrade in the next server release 1.20

@yux0 how is release going? :)

**Comment by yux0** [comment]
The release is targeting early next week(02/13).

**Comment by yux0** [comment]
Temporal server upgrade otel to 0.34 with the latest release 1.20.
