### ISSUE TITLE
Cron workflow should have ability to stop cron job

### ISSUE THREAD

**Issue by mfateev** [temporalio/temporal#356]
Currently a cron workflow cannot stop/change its cron execution. Each run can complete or fail, but the behaviour in any case is determined by a schedule provided on start.

This also should support the following customer request:

> Hi, is there a way to terminate a cron scheduled workflow in a way that doesn't terminate it while it's running, but prevents the next execution?

**Comment by yckbilly1929** [comment]
also looking for a way to schedule a workflow to run once only in future time

**Comment by yiminc** [comment]
The new [schedule workflow](https://docs.temporal.io/concepts/what-is-a-schedule) now support to stop new runs (without terminating current run), and ability to make schedule that runs only once.
