### ISSUE TITLE
Add option to batch API to specify a list of workflow executions

### ISSUE THREAD

**Issue by yiminc** [temporalio/temporal#3572]
Current batch API allow user to specify a visibility query and take action on the result set.
There are use cases where user already have the list of workflow executions that they want to apply action on.
In such case, it would be very nice for the API to be able to take a list of workflow executions as input.

User should be able to specify either a query OR a list of workflow executions, but not both.
The size of the list should have some max limit, for example 1000.

**Comment by calum-stripe** [comment]
I like this idea but why limit the lis size? is the query size limited too?

**Comment by CristopherVidalMachado** [comment]
That's cool and I like the idea too, it would be interesting to query all workflows and all their children as well.
