### ISSUE TITLE
Support explicit infinite timeout for workflows

### ISSUE THREAD

**Issue by rylandg** [temporalio/temporal#358]
When running Temporal on top of Cassandra attempting to create a TTL that will end after `2038-01-19T03:14:06+00:00` returns a failure.

```json
{
  "error":"CreateTasks operation failed. Error : Request on table temporal.tasks with ttl of 630720000 seconds exceeds maximum supported expiration date of 2038-01-19T03:14:06+00:00. In order to avoid this use a lower TTL, change the expiration date overflow policy or upgrade to a version where this limitation is fixed. See CASSANDRA-14092 for more details.",
"}
```

This is only true when using Temporal with Cassandra and is due to a Cassandra limitation regarding TTL. Temporal could solve this problem for end users by explicitly allowing an infinite timeout when running workflows. I quoted my own explanation of the issue from Slack to give more context:

> As the output states, it's possible to adjust the Cassandra overflow policy, but that actually doesn't effect this limitation. The policy can be changed to:
 
> 1. reject TTLs that would overflow past 2038-01-19T03:14:06+00:00
> 2. truncate TTLs that overflow to a max of 2038-01-19T03:14:06+00:00 and warn the user
> 3. truncate TTLs that overflow to a max of 2038-01-19T03:14:06+00:00 and suppress a warning to the user
 
> AFAIK it's not possible to actually have a TTL that ends after 2038-01-19T03:14:06+00:00

**Comment by wxing1292** [comment]
v1.4.1 solved this issue
