### ISSUE TITLE
Slack invite link is not active

### ISSUE THREAD

**Issue by gaurav9822** [temporalio/temporal#3613]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yiminc** [comment]
go to https://temporal.io/ and click join Slack or click below link:
https://temporalio.slack.com/join/shared_invite/zt-1i173003n-E2J69y3nlXEJIMpkAb54bg#/shared-invite/email
