### ISSUE TITLE
Temporal UI K8s deployment listing workflows fails with elastic error

### ISSUE THREAD

**Issue by orby-will** [temporalio/temporal#3631]
## Expected Behavior
temopral UI list workflows correctly

## Actual Behavior

failure wit the following error message:
ListWorkflowExecutions failed: elastic: Error 400 (Bad Request): all shards failed [type=search_phase_execution_exception], root causes: Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [RunId] in order to load field data by uninverting the inverted index. Note that this can use significant memory. [type=illegal_argument_exception]

<img width="1323" alt="image" src="https://user-images.githubusercontent.com/109645399/203100697-5237f812-8798-40d7-854f-77f24fe6e061.png">

## Steps to Reproduce the Problem
Launch the k8s deployment with the following command:
kubectl apply -n temporal -R -f https://raw.githubusercontent.com/temporalio/docker-compose/main/k8s/temporal.yaml

## Specifications
Deployed on GKE

**Comment by yiminc** [comment]
@orby-will what is your query? And which types are those fields?

**Comment by orby-will** [comment]
<img width="1377" alt="image" src="https://user-images.githubusercontent.com/109645399/203129244-dd70977e-c7aa-4171-9130-3593d3842080.png">

**Comment by orby-will** [comment]
Can someone please at least help point me to the right direction?

**Comment by orby-will** [comment]
@yiminc hi there, I am still blocked here. Do you mind taking another look/

**Comment by orby-will** [comment]
Friendly ping

**Comment by yiminc** [comment]
This looks like a misconfiguration of the elastic search for visibility. Please seek help in community forum. https://community.temporal.io/ Thanks.
