### ISSUE TITLE
Currently temporal provides no way to reset the workflow from a serialized history json

### ISSUE THREAD

**Issue by pratyoosh** [temporalio/temporal#3703]
**Is your feature request related to a problem? Please describe.**
Workflow history for failed workflows is purged in temporal after retention time period expires, sometimes fixing a specific defect in complex system can take greater time than retention time for failed workflows.
Trying to reset the workflow after issue has been fixed may not work if the workflow history has been purged, even if the history snapshot was saved for reference when the original issuer occurred. 

**Describe the solution you'd like**
Workflow authors or support teams should be able to save the temporal workflow & replay the stateful history even if the history has been purged from temporal.
Current Replayer only allows in memory replay, AFAIK we cannot have a new run spawned from workflow history json.

**Comment by yiminc** [comment]
This sounds like a workflow import functionality.

**Comment by pratyoosh** [comment]
Yes, this is more of an import from history & possibly continue from a specific event id.

**Comment by yiminc** [comment]
https://github.com/temporalio/temporal/pull/4853/files
