### ISSUE TITLE
Improve logging for ES connection issues

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/temporal#3710]
fx.go: https://github.com/temporalio/temporal/blob/master/temporal/fx.go#L243

Please add ES config value to this error message (so it would include the scheme, host at least from what user configured in static config).

Currently small typos in config can cause this error and its hard to debug / trace it back to values user configured vs some ES specific problem.

**Comment by yiminc** [comment]
config could contain confidential messages, so cannot throw the whole thing in log or error message. 
This PR https://github.com/temporalio/temporal/pull/4811 added more useful info for debugging.
