### ISSUE TITLE
docker-compose-es.yml docker-compose fails with error 137

### ISSUE THREAD

**Issue by pratyoosh** [temporalio/temporal#372]
On Mac OS Catalina (10.15.4) docker engine 19.03.8 running docker-compose -f docker-compose-es.yml up with temporal v0.21.1 fails with elastic search crashing with error code 137

This is due to default memory allocated setting to 2 GB,  which too little to fit temporal with elastic search. Documentation should be enhanced to mention that users change the memory setting for docker before running temporal es docker container.

**Comment by wxing1292** [comment]
https://github.com/temporalio/documentation/pull/240
