### ISSUE TITLE
schema version compatibility check failed: unable to read DB schema version keyspace/database:

### ISSUE THREAD

**Issue by Navnitkumarbarnwal** [temporalio/temporal#3765]
### **I am trying to deploy temporal in. k8s using cloudsql which is a gcp managed service but getting below error**
sql schema version compatibility check failed: unable to read DB schema version keyspace/database: temporal error: Error 1146: Table 'temporal.schema_version' doesn't exist
[Fx] ERROR		Failed to start: could not build arguments for function "[go.uber.org/fx](http://go.uber.org/fx)".(*App).constructCustomLogger.func2 (/go/pkg/mod/go.uber.org/fx@v1.17.1/app.go:415): failed to build fxevent.Logger: could not build arguments for function "[go.temporal.io/server/temporal](http://go.temporal.io/server/temporal)".glob..func8 (/home/builder/temporal/temporal/fx.go:916): failed to build log.Logger: received non-nil error from function "[go.temporal.io/server/temporal](http://go.temporal.io/server/temporal)".ServerOptionsProvider (/home/builder/temporal/temporal/fx.go:163): sql schema version compatibility check failed: unable to read DB schema version keyspace/database: temporal error: Error 1146: Table 'temporal.schema_version' doesn't exist
Unable to start server. Error: could not build arguments for function "[go.uber.org/fx](http://go.uber.org/fx)".(*App).constructCustomLogger.func2 (/go/pkg/mod/go.uber.org/fx@v1.17.1/app.go:415): failed to build fxevent.Logger: could not build arguments for function "[go.temporal.io/server/temporal](http://go.temporal.io/server/temporal)".glob..func8 (/home/builder/temporal/temporal/fx.go:916): failed to build log.Logger: received non-nil error from function "[go.temporal.io/server/temporal](http://go.temporal.io/server/temporal)".ServerOptionsProvider (/home/builder/temporal/temporal/fx.go:163): sql schema version compatibility check failed: unable to read DB schema version keyspace/database: temporal error: Error 1146: Table 'temporal.schema_version' doesn't exist

**Comment by yiminc** [comment]
temporal.schema_version' doesn't exist usually means db was not created.

**Comment by yiminc** [comment]
Please use https://community.temporal.io/ if you need more help on this.
