### ISSUE TITLE
[Feature Request] SignalWithStart for external workflows

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/temporal#3773]
Currently we have SignalWithStartWorkflow (Go SDK) via client api. 
Feature request is to add 
"SignalWithStartExternalWorkflow" (name tbd) which can be called in workflow code. Would behave same as SignalWithStartWorkflow.

**Comment by robholland** [comment]
This is a duplicate of https://github.com/temporalio/temporal/issues/537
