### ISSUE TITLE
Looking for proto.file to implement a C# SDK

### ISSUE THREAD

**Issue by dust63** [temporalio/temporal#3794]
Hello,

I want to create Temporal C# SDK that don't using Rust interop. 
I can understood that you use gRPC to interact between the server and the SDK right ? No Rest API provided ?

Do you have any proto.file or documentation about the contracts to use gRPC ?

Thank you.

**Comment by Sushisource** [comment]
We're developing a first-party .NET SDK here: https://github.com/temporalio/sdk-dotnet/ which will use our Rust Core underneath.

The gRPC definitions are here: https://github.com/temporalio/api

That all said, our SDKs are very complex. It would be a huge undertaking for you to implement one by yourself. We're of course curious to hear any reasons you have that the native core is an issue for you. Feel free to bring those up on our [forum](https://community.temporal.io/) or [Slack](https://t.mp/slack).

**Comment by Sushisource** [comment]
> Yep I know but I don't understood why you want to call Rust library instead to develop directly on .net ?

Because we have TypeScript, Python, and Ruby SDKs all being built on top of the same library
