### ISSUE TITLE
Hammering instance w/ small cache count results in ungraceful response to client

### ISSUE THREAD

**Issue by Sushisource** [temporalio/temporal#3802]
## Expected Behavior
The client ought to see a returned status with the `ResourceExhausted` error code, and a message along the lines of "Can't accept new workflow because `<xyz>`"

## Actual Behavior
Client sees `Unknown` error code with this message: "Cache capacity is fully occupied with pinned elements" - which, while perhaps a true message, isn't terribly useful.

This also causes a _ton_ of errors with full stack traces to get dumped into the logs. Since the right thing to do here is just exert back-pressure, it should probably just log some warnings at most.

Errors include (omitting stacks):
`{"operation": "PollMutableState", "wf-namespace": "default", "error": "Cache capacity is fully occupied with pinned elements", "logging-call-at": "telemetry.go:278"}`

```
{
  "level": "error",
  "ts": "2023-01-11T10:07:09.909-0800",
  "msg": "Persistent fetch operation Failure",
  ...
  "store-operation": "get-wf-execution",
  "error": "context canceled",
  "logging-call-at": "transaction_impl.go:423",
  ...
```

## Steps to Reproduce the Problem
I was able to trigger this 100% reliably by starting 1k workflows concurrently against temporalite - the workflows do nothing but run one activity and finish.

## Specifications
* Version: 1.19 (inside temporalite)
* Platform: Linux

**Comment by ukd1** [comment]
@Sushisource I've just hit this btw 😅

**Comment by ukd1** [comment]
Is there a workaround for this? I don't see an obvious way to change the cache size?

**Comment by yycptt** [comment]
Cache size can be configured by changed the value of `history.cacheMaxSize`, but default is 512 which should be large enough unless there's big backlog in transfer/timer task processing. 

Also if you see the error when using release [v1.21.3](https://github.com/temporalio/temporal/releases/tag/v1.21.3), please upgrade to 1.21.4, .3 version has known issue with the cache size calculation.

Re. backpressure, looks like this should be a resource exhausted error? cc @yiminc WDYT?

**Comment by ukd1** [comment]
@yiminc thanks - I was running 1.21.3 - I'm upgrading and will report back. 

What does "big backlog" mean - I might have 100k+ easily?

**Comment by prathyushpv** [comment]
https://github.com/temporalio/temporal/pull/4796 fixed this issue.
