### ISSUE TITLE
InvalidArgument gRPC error is non-deterministic for the same arguments

### ISSUE THREAD

**Issue by cretz** [temporalio/temporal#3846]
## Expected Behavior

A deadline time that is too close to the system clock should return a different gRPC status code so that callers of gRPC calls can know that `InvalidArgument` is non-retryable for repeated forms of the same input.

## Actual Behavior

If a poll request is made with a deadline time within 2s of the server system clock, an `InvalidArgument` is returned. This only happens when there is a proxy that would hold up a request during internal server outage (very rare). This behavior has existed for years.

Arguably we should stop considering `InvalidArgument` non-retryable on the SDK side which may make this need moot (see https://github.com/temporalio/features/issues/218). This is simply to track potential work/discussion.

**Comment by yiminc** [comment]
https://github.com/temporalio/temporal/pull/3856
