### ISSUE TITLE
Use new CallerTypePreemptable for all queues other than transfer/timer/visibility

### ISSUE THREAD

**Issue by pdoerner** [temporalio/temporal#3874]
**Is your feature request related to a problem? Please describe.**
The new (currently lowest) priority `CallerTypePreemptable` should be used for all replication and all queues other than transfer/timer/visibility to resolve issues of resource contention noticed during namespace migration.

**Describe the solution you'd like**
Right now task executable assumes all tasks are background, we need a ways to specify different caller type for different task categories. Same for the implementation on task loading.

**Describe alternatives you've considered**

**Additional context**
Followup to https://github.com/temporalio/temporal/pull/3870

**Comment by yiminc** [comment]
done
