### ISSUE TITLE
Namespace Delete feature to be available in multi cluster environment

### ISSUE THREAD

**Issue by hema-kishore-gunda** [temporalio/temporal#3888]
**Is your feature request related to a problem? Please describe.**
Namespace Delete function deletes a namespace only in the current cluster. If the environment has multiple clusters, delete namespace doesn't happen in all clusters. Separate connection need to happen to each cluster and execute the delete namespace so as it is deleted in all clusters in a multi-cluster environment set-up.

**Describe the solution you'd like**
While registering a new namespace ClusterReplicationConfig can be passed with RegisterNamespaceRequest.  Similar capability need to be added on for Namespace Delete as well.

**Describe alternatives you've considered**
We are connecting to each cluster individually and deleting the namespace in each cluster seperately.

**Additional context**

**Comment by alexshtin** [comment]
Cross cluster namespace migration can be implemented with replication: enable replication for namespace and then delete in source cluster. This scenario won't be possible if namespace is deleted in all clusters. There might be a flag or special instruction to disconnect namespaces in different cluster first but current behaviour is much safer.

**Comment by hema-kishore-gunda** [comment]
@alexshtin,

We have raised this on community forum initially and tihomir mentioned to raise as a feature request. Hence raised this, please see the below link in community forum. Can this be considered as an enhancement request and delete functionality of namespace occur in all clusters similar to register namespace.

https://community.temporal.io/t/namespace-delete-functionality-deletes-namespace-in-active-cluster/7106

**Comment by yiminc** [comment]
For reason mentioned above regarding namespace migration, we do not plan to support automatically replicate deletion  of namespace across all clusters. Delete namespace is a rare operation so is is reasonable to issue delete requests separately to all clusters.
