### ISSUE TITLE
Namespace default not found after connected with the default namespace

### ISSUE THREAD

**Issue by longquanzheng** [temporalio/temporal#3914]
I will provide detailed repro steps later…

I have to do a wait for 20s after startup iWF server in this hack: https://github.com/indeedeng/iwf/commit/7b38a5bc2423b76f7eb3e28390cfe9a66ce62b55

Otherwise the worker will not working correct (GoSDK) complaining namespace default not found -- even though it's actually registered. I even try use a script automatically register default namespace and it says "the namespace already exists". 

=

**Comment by yiminc** [comment]
This should have been fixed by the namespace read through cache change. https://github.com/temporalio/temporal/pull/3908
