### ISSUE TITLE
msyql read-only This object cannot be started

### ISSUE THREAD

**Issue by luckysanbao** [temporalio/temporal#3989]
mysql master-slave connects to the slave library and the slave library is read-only

The initialization of the temporal database is complete. If the mysql library is set to read_only, So temporal will fail to start and they're temporal-frontend temporal-history temporal-matching temporal-worker.

![image](https://user-images.githubusercontent.com/20633211/221118300-c1ea998c-5f4f-4d8a-856c-796da21ca52d.png)

![image](https://user-images.githubusercontent.com/20633211/221118197-4b449535-ae4c-4d7b-8479-baee6e5062c7.png)

How do we solve this

**Comment by luckysanbao** [comment]
The msyql temporal account has the permission

![image](https://user-images.githubusercontent.com/20633211/221118485-8b5f138b-aa2e-4dca-84ba-1c7dd84ae3cb.png)

**Comment by yiminc** [comment]
I don't understand what the problem is here. Temporal server needs write access to the MySQL db. With read-only, it is expected not working.
