### ISSUE TITLE
Temporal auto setup does not work with Postgres 15

### ISSUE THREAD

**Issue by auyer** [temporalio/temporal#4016]
## Expected Behavior
I am installing Temporal via the Airbyte Helm chart (it relies on Temporal).
After an upgrade to Postgres 15 (AWS RDS), Temporal stopped working.
I've tested various configuration options, and could not get it to work.
Once I pointed it at a Postgres 14 installation, it worked fine.

## Actual Behavior
Temporal fails to validate the connection. In some of my attempts, it created the temporal and temporal_visibility databases, but still failed.

```
+ DB=postgresql
+ SKIP_SCHEMA_SETUP=false
+ KEYSPACE=temporal
+ VISIBILITY_KEYSPACE=temporal_visibility
+ CASSANDRA_SEEDS=
+ CASSANDRA_PORT=9042
+ CASSANDRA_USER=
+ CASSANDRA_PASSWORD=
+ CASSANDRA_TLS_ENABLED=
+ CASSANDRA_CERT=
+ CASSANDRA_CERT_KEY=
+ CASSANDRA_CA=
+ CASSANDRA_REPLICATION_FACTOR=1
+ DBNAME=temporal
+ VISIBILITY_DBNAME=temporal_visibility
+ DB_PORT=5432
+ MYSQL_SEEDS=
+ MYSQL_USER=
+ MYSQL_PWD=
+ MYSQL_TX_ISOLATION_COMPAT=false
+ POSTGRES_SEEDS=rds**************com
+ POSTGRES_USER=dbuser
+ POSTGRES_PWD=************
+ ENABLE_ES=false
+ ES_SCHEME=http
+ ES_SEEDS=
+ ES_PORT=9200
+ ES_USER=
+ ES_PWD=
+ ES_VERSION=v7
+ ES_VIS_INDEX=temporal_visibility_v1_dev
+ ES_SCHEMA_SETUP_TIMEOUT_IN_SECONDS=0
+ TEMPORAL_CLI_ADDRESS=10.12.87.28:7233
+ SKIP_DEFAULT_NAMESPACE_CREATION=false
+ DEFAULT_NAMESPACE=default
+ DEFAULT_NAMESPACE_RETENTION=1
+ SKIP_ADD_CUSTOM_SEARCH_ATTRIBUTES=false
+ '[' false '!=' true ']'
+ validate_db_env
+ '[' postgresql == mysql ']'
+ '[' postgresql == postgresql ']'
+ '[' -z rds.**************.com ']'
+ wait_for_db
+ '[' postgresql == mysql ']'
+ '[' postgresql == postgresql ']'
+ wait_for_postgres
+ nc -z rds.**************.com 5432
+ echo 'PostgreSQL started.'
+ setup_schema
+ '[' postgresql == mysql ']'
+ '[' postgresql == postgresql ']'
PostgreSQL started.
Setup PostgreSQL schema.
+ echo 'Setup PostgreSQL schema.'
+ setup_postgres_schema
+ SCHEMA_DIR=/etc/temporal/schema/postgresql/v96/temporal/versioned
+ '[' temporal '!=' dbuser ']'
+ temporal-sql-tool --plugin postgres --ep rds.**************.com -u dbuser -p 5432 create --db temporal
2023-03-06T17:25:23.143Z    ERROR    Unable to create SQL database.    {"error": "unable to connect to DB, tried default DB names: postgres,defaultdb, errors: [pq: no pg_hba.conf entry for host \"10.12.87.28\", user \"dbuser\", database \"postgres\", no encryption pq: no pg_hba.conf entry for host \"10.12.87.28\", user \"dbuser\", database \"defaultdb\", no encryption]", "logging-call-at": "handler.go:97"}
2023/03/06 17:25:23 Loading config; env=docker,zone=,configDir=config
2023/03/06 17:25:23 Loading config files=[config/docker.yaml]
{"level":"info","ts":"2023-03-06T17:25:23.175Z","msg":"Updated dynamic config","logging-call-at":"file_based_client.go:143"}
{"level":"info","ts":"2023-03-06T17:25:23.175Z","msg":"Starting server for services","value":["history","matching","frontend","worker"],"logging-call-at":"server.go:123"}
Unable to start server. Error: sql schema version compatibility check failed: pq: no pg_hba.conf entry for host "*******", user "dbuser", database "temporal", no encryption
Stream closed EOF for airbyte/airbyte-temporal-5dc4877cb9-hkpw4 (airbyte-temporal)
```

## Steps to Reproduce the Problem
1. Install Temporal with auto setup on Postgres 15
 or
1. Get Airbyte helm chart here: https://github.com/airbytehq/helm-charts
1. change configurations to reflect on your databse credentials
1. install the helm chart

## Specifications
* Version: 1.13.0 (I also tried 1.18 and 1.20)
* Platform: kubernetes

**Comment by rodrigozhou** [comment]
Did you upgrade to Postgres 15 from an older version? Can you check the Postgres logs? I think it's an issue with your upgrade, not Temporal Server.
When I started a fresh DB, everything works as expected. However, if I do straight upgrade of Postgres, I get these logs from Postgres, which I believe is the issue:
```
PostgreSQL Database directory appears to contain a database; Skipping initialization

2023-03-15 23:42:17.506 UTC [1] FATAL:  database files are incompatible with server
2023-03-15 23:42:17.506 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 13, which is not compatible with this version 15.2 (Debian 15.2-1.pgdg110+1).
exited with code 1
```

**Comment by auyer** [comment]
It was upgraded by AWS. Its a managed service. Other services are using the same server with no problems.

**Comment by rodrigozhou** [comment]
@auyer I tried to repro here, but no success.

I don't know the migration steps in AWS, but it seems that Temporal Server can't connect to PostgreSQL. From your logs above, I see this error from PostgreSQL: "pq: no pg_hba.conf entry for host \"10.12.87.28\", user \"dbuser\", database \"postgres\", no encryption".

Can you take a look at if your `pg_hba.conf` is configured correctly to allow Temporal Server to connect to DB using the user `dbuser`?

**Comment by roded** [comment]
Cluster deployment documentation states:
```
PostgreSQL v9.6 and later. Use v12 (or later) with Temporal Server v1.20 or later for Advanced Visibility capabilities.
```
https://docs.temporal.io/cluster-deployment-guide#supported-databases

@rodrigozhou Can we assume Temporal supports postgres 15?

Thanks!

**Comment by rodrigozhou** [comment]
Yes, I tested locally, and it worked as expected.

**Comment by auyer** [comment]
I suppose it is some misconfiguration in the Airbyte conf. I will close this issue. Thanks.

**Comment by thatmlopsguy** [comment]
Anyone tested with RDS PostgreSQL 17.4?
