### ISSUE TITLE
Improve workflow task retry handling

### ISSUE THREAD

**Issue by yycptt** [temporalio/temporal#4022]
**Is your feature request related to a problem? Please describe.**
Exiting logic slows down workflow task retry by increasing workflow task start to close timeout (up to 10min) and rely on the fact that SDK won't respond workflow task failure if workflow task has attempt > 1.

However this does't work well with features that need to wait for pending workflow task to complete. 
One example is Query. If there's a pending workflow, query must wait for it to complete before it can be dispatched. Before that, query is buffered in-memory in workflow mutable state. Now since it can take workflow task a long time to complete, mutable state may get evicted from cache and query API will fail with Unavailable error, or the query API itself can timeout.

**Describe the solution you'd like**
Essentially need a better way for handling workflow task retry

* Workflow pause feature
* Do not override workflow task start to close timeout, but schedule a backoff time for the next workflow task attempt.

**Describe alternatives you've considered**

**Additional context**

**Comment by yiminc** [comment]
We have separate issue to track pause work.
For the query problem, it should fail fast because if workflow task keeps failing, the query would fail as well. Instead of waiting for next workflow task, it is better to fail fast which is already implemented.
