### ISSUE TITLE
Add ability to execute waiting cron immediately

### ISSUE THREAD

**Issue by mfateev** [temporalio/temporal#404]
**Is your feature request related to a problem? Please describe.**
Currently when an existing cron workflow waits for its execution there is no way to force immediate execution of it without terminating it or starting workflow with a different ID.

**Describe the solution you'd like**
Either add special admin command to force execution or use start (with terminateIfRunning id reuse policy) to restart workflow atomically.

**Additional context**
TerminateIfRunning support added to Cadence https://github.com/uber/cadence/pull/3215

**Comment by meetchandan** [comment]
@mfateev TerminateIfRunning feature is also added in temporal ?

**Comment by yiminc** [comment]
TerminateIfRunning is supported: https://github.com/temporalio/api/blob/master/temporal/api/enums/v1/workflow.proto#L48

SignalWithStartWorkflowExecution can be used to execute waiting cron (next run) immediately.
