### ISSUE TITLE
why WorkflowTaskScheduled event didn‘t retry

### ISSUE THREAD

**Issue by zhangkyou** [temporalio/temporal#4070]
## Expected Behavior
Set the WorkflowTaskTimeout in StartWorkflowOptions  with 10second and start this cron workflow in samples-go.
And then kill the worker, I expected the WorkflowTaskScheduled event will retry after 10second timeout,but it always hang on WorkflowTaskScheduled event until reached the WorkflowRunTimeout which was set 65second.

here is the workflowOptions
```
retryPolicy := &temporal.RetryPolicy{
		InitialInterval:    time.Second,
		BackoffCoefficient: 2,
		MaximumInterval:    20 * time.Second,
		MaximumAttempts:    3,
	}

workflowOptions := client.StartWorkflowOptions{
		ID:           workflowID,
		TaskQueue:    "cron",
		CronSchedule: "* * * * *",
		WorkflowIDReusePolicy: 4,
		//WorkflowExecutionTimeout: time.Minute * 2,
		WorkflowRunTimeout: time.Second * 65,
		WorkflowTaskTimeout: time.Second * 10,
		RetryPolicy: retryPolicy,
	}
```

## Actual Behavior
<img width="1579" alt="image" src="https://user-images.githubusercontent.com/7250068/226578565-38f643d1-d7cd-4479-841d-0dab9f950152.png">

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version: docker-compose -f docker-compose-mysql.yml up
  - Platform: mac

**Comment by zhangkyou** [comment]
I think I realized the reason for this scenario when I read the workflow task timeout's explain. [https://docs.temporal.io/workflows#workflow-task-timeout](url)
If the workflow task didn't pulled by worker, this timeout doesn't work.

**Comment by yiminc** [comment]
The task is stilling in the task queue waiting for worker to pick it up. The task did not started, so it won't timeout. 
The event 3 in your screenshot is workflow timeout event (not the workflow task).
