### ISSUE TITLE
Search Attributes fail to be added when executed back to back

### ISSUE THREAD

**Issue by anthonywong555** [temporalio/temporal#4073]
## Expected Behavior

All the search attributes should have been added when using the `temporal operator search-attribute create` **command** back-to-back.

## Actual Behavior

When executing the following command:

```sh
temporal operator search-attribute list | grep Custom
  CustomStringField           Text
```

You can see that only one search attribute was added.

## Steps to Reproduce the Problem

In the terminal, execute the following commands:
  1. temporal server start-dev
  2. temporal operator search-attribute create --name CustomIntField --type Int
  3. temporal operator search-attribute create --name CustomDatetimeField --type Datetime
  4. temporal operator search-attribute create --name CustomKeywordField --type Keyword
  5. temporal operator search-attribute create --name CustomBoolField --type Bool
  6. temporal operator search-attribute create --name CustomDoubleField --type Double
  7. temporal operator search-attribute create --name CustomStringField --type Text

## Workaround

In testing, it looks like if you execute the following command:

```sh
temporal operator search-attribute create \
    --name CustomIntField --type Int \
    --name CustomDatetimeField --type Datetime \
    --name CustomKeywordField --type Keyword \
    --name CustomBoolField --type Bool \
    --name CustomDoubleField --type Double \
    --name CustomStringField --type Text
```

This would save all the search attributes. 

## Specifications

  - Version: Temporal Version 0.6.0 (Server 1.20.0) (UI 2.11.0)

**Comment by rodrigozhou** [comment]
PR https://github.com/temporalio/temporal/pull/4080 should fix the issue.
