### ISSUE TITLE
Canary memory usage always increasing

### ISSUE THREAD

**Issue by skrul** [temporalio/temporal#411]
## Expected Behavior

We expect to be able to run the canary process continuously without any problems :)

## Actual Behavior

The memory usage of the canary process is always increasing, and after about three days it eventually used up 1GB of memory (and was then killed by our k8s cluster due to OOM):

![image](https://user-images.githubusercontent.com/372141/82941811-e1ed2480-9f4b-11ea-8322-1fa4ac266480.png)

## Steps to Reproduce the Problem

Using this canary configuration:
```
canary:
  namespaces: ["canary"]
  excludes: [
    "workflow.archival.history", # known to timeout sanity workflow
    "workflow.archival.visibility", # does not record success?
    "workflow.cancellation", # known to fail
    "workflow.batch", # known to fail
    "workflow.searchAttributes", # known to fail
    "workflow.reset" # known to fail
  ]
```

## Specifications

  - Version: v0.23.0

**Comment by alexshtin** [comment]
Here is the fix: https://github.com/temporalio/temporal-go-sdk/pull/147
