### ISSUE TITLE
Fix uninformative message when targeting nonexistent workflows

### ISSUE THREAD

**Issue by Sushisource** [temporalio/temporal#4118]
**Is your feature request related to a problem? Please describe.**
Various APIs return a very un-helpful error message if the user targets a nonexistent workflow. Often something like this:
```
Status { code: NotFound, message: "sql: no rows in result set", details: b"\x08\x05\x12\x1asql: no rows in result set\x1aB\n@type.googleapis.com/temporal.api.errordetails.v1.NotFoundFailure", metadata: MetadataMap { headers: {"content-type": "application/grpc"} }, source: None }
```

Which I received in response to a workflow cancel request.

**Describe the solution you'd like**
The message in the response should be something meaningful like "Workflow foo-bar was not found when attempting workflow cancellation", rather than some message straight out of the database.

**Comment by bplunkett-stripe** [comment]
To add to a specific case, it's a little extra unintuitive in updating schedules. If a schedule __was__ running but has been deleted, [ it will return "schedule not found"](https://github.com/temporalio/temporal/blob/8753b8eae925648744e98c53f69cf887ec48e59e/service/frontend/workflow_handler.go#L3006-L3010). But if it was never created, it will just return `sql: no rows in result set`. Both errors should probably be the same.

Thanks in advance for all of this!

**Comment by Navbryce** [comment]
To add a specific example of this (and an existing weird behavior)

When updating a schedule a schedule that was running but is no longer running,[ it returns "schedule not found"](https://github.com/temporalio/temporal/blob/8753b8eae925648744e98c53f69cf887ec48e59e/service/frontend/workflow_handler.go#L3006-L3010).

But if updating a schedule that never existed, it returns "sql: no rows in result set".

Thanks in advance for all of the help on this!

**Comment by dandavison** [comment]
Interestingly, the same error results when using the Cassandra persistence backend.
