### ISSUE TITLE
v1.21 is supposed to drop Postgres v9.6 support, but v12 scripts fail on CockroachDB

### ISSUE THREAD

**Issue by Hades32** [temporalio/temporal#4136]
## Expected Behavior
scripts to work on CRDB

## Actual Behavior
` ERROR   Unable to update SQL schema.    {"error": "error executing statement:pq: unimplemented: extension \"btree_gin\" is not yet supported", "logging-call-at": "handler.go:78"}`

## Steps to Reproduce the Problem

  1. run `./temporal-sql-tool update-schema -schema-dir schema/postgresql/v96/temporal/versioned` against a CRDB v22.2.7

## Specifications

  - Version: Temporal 1.20.1
  - Platform: Linux

**Comment by Hades32** [comment]
This also prevents advanced visibility to be used with the SQL backend

**Comment by Hades32** [comment]
@rodrigozhou why is this even used in [1] and [2]? According to https://www.postgresql.org/docs/current/btree-gin.html this is rarely useful and from looking at the other migrations it's not actually used as indexes created without `USING GIN` will use the default index

[1] https://github.com/temporalio/temporal/blob/6f1f02280f72bc92212c98a87c8a21122724490b/schema/postgresql/v12/visibility/schema.sql#L1
[2] https://github.com/temporalio/temporal/blob/6f1f02280f72bc92212c98a87c8a21122724490b/schema/postgresql/v12/visibility/versioned/v1.2/advanced_visibility.sql#L1

**Comment by rodrigozhou** [comment]
@Hades32 Postgres needs to enable btree_gin extension to enable creating multi-column GIN index.
With CockroachDB, it seems that it's not necessary and it works out of the box: https://www.cockroachlabs.com/docs/v22.2/inverted-indexes#multi-column-gin-indexes
Can you try just removing the line `CREATE EXTENSION btree_gin;`?

**Comment by Hades32** [comment]
I will try tomorrow and get back to you.

Is that because of the data types you're indexing? Since 8.4 postgres supports multicolumn indexes with GIN without that extension for default types

**Comment by danthegoodman1** [comment]
TSvector is the main problem. Not sure why that `convert_ts` function exists but it can be replaced either with a cast or CRDB's UDF creation format.

Seems like support for `tsvector` has been merged, but unsure about release: https://github.com/cockroachdb/cockroach/pull/90842

**Comment by Hades32** [comment]
Opened a PR for this

**Comment by yiminc** [comment]
Close this one as there is another one to track support for CRDB.
