### ISSUE TITLE
Reject fast signals when workflow task is failing at continueAsNew

### ISSUE THREAD

**Issue by longquanzheng** [temporalio/temporal#4137]
**Is your feature request related to a problem? Please describe.**
When workflow is closing(continueAsNew/fail/complete), the workflow task would fail if there is any signals received but not processed. This is designed to prevent signals being lost(continueAsNew with unhandled signals). 

This is problematic especially for continueAsNew. In a valid design, workflow should do continueAsNew after processing too many signals, to avoid blowing up the history. However, when signals are coming too fast, workflow task won't be able to process, and failing in a loop 
* WFT scheduled/started
* WFT fail when attempt to continueAsNew, because a signal is received when WFT is completing
* WFT scheduled/started
* ...
As a result, workflow will either get terminated because of history length/size limit (50K events or 50MB) it can't process the signals, or there are too many signals that it can't carry over to next run(limit of workflow input). 

**Describe the solution you'd like**
Option 1: DescribeWF response will return why the last workflow task is failing -- is it trying to do a continueAsNew. So that app can use it to decide rejecting the signals
Option 2: Temporal server will reject the signals based on last continueAsNew failure.
Option 3: instead of failing, apply the buffered signals to next run if workflow is doing continueAsNew, as described in https://github.com/temporalio/temporal/issues/1289 

**Describe alternatives you've considered**
A workaround today is that application will describe workflow to check a pending workflow task attempt, and just reject signals when attempt >1 see https://github.com/indeedeng/iwf/issues/236

**Additional context**

https://temporalio.slack.com/archives/CTQU95E84/p1680537731857359

**Comment by yiminc** [comment]
Fixed in https://github.com/temporalio/temporal/pull/4395
