### ISSUE TITLE
workflow query (cli and sdk)

### ISSUE THREAD

**Issue by kaushiksriram100** [temporalio/temporal#414]
**Is your feature request related to a problem? Please describe.**
Querying for workflow state (strong consistency) results in a error: 
```cluster or namespace does not enable strongly consistent query but strongly consistent query was requested```

**Describe the solution you'd like**
It appears that the dynamic config variable (history.EnableConsistentQueryByNamespace: true) would fix it. Can we make the default as true? I added the dynamic config and it started working (with a latency). 

**Additional context**
It's likely that this might increase the latency. Open to feedback. 

P.S The docs related to this would need an update - https://docs.temporal.io/docs/go-queries. Some notes look outdated (like the valid arguments for a "query_type").

**Comment by alexshtin** [comment]
Query consistency level was completely removed together with dynamic config settings: https://github.com/temporalio/temporal/pull/468. Default is `strong`.

Docs need to be updated though.
