### ISSUE TITLE
Remove requirement for sequential server version upgrades

### ISSUE THREAD

**Issue by mindaugasrukas** [temporalio/temporal#4150]
**Is your feature request related to a problem? Please describe.**
Currently, server version upgrade requires manual sequential upgrades:

https://docs.temporal.io/cluster-deployment-guide#upgrade-server:
```
When upgrading your Temporal Server version, ensure that you upgrade sequentially.
For example, when upgrading from v1.n.x, always upgrade to v1.n+1.x (or the next available version),
and so on until you get to the required version.
```

**Describe the solution you'd like**
Version upgrades should be done automatically using Up & Down migrations.

**Comment by dnr** [comment]
The sequential requirement is not (just) for database schema upgrades, it's for metadata in other places, e.g. cluster metadata table or history shard metadata or queue metadata. Those are encoded in protos so they can't be upgraded by DDL at the database level. And for history shard metadata in particular, migrations would have to obey all the locking rules, so they basically have to be done by the history service itself.

**Comment by mindaugasrukas** [comment]
> The sequential requirement is not (just) for database schema upgrades, it's for metadata in other places, e.g. cluster metadata table or history shard metadata or queue metadata. Those are encoded in protos so they can't be upgraded by DDL at the database level. And for history shard metadata in particular, migrations would have to obey all the locking rules, so they basically have to be done by the history service itself.

I don't see this as a blocker.
[updated the description] Those upgrades are not limited to only running schema migrations. They can run metadata and other migrations too.
