### ISSUE TITLE
[possible bug] ExecuteWorkflow with CronSchedule can lead to client timeout in edge case(s)

### ISSUE THREAD

**Issue by antmendoza** [temporalio/temporal#4182]
## Expected Behavior
Scheduling a cronjob with an invalid date e.g `* * 31 2 *`  should return an immediate error (as it happens when trying to start a corn job with a invalid CronSchedule  e.g. `* * 31 2 a`

## Actual Behavior

Reported by a user 

--- 

We seem to have found an edge case that makes client request timeout on ExecuteWorkflow call to Temporal, suggesting there is possibly an infinite loop server side when evaluating a cron schedule.

Following is an extract of our Golang code using temporal client v1.21.1 to execute a workflow. 

```
func (t *temporal) Create(ctx context.Context, projectId uuid.UUID, envId uuid.UUID, plan schedule.Plan) error {
    workflowOptions := client.StartWorkflowOptions{
        ID:           plan.ID,
        TaskQueue:    "CloudEventEmitter",
        CronSchedule: "* * 31 2 *",
    }

    se := schedule.Event{
        ProjectID:     "projectid",
        EnvironmentID: "envid",
    }

    _, err := t.client.ExecuteWorkflow(ctx, workflowOptions, workflowName, se)
    if err != nil {
        return handleError(err)
    }

    return nil
}

```
It works fine with various Cron entries, but "* * 31 2 *" seems to make request timeout as is not a valid date even though it is valid cron syntax.

Using github.com/robfig/cron library (as found to be the lib used by [temporal](https://github.com/temporalio/temporal/blob/master/go.mod)) we managed to put further validation on this case in our code with the following:

```
       [ parser := cron.NewParser(cron.Minute | cron.Hour | cron.Dom | cron.Month | cron.Dow)](https://github.com/temporalio/temporal/blob/master/go.mod)
       [ s, err := parser.Parse(plan.Schedule)](https://github.com/temporalio/temporal/blob/master/go.mod)
       [ if err != nil || time.Now().After(s.Next(time.Now())) {](https://github.com/temporalio/temporal/blob/master/go.mod)
           [ return errors.New("Invalid cron schedule") ](https://github.com/temporalio/temporal/blob/master/go.mod)
       [ }](https://github.com/temporalio/temporal/blob/master/go.mod)
```

As next schedule time seems to resolve to "0001-01-01 00:00:00 +0000 UTC" in that case.

We have not managed to find other cases where cron schedule would cause a timeout but wanted to raise it to the team as it's possible other entries might cause a similar problem, and we are not fully aware of what side effects it has on the Temporal side.

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:

**Comment by yiminc** [comment]
https://github.com/temporalio/temporal/pull/4206
