### ISSUE TITLE
Enable persistenceGlobalMaxQPS (or maybe remove from dynamic config)

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/temporal#4185]
Looks as currently persistenceGlobalMaxQPS dynamic config is not used, see https://github.com/temporalio/temporal/blob/master/service/fx.go#L70-L79

If this cannot be enabled maybe we should comment the related dynamic config knobs for this or comment that they are not going to be used if set in dynamic config.

**Comment by yiminc** [comment]
Done https://github.com/temporalio/temporal/pull/4803
