### ISSUE TITLE
gocql fails to refresh node IPs after the Cassandra cluster/node restart

### ISSUE THREAD

**Issue by andrey-dubnik** [temporalio/temporal#4265]
## Expected Behavior

After the Cassandra cluster maintenance all/some nodes would get new IP addresses the expectation is for the client to re-connect seamlessly.

## Actual Behavior

Due to a [bug in the gocql](https://github.com/gocql/gocql/issues/1582) new IP addresses of Cassandra are not getting refreshed by the gocql and after the cluster maintenance each temporal service with a dependency on gocql have to be restarted explicitly.

Please consider updating to the latest gocql (1.4.0+) which does have the issue resolved (hopefully) as per the cross-reference of the mentioned issue with gocql PRs.

## Specifications

  - Version: (go.mod have v1.3.1)
  - Platform: x86

**Comment by mindaugasrukas** [comment]
Thanks for reporting! Looking into that.
