### ISSUE TITLE
Wrong handling of sophisticated CRON schedule

### ISSUE THREAD

**Issue by Dmitriusan** [temporalio/temporal#4288]
## Expected Behavior
We have a new workflow that should be effectively disabled during PROD deployment until the development is fully completed. To achieve that, we specify a CRON schedule `0 0 29 2 1`. The idea is:

The next execution date for this crontab entry would be `February 29th` of the `next leap year` which falls on a `Monday`. According to the calendar, that should happen in the year 2032 so we have plenty of time to complete the development. 
## Actual Behavior
In fact, for some reason Temporal CRON schedules that differently
![image](https://user-images.githubusercontent.com/1825803/236550676-17b3daa0-aa5f-4358-8f88-16649444a0fe.png)

I've tried checking the sleep period manually and it does not correspond to the CRON specified. Is there some integer overflow?
```
> date -d 'now + 6604 hours 52 minutes 13 seconds'
Mon 05 Feb 2024 02:13:18 AM EET
```

## Steps to Reproduce the Problem

  1. specify a CRON schedule `0 0 29 2 1`
  1. schedule some workflow
  1. take a look at expected date

## Specifications

  - Version: v1.9.0 web
  - Platform: Linux

**Comment by dnr** [comment]
Classic cron syntax has the "feature" than when both day-of-month and day-of-week are specified, then they're treated as "or" instead of "and". (The cron implementation in Schedules doesn't do this but the one for workflow CronSchedule does.)

In this case, why not just not start the workflow at all?

**Comment by yiminc** [comment]
Just for reference https://crontab.guru/#0_0_29_2_1 has same next schedule at 2024-02-05 00:00:00

**Comment by Dmitriusan** [comment]
@dnr thank you for the clarification! Very unobvious, but looks like "Works as desired". May be a good candidate for including some note at Temporal documentation

@yiminc , great service, thanks for pointing out to it!
