### ISSUE TITLE
is fastflow support rollback？

### ISSUE THREAD

**Issue by qiankunli** [temporalio/temporal#4358]
in my case, i want to use temporal to create some resources on a public cloud. like creating a cloud vm with public ip.

1. create a vm using cloud openapi
2. wait the status of vm is running(may cost some minutes)
3. create a public ip using cloud openapi
4. wait the status of public ip is available(may cost some seconds)
5. bind the public ip with vm
6. other steps

i want

1. if one step failed, workflow can free the created resources(vm,public ip etc) automaticlly. temporal is ok.
2. if I cancel the workflow(like run flow.cancel()), can temporal free the created resources(vm,public ip etc) ?

**Comment by yiminc** [comment]
Temporal will not do automatically rollback (or saga compenstaion), but your workflow would have to handle that explicitly. 
If one step failed, your workflow need to handle that failure and run rollback steps. 

Here is an example https://learn.temporal.io/tutorials/php/booking_saga/
Another one: https://github.com/temporalio/samples-java/blob/main/src/main/java/io/temporal/samples/hello/HelloSaga.java

If your workflow received cancellation, your workflow would need handle the cancellation and respond with rollback steps.
An example: https://legacy-documentation-sdks.temporal.io/go/how-to-request-cancellation-of-a-workflow-execution-in-go

**Comment by yiminc** [comment]
For further questions, please use temporal community [slack](https://temporalio.slack.com/join/shared_invite/zt-1vesb4c00-BGWxHXoIRBH6DidaUQmSQA#/shared-invite/email) or [forum](https://community.temporal.io/).
