### ISSUE TITLE
Does temporal support message/event queue?

### ISSUE THREAD

**Issue by enihcam** [temporalio/temporal#4360]
**Is your feature request related to a problem? Please describe.**
I'm thinking of adopting temporal in my current system for decoupling durable complex tasks from microservices, which should implement only atomic functionalities I assume. However, the microservices are cross clusters therefore behind their firewalls. And, Temporal only supports gRPC so I don't know how friendly it is to the firewalls.

**Describe the solution you'd like**
I need a firewall-friendly solution of orchestrating durable tasks. e.g. Maybe agents are needed to be deployed in each clusters/vnets communicating with the orchestrator as control plane. So any suggestions from temporal perspective?

**Describe alternatives you've considered**
DIY by using gocelery or machinery to implement the whole solution.

**Additional context**
Thanks.

**Comment by mfateev** [comment]
Temporal workers which are hosted inside each service only need an outbound gRPC connection to the Temporal service. So each service firewall should not be affected

**Comment by yiminc** [comment]
HTTP API support is also added to temporal frontend. https://github.com/temporalio/temporal/pull/4543
