### ISSUE TITLE
Persist and Modify Rate Limits Tied to Worker IDs in Temporal

### ISSUE THREAD

**Issue by zboralski** [temporalio/temporal#4361]
**Is your feature request related to a problem? Please describe.**
Yes, it involves managing rate limits using Temporal's `WorkerActivitiesPerSecond` parameter. As of now, this parameter resets when a worker restarts or migrates, causing problems with rate limiting strategies. It's especially tricky when third-party downstream rate limits need observing.

**Describe the solution you'd like**
Here are two changes that would help:

1. Allow the `WorkerActivitiesPerSecond` limit to stick around when a worker restarts or moves to a new machine. This way, the worker's rate limit settings don't get lost if it restarts or changes location.
2. Make it possible to change the `WorkerActivitiesPerSecond` limit after the worker is created. This flexibility would let the system adapt to new situations without the need for a new worker.

The state could be tied to the worker id for better management.

**Describe alternatives you've considered**
To work around this issue, there's an idea to use Gubernator, another rate limiting system. It means adding extra activities to check and register hits with Gubernator. But this adds complexity that could be avoided.

**Additional context**
This feature would simplify things for developers by offering better control over rate limiting within Temporal. It would be helpful not just in this scenario, but in others where there's a need for detailed and lasting control over worker activity rates.

**Comment by zboralski** [comment]
Upon reviewing the rate limiter's implementation (go sdk), I believe the concerns previously mentioned may not pose significant issues. It's worth noting that the rate limiter utilizes a burst value of one and doesn't employ the use of allow or reservation.

In the event that a worker is restarted only once during the replenishment period of the token, we might slightly exceed the limit by just one event. This might be more of an issue if the worker is restarted multiple times within that same interval.

However, if the worker is restarted after the token has already been replenished, this would not affect the rate limit at all.
It could be a problem if the worker is restarted many times during that interval.

A potential useful improvement could be to provide an option to skip the first event upon creating the limiter, by calling 'Wait'. 
This could be particularly helpful in situations where an activity bug may cause a worker to crash and restart multiple times. Implementing this option would guard the user against exceeding their downstream API quota due to repeated worker restarts.

**Comment by yiminc** [comment]
Look like it is not longer a big concern for you.
You might consider a workaround to put a sleep (over the duration of concern for one token) in worker's main method.
