### ISSUE TITLE
Child workflow is not retried if retryPolicy.maximumAttempts is not set

### ISSUE THREAD

**Issue by mfateev** [temporalio/temporal#437]
## Expected Behavior
Child workflow is retried on failures if retryPolicy is set.

## Actual Behavior
Child workflow fails without retry. It is retried if retryPolicy.maximumAttempts is set.

## Steps to Reproduce the Problem

  1. Create a child workflow that always returns an error with retryPolicy withy 0 maximumAttempts.
  1. Execute child from a parent
  1. Witness that the child is not retried.

## Specifications

  - Version: temporalio/auto-setup:0.23.1
  - Platform: mac

**Comment by samarabbas** [comment]
Can you try to reproduce with latest bits.  Close if it does not otherwise move to stabilization.

**Comment by mastermanu** [comment]
Behavior is confirmed:

	cwo := workflow.ChildWorkflowOptions{
		WorkflowID:               "sanity-" + pandemicType + "-" + workflow.Now(ctx).Format(time.RFC3339),
		WorkflowExecutionTimeout: time.Second * time.Duration(targetTimeInSeconds+10),
		RetryPolicy: &temporal.RetryPolicy{
			InitialInterval: time.Second * 1, <-- retries even if 0 if others are set
			MaximumAttempts: 0, <-- no retries if 0, but if I set it to 5, it retries 5 times.
			MaximumInterval: time.Second * 5, <-- retries even if 0 if others are set
		},
	}

Also no retries if MaximumAttempts is set and both InitialInterval and MaximumInterval is set to 0
