### ISSUE TITLE
Inconsistent datetime format for datetime search attribute

### ISSUE THREAD

**Issue by longquanzheng** [temporalio/temporal#4377]
## Expected Behavior
consistent datetime format should be returned in a string or datetime type 

## Actual Behavior
I see format in both `2023-04-27T22:52:33Z` and `2006-01-02T15:04:05-07:00` in different env. 

## Steps to Reproduce the Problem
Here is how I retrieve the SA via client SDK(descWF API)
https://github.com/indeedeng/iwf/blob/58f463e7593fcbf7806bd9014c04d0c5f7f34e21/service/api/temporal/client.go#LL164C46-L164C46

## Specifications

  - Version: TEMPORAL_VERSION=1.20.1 go.temporal.io/sdk v1.20.0
  - Platform: Golang SDK  + Temporal server in docker

## Others
I tried to workaround in https://github.com/indeedeng/iwf/issues/261 but realized that may not be a good idea

**Comment by rodrigozhou** [comment]
They are both in the same format RFC3339.

**Comment by longquanzheng** [comment]
> They are both in the same format RFC3339.

I see. Thanks for responding to it. Also found this SO post for this problem: https://stackoverflow.com/questions/40369287/what-pattern-should-be-used-to-parse-rfc-3339-datetime-strings-in-java

Though, I still feel like this is not a great experience to use

**Comment by rodrigozhou** [comment]
What are you calling as "inconsistent"? Being in different time zones?

Is it a system search attribute (eg: start time), or is it a custom search attribute?
For system, we convert to UTC for storage. For custom, we try to keep it with timezone as set by the user so it can be retrieved exactly as the user set.

**Comment by longquanzheng** [comment]
> What are you calling as "inconsistent"? Being in different time zones?
> 
> Is it a system search attribute (eg: start time), or is it a custom search attribute? For system, we convert to UTC for storage. For custom, we try to keep it with timezone as set by the user so it can be retrieved exactly as the user set.

Basically it’s a problem when I try to parse the string back to date time using a fixed format:
https://github.com/indeedeng/iwf-golang-sdk/blob/b2ed2e607dd4184bc01cd24507cbb55738fbd04b/iwf/persistence_impl.go#L196

There is probably a better way to do this . I will need to find out. If you know it, please share with me

**Comment by rodrigozhou** [comment]
Have you tried the `time Parse(time.RFC3339Nano, dt)`?

**Comment by rodrigozhou** [comment]
I'm closing this issue for now. Feel free to reopen if you still need help.
