### ISSUE TITLE
Server startup fail at concurrent map writes

### ISSUE THREAD

**Issue by longquanzheng** [temporalio/temporal#4434]
## Expected Behavior
shouldn't fail

## Actual Behavior
![Screenshot 2023-06-02 at 11 54 04 AM](https://github.com/temporalio/temporal/assets/4523955/c2947478-2d14-419d-a30b-e9aa1662a12e)

see full log here: https://gist.github.com/longquanzheng/1e1b8d00b39d0714b56978979d4d0f68
## Steps to Reproduce the Problem

This doesn't always happen. I only see it once when running docker-compose up, following instruction: https://github.com/indeedeng/iwf#using-docker-image--docker-compose

## Specifications

  - Version: 1.20.2
  - Platform: docker-compose file on Mac

**Comment by yiminc** [comment]
Dup of https://github.com/temporalio/temporal/issues/4000
