### ISSUE TITLE
standalone admin-tools fails to connect in kubernetes

### ISSUE THREAD

**Issue by lerminou** [temporalio/temporal#4467]
We use temporal in kubernetes for a while.
To update our temporal version, we run the admin-tools container to migrate the database.

We use a standalone container admin-tools

  => Use a simple pod admin-tools with this basic definition
  ```
      apiVersion: v1
      kind: Pod
      metadata:
        name: admin-tools
      spec:
        containers:
          - name: admin-tools
            image: temporalio/admin-tools:1.20.3
            imagePullPolicy: IfNotPresent
```

## Expected Behavior
the container fails to connect to cassandra if deployed in the same namespace as cassandra

## Actual Behavior
The container can connect with cassandra  if deployed in the same namespace

## Steps to Reproduce the Problem

  1. create the resource in the same namespace as cassandra and run the command to create the database for example
  ```
/etc/temporal $ temporal-cassandra-tool --endpoint cassandra.dev.svc -u nexus -pw xxxx create-Keyspace -k temporal --rf 3 -v
panic: error getting env CASSANDRA_PORT

goroutine 1 [running]:
go.temporal.io/server/environment.GetCassandraPort()
	/home/builder/temporal/environment/env.go:153 +0xa5
go.temporal.io/server/tools/cassandra.buildCLIOptions()
	/home/builder/temporal/tools/cassandra/main.go:70 +0x1a5
go.temporal.io/server/tools/cassandra.RunTool({0xc00003e1a0, 0xd, 0xd})
	/home/builder/temporal/tools/cassandra/main.go:40 +0x28
main.main()
	/home/builder/temporal/cmd/tools/cassandra/main.go:34 +0x2e
```
  
  2. run the command `printenv` in the container to show default env vars
```
/etc/temporal $ printenv
CASSANDRA_PORT_8080_TCP_PROTO=tcp
KUBERNETES_SERVICE_PORT=443
KUBERNETES_PORT=tcp://10.43.0.1:443
CASSANDRA_SERVICE_PORT=9042
CASSANDRA_PORT=tcp://10.43.109.12:9042
HOSTNAME=admin-toolsa
SHLVL=1
HOME=/home/temporal
CASSANDRA_PORT_9042_TCP=tcp://10.43.109.12:9042
CASSANDRA_PORT_8080_TCP=tcp://10.43.109.12:8080
CASSANDRA_SERVICE_PORT_METRICS=8080
CASSANDRA_SERVICE_PORT_CQL=9042
TERM=xterm
KUBERNETES_PORT_443_TCP_ADDR=10.43.0.1
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
KUBERNETES_PORT_443_TCP_PORT=443
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_SERVICE_PORT_HTTPS=443
KUBERNETES_PORT_443_TCP=tcp://10.43.0.1:443
KUBERNETES_SERVICE_HOST=10.43.0.1
PWD=/etc/temporal
CASSANDRA_PORT_9042_TCP_ADDR=10.43.109.12
CASSANDRA_SERVICE_HOST=10.43.109.12
CASSANDRA_PORT_8080_TCP_ADDR=10.43.109.12
CASSANDRA_PORT_9042_TCP_PORT=9042
CASSANDRA_PORT_9042_TCP_PROTO=tcp
CASSANDRA_PORT_8080_TCP_PORT=8080

```

=> it seems that the container can auto detect cassandra endpoint and some informations

  3. Do the same actions to deploy the container in another namespace
  ```
/etc/temporal $ temporal-cassandra-tool --endpoint cassandra.dev.svc -u nexus -pw xxxx create-Keyspace -k temporal --rf 3 -v
2023-06-09T07:40:23.057Z	INFO	Validating connection to cassandra cluster.	{"logging-call-at": "cqlclient.go:111"}
2023-06-09T07:40:23.967Z	INFO	Connection validation succeeded.	{"logging-call-at": "cqlclient.go:122"}
2023-06-09T07:40:23.967Z	INFO	Creating Keyspace temporal using SimpleStrategy with RF=3.	{"logging-call-at": "cqlclient.go:169"}
```
 check env vars
```
/etc/temporal $ printenv
KUBERNETES_SERVICE_PORT=443
KUBERNETES_PORT=tcp://10.43.0.1:443
HOSTNAME=admin-tools
SHLVL=1
HOME=/home/temporal
TERM=xterm
KUBERNETES_PORT_443_TCP_ADDR=10.43.0.1
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
KUBERNETES_PORT_443_TCP_PORT=443
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_SERVICE_PORT_HTTPS=443
KUBERNETES_PORT_443_TCP=tcp://10.43.0.1:443
KUBERNETES_SERVICE_HOST=10.43.0.1
PWD=/etc/temporal
/etc/temporal $
```

=> when env var `CASSANDRA_PORT` is not present, the connection is successfull.

## Specifications

  - Version: 1.20.3
  - Platform: Kubernetes

**Comment by yiminc** [comment]
The temporal-cassandra-tool expect CASSANDRA_PORT to be a valid integer port number (like 9042). In your case, the environment variable was set to something else (CASSANDRA_PORT=tcp://10.43.109.12:9042) that cause the tool to panic. This is expected behavior. If you want to avoid this panic, you can pass in port as argument by `--port`. 

When you run it in other namespace where there is no CASSANDRA_PORT, the tool would fallback to use default port which is 9042.

To make the tool work, you either pass in your port via command line argument, or you specify a CASSANDRA_PORT to a valid port number. If neighter are present, a default 9042 is used.
