### ISSUE TITLE
Support gRPC Reflection API

### ISSUE THREAD

**Issue by cvanderschuere** [temporalio/temporal#448]
**Is your feature request related to a problem? Please describe.**
Exploring APIs requires linking to the protobuf definitions. This makes using tools such as [grpcurl](https://github.com/fullstorydev/grpcurl) or [grpcui](https://github.com/fullstorydev/grpcui) more difficult

**Describe the solution you'd like**
Support [gRPC Reflection](https://pkg.go.dev/google.golang.org/grpc/reflection?tab=doc) for Frontend APIs.

**Additional context**

Unfortunately, this is not currently possible without a much more significant change of protobuf libraries. There is more context in this [blog post](https://jbrandhorst.com/post/gogoproto/), but the short is that without this change there will be errors similar to:
```
$ grpcui  --plaintext localhost:7233 
Failed to compute set of methods to expose: Symbol not found: adminservice.AdminService
```

**Comment by samarabbas** [comment]
@alexshtin can you look into this?

**Comment by alexshtin** [comment]
gRPC reflection will come automatically if we #38. It doesn't work with gogo implementation. The only APIs that supported are health check APIs (which served by google generated code).

**Comment by alexshtin** [comment]
Btw, https://github.com/ktr0731/evans is another great tool to explore gRPC services.

**Comment by alexshtin** [comment]
This was essentially enabled by #5032.

**Comment by alexshtin** [comment]
Can be used with `evans`:
```
echo '{"namespace":"temporal-system"}' | evans --host 127.0.0.1 --port 7233 --reflection cli call temporal.api.workflowservice.v1.WorkflowService.ListWorkflowExecutions
```
or
![image](https://github.com/temporalio/temporal/assets/2232524/711ee6ce-5d36-4b0e-86c1-664d7f8e323a)
