### ISSUE TITLE
cancel mutil activity by  single workflow

### ISSUE THREAD

**Issue by CarlosEssun** [temporalio/temporal#4507]
## Expected Behavior
Hope that the currently running Xworkflow can be canceled through CancelWorkflow or RequestCancelWorkflowExecution

## Actual Behavior
Define a DownloadWorkflow in which there are two activities DumpActivity and LoadActivity. When CancelWorkflow(ctx, req.WorkflowId, req.RunId) is used to cancel, the following activities will still be executed. Is there any way to cancel the currently running workflow task?

## Steps to Reproduce the Problem
`2023/06/16 10:19:29 Started Workflow Execution WorkflowID 02029f6f-d4bb-4eef-b94c-035222ee06f0 RunID c3ee77e9-27cc-44b2-8728-8ed4f42a0a9e
2023/06/16 10:19:29 INFO  cancel workflow started Namespace test TaskQueue test WorkerID 10041@essun.com@ WorkflowType CannelDumplingWorkflow WorkflowID 02029f6f-d4bb-4eef-b94c-035222ee06f0 RunID c3ee77e9-27cc-44b2-8728-8ed4f42a0a9e Attempt 1
2023/06/16 10:19:29 DEBUG ExecuteActivity Namespace test TaskQueue test WorkerID 10041@essun.com@ WorkflowType CannelDumplingWorkflow WorkflowID 02029f6f-d4bb-4eef-b94c-035222ee06f0 RunID c3ee77e9-27cc-44b2-8728-8ed4f42a0a9e Attempt 1 ActivityID 5 ActivityType DumperActivity

2023/06/16 10:20:11 DEBUG RequestCancelActivity Namespace test TaskQueue test WorkerID 10041@essun.com@ WorkflowType CannelDumplingWorkflow WorkflowID 02029f6f-d4bb-4eef-b94c-035222ee06f0 RunID c3ee77e9-27cc-44b2-8728-8ed4f42a0a9e Attempt 1 ActivityID 11
......
2023/06/16 10:20:39 INFO Namespace test TaskQueue test WorkerID 10041@essun.com@ WorkflowType CannelDumplingWorkflow WorkflowID 02029f6f-d4bb-4eef-b94c-035222ee06f0 RunID c3ee77e9-27cc-44b2-8728-8ed4f42a0a9e Attempt 1 
2023/06/16 10:20:39 DEBUG ExecuteActivity Namespace test TaskQueue test WorkerID 10041@essun.com@ WorkflowType CannelDumplingWorkflow WorkflowID 02029f6f-d4bb-4eef-b94c-035222ee06f0 RunID c3ee77e9-27cc-44b2-8728-8ed4f42a0a9e Attempt 1 ActivityID 22 ActivityType CleanMigrateActivity

`
## Specifications

  - Version:  go sdk 1.15.0 ;temporal 1.15.0
  - Platform: linux

**Comment by yiminc** [comment]
Cancel activity from within the workflow via the context that is used to start the activity. If the activity is already started, the activity needs to do heartbeat to be able to notice that it is cancelled.
See similar discussion here: https://community.temporal.io/t/problems-cancelling-a-running-activity-from-parent-workflow/2169

Please post this type of questions to community forum. Github is used for issue request or bug report. Thanks.
