### ISSUE TITLE
Metrics - allow "child_workflow_command" counter to be filtered by namespace

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/temporal#4628]
Currently child_workflow_command is incremented each time history service handler StartChildWorkflow command but its not filterable by namespace. 
Feature request is to have ability to filter it by ns.

**Comment by yiminc** [comment]
Currently, each command would emit a separate metric. We probably should change to emit one metric for all command and tag a command_type to that metric. Should also tag namespace to it.
