### ISSUE TITLE
docker/README.md and graphite support

### ISSUE THREAD

**Issue by mkjt2** [temporalio/temporal#466]
## Expected Behavior

Graphite metrics dashboard available across all docker-compose*.yml options, as described by README.md (localhost:8080/dashboard)

## Actual Behavior

Default docker-compose.yml (with Cassandra) does not run graphite at all.

## Steps to Reproduce the Problem

  1. cd docker
  1. docker-compose up
  1. try to open localhost:8080/dashboard in browser (fails).
  1. `docker ps` does not mention 8080 port mapping at all.

## Specifications

  - Version: master branch, commit b1d950280a9496a9fd20887aa9b3338ff88cab0e
  - Platform: not applicable

Note sure if README.md or the docker-compose files should be changed.

**Comment by cullywakelin** [comment]
Graphite is no longer a default component/dependency. The temporal/docker/README file has been updated to reflect this: https://github.com/temporalio/temporal/pull/548
