### ISSUE TITLE
Reason why i cant filter by both execution status and workflowType

### ISSUE THREAD

**Issue by kechkibet** [temporalio/temporal#4693]
Hi,
We have noticed that we cant be able to filter by both execution status and workflowtype, we are inquiring on why it is configured so. As per the test on converter_test.go line 62, `ExecutionStatus = "Running" AND WorkflowType = "xyz"`, is part of unsupported queries.
Kindly shed light on this so that it may guide us in the future.

Thanks.

**Comment by alexshtin** [comment]
I think you are using standard visibility backed by Cassandra or SQL. It supports only limited filtering functionality, and, by the way, gonna be deprecated soon. To use different filter combinations you need to enable advanced visibility. It is supported by Elasticsearch or SQL. You can read more here: https://docs.temporal.io/visibility.
