### ISSUE TITLE
ChildWorkflows not being retried with MySQL persistence

### ISSUE THREAD

**Issue by mfateev** [temporalio/temporal#470]
https://github.com/uber/cadence/issues/3351

**Comment by samarabbas** [comment]
Need to verify if this happens with Temporal.

**Comment by mastermanu** [comment]
This does not reproduce on the latest temporal server bits:

Workflow History:

   5  StartChildWorkflowExecutionInitiated  {Namespace:default,                                                                                                       
                                            WorkflowId:sanity-standard-2020-07-31T18:48:05Z,                                                                          
                                            WorkflowType:{Name:bench-driver},                                                                                         
                                            TaskQueue:{Name:temporal-bench,                                                                                           
                                            Kind:Normal}, Input:[{Concurrency:2 Count:2                                                                               
                                            Parameters:map[Basic:map[SequenceCount:0]                                                                                 
                                            ConfigDriven:map[BuiltInType: TotalInstances:0]                                                                           
                                            Pandemic:map[Depth:2 Fanout:7 Type:standard]                                                                              
                                            Reactor:map[SignalsPerRun:0 SignalsTotal:0                                                                                
                                            TotalExecutions:0] Type:pandemic]}],                                                                                      
                                            WorkflowExecutionTimeout:40s,                                                                                             
                                            WorkflowRunTimeout:40s, WorkflowTaskTimeout:5s,                                                                           
                                            ParentClosePolicy:Terminate,                                                                                              
                                            WorkflowTaskCompletedEventId:4,                                                                                           
                                            WorkflowIdReusePolicy:AllowDuplicate,                                                                                     
                                            **RetryPolicy:{InitialInterval:1s,                                                                                          
                                            BackoffCoefficient:2,                                                                                                     
                                            MaximumInterval:5s, MaximumAttempts:5,                                                                                    
                                            NonRetryableErrorTypes:[len=0]},**                                                                                          
                                            Header:{Fields:map{}}}                                                                                                    
   6  ChildWorkflowExecutionStarted         {Namespace:default, InitiatedEventId:5,                                                                                   
                                            WorkflowExecution:{WorkflowId:sanity-standard-2020-07-31T18:48:05Z,                                                       
                                            RunId:7a7ecee7-b617-41f4-96fa-3ee5a3de9351},                                                                              
                                            WorkflowType:{Name:bench-driver}, Header:{Fields:map{}}}                                                                  
   7  WorkflowTaskScheduled                 {TaskQueue:{Name:temporal-dev:8c482def-d658-4a35-8216-d2ebc259106a,                                                       
                                            Kind:Sticky}, StartToCloseTimeout:5s, Attempt:1}                                                                          
   8  WorkflowTaskStarted                   {ScheduledEventId:7,                                                                                                      
                                            Identity:617231@temporal-dev@,                                                                                            
                                            RequestId:9ef55904-af4e-4b43-9e22-878fb70f3bfe}                                                                           
   9  WorkflowTaskCompleted                 {ScheduledEventId:7, StartedEventId:8,                                                                                    
                                            Identity:617231@temporal-dev@,                                                                                            
                                            BinaryChecksum:94f4b578a0ec8b544ae3b099702269cf}                                                                          
  10  ChildWorkflowExecutionFailed          **{Failure:{Message:simulated failure to exercise retry, Source:GoSDK,                                                      
                                            FailureInfo:&Failure_ApplicationFailureInfo{ApplicationFailureInfo:&ApplicationFailureInfo{Type:errorString,NonRetryable  
                                            :false,Detai ls:nil,},}}, Namespace:default, WorkflowExecution:{WorkflowId:sanity-standard-2020-07-31T18:48:05Z,          
                                            RunId:ea886b6d-5a94-4faa-a0e1-c3f728e3afa4}, WorkflowType:{Name:bench-driver}, InitiatedEventId:5, StartedEventId:6,      
                                            RetryState:MaximumAttemptsReached}** 

I see the Child Workflow print its start log 5 times before I finally get the following error:

2020-07-31T11:53:04.592-0700	WARN	sanity/workflow.go:75	workflow failed	{"Namespace": "default", "TaskQueue": "temporal-bench", "WorkerID": "617657@temporal-dev@", "WorkflowType": "sanity", "WorkflowID": "1", "RunID": "4f9d55b3-a14d-4eff-b3fc-cca4f05a2c16", "scenarioName": "pandemicStandard", "Error": "child workflow execution error (workflowID: sanity-standard-2020-07-31T18:52:27Z, runID: fe22384c-b43a-42ab-bbc3-1e7f29cc55c5, initiatedEventID: 5, startedEventID: 6, workflowType: bench-driver): simulated failure to exercise retry"}
github.com/temporalio/temporal-bench/common.(*ZapAdapter).Warn
	/home/manu/work/temporal-bench/common/zap_adapter.go:70
go.temporal.io/sdk/internal/log.(*ReplayLogger).Warn
	/home/manu/go/pkg/mod/go.temporal.io/sdk@v0.27.1-0.20200731022914-4dfdb125c775/internal/log/replay_logger.go:68
github.com/temporalio/temporal-bench/workflows/sanity.executeScenario
	/home/manu/work/temporal-bench/workflows/sanity/workflow.go:103
github.com/temporalio/temporal-bench/workflows/sanity.SanityWorkflow
	/home/manu/work/temporal-bench/workflows/sanity/workflow.go:75
reflect.Value.call
	/usr/local/go/src/reflect/value.go:460
reflect.Value.Call
	/usr/local/go/src/reflect/value.go:321
go.temporal.io/sdk/internal.(*workflowEnvironmentInterceptor).ExecuteWorkflow
	/home/manu/go/pkg/mod/go.temporal.io/sdk@v0.27.1-0.20200731022914-4dfdb125c775/internal/workflow.go:370
go.temporal.io/sdk/internal.(*workflowExecutor).Execute
	/home/manu/go/pkg/mod/go.temporal.io/sdk@v0.27.1-0.20200731022914-4dfdb125c775/internal/internal_worker.go:759
go.temporal.io/sdk/internal.(*syncWorkflowDefinition).Execute.func1
	/home/manu/go/pkg/mod/go.temporal.io/sdk@v0.27.1-0.20200731022914-4dfdb125c775/internal/internal_workflow.go:491
go.temporal.io/sdk/internal.(*dispatcherImpl).NewCoroutine.func1
	/home/manu/go/pkg/mod/go.temporal.io/sdk@v0.27.1-0.20200731022914-4dfdb125c775/internal/internal_workflow.go:903
