### ISSUE TITLE
SQLite (SQL generally?) visibility problems with custom text fields

### ISSUE THREAD

**Issue by Sushisource** [temporalio/temporal#4729]
## Expected Behavior
Searching by a custom text field should work, as it does using the ES backend.

## Actual Behavior
After upserting the custom attribute from a workflow with a value like `configdriven-stresstest`, subsequent queries fail with errors like the following:

```
"level":"error","ts":"2023-08-03T16:49:59.640-0700","msg":"service failures","operation":"CountWorkflowExecutions","wf-namespace":"default","error":"CountWorkflowExecutions operation failed. Query failed: SQL logic error: no such column: stresstest (1)
```
or
```
error":"ListWorkflowExecutions operation failed. Select failed: SQL logic error: no such column: stresstest (1)",
```

My guess is there is some kind of escaping or parsing issue with dashes going on here.

## Steps to Reproduce the Problem

  1. `temporal operator search-attribute create --name CustomStringField --type Text`
  1. Upsert the value from a workflow with something with dashes in it like `foo-bar`
  1. Attempt to query/list for WFs matching that value

## Specifications

  - Version: 1.21.4
  - Platform: Temporal CLI using SQLite backend

**Comment by rodrigozhou** [comment]
The issue only happens in SQLite. PR https://github.com/temporalio/temporal/pull/4755 fixes it.
