### ISSUE TITLE
Unable to build Temporal on 32-bit platforms 

### ISSUE THREAD

**Issue by heavycrystal** [temporalio/temporal#4736]
## Expected Behavior
Unmodified build to succeed on any platform that Golang supports without any issues.

## Actual Behavior
Compilation fails on 32-bit systems with the following error:

```
common/persistence/cassandra/errors.go:48:25: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in variable declaration (overflows)
```

This is because the line in question specifies a variable without any type, which defaults to `int` [which is 4 bytes wide on 32-bit platforms] and thus cannot hold the value. This is a [well-known issue](https://stackoverflow.com/questions/29309922/go-math-maxint64-and-type-inference-error). Assignments like this might be present elsewhere, this is just the place where the Go compiler stopped.

## Steps to Reproduce the Problem

  1. Clone the repo normally 
  1. Run `make`

## Specifications

  - Version: HEAD 
  - Platform: Raspberry Pi Zero W [ARMv6 architecture]

**Comment by yiminc** [comment]
No plan to support 32-bit platform at the moment.
