### ISSUE TITLE
Java 1.20.0  Schedule State

### ISSUE THREAD

**Issue by Morain-Miao** [temporalio/temporal#4737]
Now, Schedule only has Running and Pause.
Business scenario:
we need have only run only once.  How do i end schedule?
If use delete(), I'll lose my record.

what should I do？

**Comment by dnr** [comment]
In server 1.22 (next release), a schedule with no more remaining actions will automatically delete itself after 1 week. You can also delete it yourself before that time. After it's deleted, either automatically or manually, you will lose the record of the schedule, yes. Do you need to keep it longer than that? Note that the workflow(s) started by the schedule will be subject to retention, archival, etc.

**Comment by Morain-Miao** [comment]
yeah,   i  need to keep record longer time.  i  want to more schedule state ,  example:  completed,  terminated...  just like WorkFlow state.

**Comment by yiminc** [comment]
For run only once, you can use StartDelay to start your workflow with desired delay time. It is available for Java/Go for now. Support to other languages will be added soon. https://github.com/temporalio/features/issues/338
