### ISSUE TITLE
ringpop deprecation discussion

### ISSUE THREAD

**Issue by decibelcooper** [temporalio/temporal#4748]
# Context
I have a small hope that there will one day be support for an active-active Temporal configuration across datacenters, even though I have seen statements from Maxim such as, “Temporal doesn’t support active-active. A namespace is active in one cluster at a time.”

I have experience building and running active-active applications on top of Cassandra, and I believe that there is the possibility of Temporal growing to support such a configuration with the right underlying DB, consistency tuning, and sharding strategy.

# Question
As part of my effort to understand the momentum vector of Temporal as an open-source project, I would like to know if anyone can enlighten me about the deprecation of ringpop. I see that membership is pretty nicely abstracted now, so I wonder if there is a long-term strategy for replacing ringpop?

**Comment by yiminc** [comment]
Yes, we do want to replace ringpop with a well maintained library, but this is currently not a priority.

**Comment by decibelcooper** [comment]
Thanks, that is helpful for understanding where Temporal is headed.  I'll go ahead and close this issue.

**Comment by longquanzheng** [comment]
Any thoughts on what could be the potential replacement? @yiminc 

Also a similar issue in Cadence: https://github.com/uber/cadence/issues/2471

AFAIK, I don't see any good replacement in OSS today. Even serf is missing a lot of features compared to Ringpop for the use case of Cadence/Temporal
