### ISSUE TITLE
Each activity heartbeats results in two state transitions

### ISSUE THREAD

**Issue by mjameswh** [temporalio/temporal#4781]
## Description

At the moment, each heartbeat will incur 2 state transitions. One state transition happen when the `RecordActivityHeartbeat` API is called. Another state transition when the previous heartbeat timeout happens and it would create a new heartbeat timeout timer.

It seems like it might be possible to do optimize this, by creating the new heartbeat timeout timer when `RecordActivityHeartbeat` API is called, so when the previous heartbeat timeout timer fires, it would be a no-op, avoiding the second state transition.

**Comment by yiminc** [comment]
After discussion, this is expected behavior. Trying to optimize it would result in many edge cases that may perform worse. 
So will not change it for now.
