### ISSUE TITLE
temporal-system:read role should have access to ListSearchAttributes RO API (when using default authorizer)

### ISSUE THREAD

**Issue by ddavidyuk** [temporalio/temporal#4783]
## Expected Behavior
When using Temporal's default JWT authorizer, users with `temporal-system:read` permission should have access to `temporal.api.operatorservice.v1.OperatorService/ListSearchAttributes` API

https://github.com/temporalio/temporal/blob/release/v1.21.x/common/authorization/frontend_api.go#L50

## Actual Behavior
Users with `temporal-system:read` permission do NOT have access to the `ListSearchAttributes` API. This can be confirmed via CLI (`temporal operator search-attribute list`) or just by opening Temporal UI.
In case of CLI we get `Request unauthorized` error, when opening Temporal UI we get redirected back to the login screen after authentication because of the 403 Forbidden error to the `/search-attributes` endpoint

## Steps to Reproduce the Problem

  1. Deploy Temporal with default authorizer
  2. Configure an Oauth2 client in your auth provider to add `permissions: [ "temporal-system:read" ]` claim to the access token.
  3. Request to list search attributes via `tctl` or `temporal cli` with your access token or open Temporal UI.

## Specifications

  - Version: Temporal v1.21.4

**Comment by yiminc** [comment]
related https://github.com/temporalio/temporal/issues/4654

**Comment by ddavidyuk** [comment]
Hi everyone! Any chance this can be released in 1.21.6? This blocks our upgrade to 1.21.x because users with temporal-system:read role cannot use Temporal UI (after logging in they are immediately redirected back to the login screen because of the 403 error for the ListSearchAttributes API).

**Comment by dnr** [comment]
Closed by #4794. Not sure about backporting yet.
