### ISSUE TITLE
Describe Workflow (& other RPCs) with an empty Run ID problems post-run-deletion

### ISSUE THREAD

**Issue by Sushisource** [temporalio/temporal#4792]
## Expected Behavior
If you call describe workflow, or get history, etc passing an empty run ID - you should always get results as long as any workflow with the provided workflow ID exists.

## Actual Behavior
If you have deleted a run which was continued / reset from a previous run with the same ID, subsequent calls of the kind described above will fail with not found.

## Steps to Reproduce the Problem

  1. Start a workflow and have it continue-as-new, or reset it
  1. Complete the new instance
  1. Delete it
  1. Make one of the relevant RPCs with an empty run ID

## Specifications

  - Version: 1.21
  - Platform: Linux / sqlite

**Comment by yiminc** [comment]
The server would fetch current run-id if the run-id is not provided as input. Delete current run does not make previous run as current run.
