### ISSUE TITLE
Improve retry with saved token

### ISSUE THREAD

**Issue by abtris** [temporalio/temporal#4799]
**Is your feature request related to a problem? Please describe.**

I need call in activity Azure Go SDK and here is part of logic. You get token for possible retry problems but I need own retry logic that I can't use retry with token in Temporal.

```
if token == nil {
	poller, err := clientFactory.NewApplicationsClient().BeginDelete(ctx, AzureDataResourceGroupName, appName, nil)
	if err != nil {
		return result, err
	}
	// save token (use for retry)
	token, _ := poller.ResumeToken()
	
	} else {
	poller, err = clientFactory.NewApplicationsClient().BeginDelete(ctx, AzureDataResourceGroupName, appName, &armmanagedapplications.ApplicationsClientBeginDeleteOptions{
		ResumeToken: token,
	})
}
```

**Describe the solution you'd like**

My idea, if we have possible save token for retry and can use if activity is retried that will be great.

**Describe alternatives you've considered**

No idea, I just write some my implementation that logic inside activity using my own db.

**Additional context**

Related discussion was in https://temporalio.slack.com/archives/CTDTU3J4T/p1692802525517009

**Comment by yiminc** [comment]
i think you could heartbeat to record the token, and retrieve it from later retry attempt.

**Comment by abtris** [comment]
@yiminc Heartbeat details are not guaranteed to be recorded in Slack from @mfateev

**Comment by yiminc** [comment]
Your process could be killed after you fetched token but before you saved it to your own db. So there is no way to 100% guarantee that. From what you describe, your application will continue to work (by fetch a new token) if that happens. So I think heartbeat could be a good solution for you. 

Other approach is to break your activities into 2 activities, first one fetch the token, and second one take token as input.
