### ISSUE TITLE
Starting abandoned child after parent closes

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/temporal#4812]
Attempting to start a child workflow right before parent closes (for example on history event count limit) 
creates the child workflow execution but this execution never receives the first workflow task (stays open). 

This child workflow stays running and claims its child workflow id (cannot be used by other child workflows) as well as
needs to be manually terminated.

**Comment by yiminc** [comment]
dup of https://github.com/temporalio/temporal/issues/2829
