### ISSUE TITLE
Retroactively make namespace global

### ISSUE THREAD

**Issue by arlyon** [temporalio/temporal#4835]
**Is your feature request related to a problem? Please describe.**

I have coded myself into a ticking-timebomb of a corner. I created a cluster for a hobby project that ended up getting far more use than intended and didn't have a great understanding when creating the cluster of the implications of `numHistoryShards` (which is set to 1). I want to resolve this by replicating to a new cluster with 1024 shards, failing over to it, and shutting off the old one, but have hit an insurmountable dead-end. I did not specify the 'global' flag when creating the namespace and there is no way to change that, so I can't enable replication, and can't change the number of history shards, and the workflows running (long-life on the order of months) are marooned. Since there is a single shard, most queries are cache misses leading to quite awful latency for certain routines (specifically, performing some query for a sufficiently large subset of workflows).

I could route new workflows to a new parallel cluster at the application level but I really don't want to. This is essentially a hobby running in my spare time and I don't want to deal with the additional complexity involved.

**Describe the solution you'd like**

This is a hybrid request; firstly this situation could be avoided altogether if the history shards could be scaled up as needed. Secondly, this situation could be remedied if I was able to mark namespaces as eligible for replication _after_ they are created. Alternatively, an option I investigated was somehow import events from one namespace / cluster to another, and do a full stop-the-world dump and import, but it seems this is not supported _either_.

**Additional context**

These foot-guns are very easy to trigger and very hard to undo.

**Comment by arlyon** [comment]
A question I have is what is the implication of taking down the cluster and starting it up against the same persistence with a different shard count? Is the state in the db dependent on the number of shards in some way?

**Comment by arlyon** [comment]
I am currently investigating manually calculating new shard IDs / hashes and updating the underlying persistence myself as if we had that many shard from the start

**Comment by arlyon** [comment]
Seems like the flag I am looking for is `  --promote-global`. The next hurdle is trying to add a second cluster to the namespace which seems to be ignored altogether.

**Comment by yiminc** [comment]
Yes, you should be able to promote a local namespace to a global one with that --promote-global flag https://docs.temporal.io/cli/cmd-options#promote-global
