### ISSUE TITLE
How can I scalable independently services such as fronted services?

### ISSUE THREAD

**Issue by imporoutco586** [temporalio/temporal#4836]
I see the docus, in the concepts of clusters.  It says that "a real-life production deployment can have 5 Frontend, 15 History, 17 Matching, and 3 Worker Services per cluster."   But I don't see the specific operation steps.   If I install Temporal CLI using cURL in my self-host, where can I scalable the services, in which config docus(I can't find some) or in the other way?   I hope someone can teach me that.

**Comment by yiminc** [comment]
Temporal CLI runs all 4 server roles in one process. Its goal is simplicity for developer experience. 
For production setup, you want to run different server roles separately and they can be scaled differently based on needs.

**Comment by imporoutco586** [comment]
Thanks for your explanation!  Where can I  find the way to scale different servers, I mean, in which config, or if there are some docus that can teach me do it?

> Temporal CLI runs all 4 server roles in one process. Its goal is simplicity for developer experience. For production setup, you want to run different server roles separately and they can be scaled differently based on needs.

**Comment by yiminc** [comment]
@imporoutco586 you may want to take a look at this: https://github.com/temporalio/helm-charts#readme

**Comment by yiminc** [comment]
For further questions, please use community forum at https://community.temporal.io/
