### ISSUE TITLE
Building on FreeBSD: Findings

### ISSUE THREAD

**Issue by ehaupt** [temporalio/temporal#4842]
I am aware that FreeBSD is not officially supported to run temporal. Nevertheless, I was trying to build the latest version on FreeBSD 14.0-ALPHA4 amd64. Here is how far I got:

Install dependencies:
```
pkg install -y gmake go120 git
```

Get the repository:
```
git clone --recurse-submodules https://github.com/temporalio/temporal.git
```

Try to build it with the provided `GNU-Makefile`:
```
cd temporal
ln -s /usr/local/bin/go120 /usr/local/bin/go
gmake
```

Output:
```
e[1;36mInstall/update goimports...e[0m
e[1;36mInstall/update linters...e[0m
e[1;36mInstall/update mockgen tool...e[0m
e[1;36mInstall/update proto plugins...e[0m
e[1;36mInstall/update proto linters...e[0m
e[1;36mBuild temporal-server with CGO_ENABLED=0 for freebsd/amd64...e[0m
CGO_ENABLED=0 go build -o temporal-server ./cmd/server
# github.com/temporalio/tchannel-go
../go/pkg/mod/github.com/temporalio/tchannel-go@v1.22.1-0.20220818200552-1be8d8cffa5b/sockio_unix.go:42:33: undefined: getSendQueueLen
gmake: *** [Makefile:212: temporal-server] Error 1
```

It would be awesome if someone could have a look. Maybe it's easy to fix. If you need a VM, [this](https://app.vagrantup.com/freebsd/boxes/FreeBSD-13.2-RELEASE) vagrant box would suffice.

**Comment by ehaupt** [comment]
Related: https://github.com/temporalio/temporal/issues/2703

**Comment by yiminc** [comment]
This is the same as the linked issue, going to close this one. ;P
