### ISSUE TITLE
Build a new signalOrStart API to replace the signalWithStart API

### ISSUE THREAD

**Issue by longquanzheng** [temporalio/temporal#4885]
**Is your feature request related to a problem? Please describe.**
* The `signalWithStart` is confusing to understand the word `with` which means a lot 
* Sometimes people don't really need an additional signal when starting it
* Even they need it, it can be included into the start parameter anyway

More importantly, users don't have to deal with the fact that signal method can be invoked before workflow method...Although, this could still happen due to reset. See post: https://medium.com/@qlong/gotchas-about-signalwithstart-in-cadence-temporal-c3783fe1cc2e 

**Describe the solution you'd like**
This should be really easy to build based on the existing signalWithStart API. 

**Describe alternatives you've considered**
NA

**Additional context**
Some discussion in Slack: https://indeed-pte.slack.com/archives/C02E8TQA01G/p1695229310008899

**Comment by yiminc** [comment]
Technically, it is Signal-Or-StartAndSignal... 
At this point, adding more API to do the same probably just add more confusion and no way to deprecate existing one.
