### ISSUE TITLE
Add reason and details to RequestCancelWorkflowExecutionRequest

### ISSUE THREAD

**Issue by alexshtin** [temporalio/temporal#491]
[TerminateWorkflowExecutionRequest](https://github.com/temporalio/temporal-proto/blob/a404bd24bd395a026e19b2dcc48832cedd06fa44/temporal/workflowservice/v1/request_response.proto#L394) has `details` and `reason` fields but [RequestCancelWorkflowExecutionRequest](https://github.com/temporalio/temporal-proto/blob/a404bd24bd395a026e19b2dcc48832cedd06fa44/temporal/workflowservice/v1/request_response.proto#L330) doesn't. To keep parity these fields needs to be added and supported by CLI (at least `reason`).

**Comment by yiminc** [comment]
Reason is available: https://github.com/temporalio/api/blob/f4f5bd81e2d34770f9bf3948c1697ede3acbdc02/temporal/api/workflowservice/v1/request_response.proto#L573
