### ISSUE TITLE
TestIntegrationSuite/TestWorkflowTerminationSignalBeforeTransientDecisionStarted is flaky

### ISSUE THREAD

**Issue by mastermanu** [temporalio/temporal#496]
## Expected Behavior
Test should pass reliably within a few seconds.

## Actual Behavior
Test failed after timing out for a minute.

## Steps to Reproduce the Problem

  1. KiteServer integration test build (1414). Repro is difficult, but will attach logs:
[temporal-server_build_1414_golang-integration-test-with-cassandra.log](https://github.com/temporalio/temporal/files/4866136/temporal-server_build_1414_golang-integration-test-with-cassandra.log)

## Specifications

  - Version:
  - Platform:

**Comment by samarabbas** [comment]
TestWorkflowTerminationSignalBeforeTransientWorkflowTaskStarted is passing consistently.
