### ISSUE TITLE
TestIntegrationSuite/TestContinueAsNewWorkflow_Timeout is flaky

### ISSUE THREAD

**Issue by mastermanu** [temporalio/temporal#497]
## Expected Behavior
Test failed in 5 seconds

## Actual Behavior
Test passes within 5 minutes.

## Steps to Reproduce the Problem
Attaching KiteServer logs for more information here:
[temporal-server_build_1414_golang-integration-test-with-mysql.log](https://github.com/temporalio/temporal/files/4866157/temporal-server_build_1414_golang-integration-test-with-mysql.log)

## Specifications

  - Version:
  - Platform:

**Comment by alexshtin** [comment]
And it also takes 5 mins.
