### ISSUE TITLE
Postgres connection pooling not working

### ISSUE THREAD

**Issue by Hades32** [temporalio/temporal#4975]
## Expected Behavior
Connections rarely getting opened

## Actual Behavior
50% of all CPU load (4 cores) just from opening new connections

![image](https://github.com/temporalio/temporal/assets/167847/0b1cc327-1d8c-47a7-921c-678fcd14ffd9)

## Steps to Reproduce the Problem

  1. cluster with 2k shards (I assume that's the culprit)
  1. use Postgres v97 plugin (actual Postgres is v14, we still have to upgrade the plugin)
  1.

## Specifications

  - Version: v1.20
  - Platform: Linux, AWS, EKS

**Comment by Hades32** [comment]
Looking through the code I see that Temporal tries to do its own connection pooling, but I didn't figure out if that's on the shard level or the node level.

Why not use a well-established connection pooling library like `pgx` and have one pool per node per type of connection (history, visibility, etc)?

**Comment by rodrigozhou** [comment]
@Hades32 `pgx` support was added recently in https://github.com/temporalio/temporal/pull/4913. Give it a try. You'll need to build Temporal from source though (not in a release yet), and you'll have to change the plugin name to `postgres_pgx` or `postgres12_pgx`.

**Comment by tdeebswihart** [comment]
@rodrigozhou our pgx implementation doesn't make use of pgx's connection pooling

**Comment by tdeebswihart** [comment]
> @Hades32 `pgx` support was added recently in #4913. Give it a try. You'll need to build Temporal from source though (not in a release yet), and you'll have to change the plugin name to `postgres_pgx` or `postgres12_pgx`.

Unfortunately we don't use pgx's conn pooling

**Comment by Hades32** [comment]
Are there plans to change that?

**Comment by tdeebswihart** [comment]
There are no plans that I'm aware of to use pgx's connection pool. We'd definitely fix our own before that

**Comment by Hades32** [comment]
There is a related issue that TLS certs are not re-used and thus crazy load is put on the system in terms of CPU for GC 
<img width="1175" alt="image" src="https://github.com/temporalio/temporal/assets/167847/8ac66219-663e-4484-80a2-dc2be17e00aa">

@tdeebswihart is that something that could be fixed independently?

**Comment by Hades32** [comment]
@tdeebswihart  haha, sure, I didn't want you to bother with analyzing the whole thing. AFAICT the main issue is still the connections not being re-used and as a side-effect, the cert being re-created all the time.
I'll still attach them for your convenience :)
[pprof.temporal-server.alloc_objects.alloc_space.inuse_objects.inuse_space.005.pb.gz](https://github.com/temporalio/temporal/files/13478313/pprof.temporal-server.alloc_objects.alloc_space.inuse_objects.inuse_space.005.pb.gz)
[pprof.temporal-server.alloc_objects.alloc_space.inuse_objects.inuse_space.004.pb.gz](https://github.com/temporalio/temporal/files/13478315/pprof.temporal-server.alloc_objects.alloc_space.inuse_objects.inuse_space.004.pb.gz)
[pprof.temporal-server.samples.cpu.003.pb.gz](https://github.com/temporalio/temporal/files/13478316/pprof.temporal-server.samples.cpu.003.pb.gz)

**Comment by tdeebswihart** [comment]
> So, this bug affects all database backends? Is there an issue for tracking the fix for your own connection pooling? I'm surprised you even have custom one

To clarify: we use sqlx's connection pooling, we haven't built our own.

**Comment by tdeebswihart** [comment]
What have you set the `persistence.datastores.*.sql.maxConns` and `persistence.datastores.*.sql.maxIdleConns` configuration values to? If unspecified we'll fall back to [sqlx's defaults](http://jmoiron.github.io/sqlx/) (look for "The Connection Pool") which are:
- Maximum of 2 idle conns
- Unbounded connection pool size (maxConns = 0)

I see a lot of calls to `pq.DialOpen` which screams "you should set idle conns higher" to me

**Comment by Hades32** [comment]
ohhh, that's some _very_ low default. Yes, we didn't have that one configured and adding it seems to have basically removed connection handling from CPU and memory profiles.
Thanks!

Will close this, as the main issue is solved, and the constant TLS cert re-loading is negligible with proper pooling

**Comment by tdeebswihart** [comment]
> ohhh, that's some _very_ low default. Yes, we didn't have that one configured and adding it seems to have basically removed connection handling from CPU and memory profiles. Thanks!
> 
> Will close this, as the main issue is solved, and the constant TLS cert re-loading is negligible with proper pooling

Excellent, I’m glad that solved your problem!
