### ISSUE TITLE
Update otel library

### ISSUE THREAD

**Issue by cretz** [temporalio/temporal#4996]
**Describe the solution you'd like**

Currently `go.opentelemetry.io/otel` is at `v1.16.0` but `v1.19.0` is latest and they made backwards incompatible changes to dependent libraries within. Upgrade needed for others that want to upgrade otel and depend on server as a library.

**Comment by adamjreed** [comment]
Hi, when should we expect to see this included in a release? Looks like it was merged about 3 weeks ago but wasn't included in the `v1.22.2` release yesterday. We'd like to upgrade to the newest version of the [buf](https://github.com/bufbuild/buf) package, but it's [using](https://github.com/bufbuild/buf/blob/v1.28.0/go.mod#L30) `v1.19.0` of the otel library referenced here and is causing dependency conflicts in our Go services. Thanks!

**Comment by kevink1103** [comment]
+1 for @adamjreed , waiting for otel upgrade being included in the next release!
@stephanos

**Comment by afifurrohman-id** [comment]
does this impact current behaviour of **temporal not export trace** to jaeger?

configure env:
```sh
OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://jaeger-host:4317"
```
should export trace to jaeger, because current jager version already **support OTLP protocol** directly.
