### ISSUE TITLE
Support Accepted stage on UpdateWorkflowExecution

### ISSUE THREAD

**Issue by yiminc** [temporalio/temporal#5018]
**Is your feature request related to a problem? Please describe.**
Currently, you can only synchronously wait on update result when calling UpdateWorkflowExecution.
There are many cases where you want the update to start long running async operations and you don't want to return from UpdateWorkflowExecution as soon as update is accepted.

**Comment by dandavison** [comment]
This was implemented in https://github.com/temporalio/temporal/pull/4309
