### ISSUE TITLE
CLI workflow run command can't process --input param with multiple args

### ISSUE THREAD

**Issue by feedmeapples** [temporalio/temporal#502]
## Expected Behavior
CLI should be able to start a workflow with --input param containing multiple args
See https://docs.temporal.io/docs/learn-cli#start-workflow

## Actual Behavior
`processJSONInput` throws an error when it tries to `Unmarshal` the input. Input param is not a correct json and has to be pre-processed to support the expected behavior.

## Steps to Reproduce the Problem

  1. Execute 
``` bash
./tctl workflow start --tq helloWorldGroup --wt main.WorkflowWith3Args --et 60 -i '"your_input_string" 123 {"Name":"my-string", "Age":12345}'
```
The output will contain an error message `invalid character '1' after top-level value`

## Specifications

  - Version: 0.26.0
  - Platform: Temporal on WSL2/Ubuntu go1.14.4 linux/amd64

**Comment by alexshtin** [comment]
Yes, last time I made a quick fix to make it work with one parameter, but proper fix needs to be made.
