### ISSUE TITLE
Allow authentication with IRSA on archival with AWS S3 

### ISSUE THREAD

**Issue by denniskniep** [temporalio/temporal#5051]
**Is your feature request related to a problem? Please describe.**
I´m running temporal with the HelmChart in a K8s EKS Cluster. And configured archival with S3.
I can´t get [IRSA](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) work. Maybe it´s not supported yet?

The temporal pods are getting automatically following env vars:
```
AWS_DEFAULT_REGION
AWS_REGION
AWS_ROLE_ARN 
AWS_STS_REGIONAL_ENDPOINTS 
AWS_WEB_IDENTITY_TOKEN_FILE 
```

Furthermore the currently used [Go SDK is supported](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.html), right?

If I update my namespace to use archival 
` temporal operator namespace update --visibility-archival-state enabled --history-archival-state enabled <namespace>`

I get following error:
```
namespace update failed: Forbidden: Forbidden  status code: 403,
```

Stacktrace is not helpful due to following issue: https://github.com/temporalio/temporal/issues/983

According to several comments and PR´s from different projects:

AWS Go SDK´s `session.NewSession` must be probably replaced with `session.NewSessionWithOptions` [here](https://github.com/temporalio/temporal/blob/01d3e7fdeaedf6375426684fc5671185de3ba695/common/archiver/s3store/history_archiver.go#L113)
* https://github.com/aws/aws-sdk-go/issues/3101#issuecomment-604739840
* https://github.com/zalando-incubator/kube-metrics-adapter/pull/230

**Comment by denniskniep** [comment]
Update: Turned out, `403 Forbidden` error was due to missing S3 Permission in the RolePolicy and authentication via IRSA was already successfully executed.

It would be really helpful if one can activate debug logging of aws sdk if necessary for troubleshooting.

**Comment by denniskniep** [comment]
Created that PR #5059 which provides the ability to activate debug logging of aws sdk if necessary for troubleshooting.

**Comment by MichaelSnowden** [comment]
@denniskniep can this issue be closed?
