### ISSUE TITLE
community.temporal.io is not letting me open an account

### ISSUE THREAD

**Issue by kirtan-desai** [temporalio/temporal#5053]
## Expected Behavior
I should be able to sign up for an account

## Actual Behavior
Gives me an error saying the `Something went wrong, perhaps this email is already registered, try the forgot password link` but I try the forgot password link it says email does not exist. I tried this with three different emails and also trying logging in using google.

## Steps to Reproduce the Problem

  1. Go to community.temporal.io
  2. Sign up for an account

## Specifications

  - Version:
  - Platform:
  
  Sorry to add issue on this repo. I couldn't find the forum repo if there is any.

**Comment by yiminc** [comment]
This should have been fixed now.
