### ISSUE TITLE
Consider adding CANCELLATION_REQUESTED status to WorkflowExecutionStatus

### ISSUE THREAD

**Issue by mfateev** [temporalio/temporal#508]
**Is your feature request related to a problem? Please describe.**
DescribeWorkflowExecutionResponse doesn't contain information if a workflow has received a cancellation request.
This information is useful for troubleshooting.

**Describe the solution you'd like**
Either add CANCELLATION_REQUESTED status to WorkflowExecutionStatus enum or add some other field to DescribeWorkflowExecutionResponse that indicates that cancellation was requested.

**Comment by wxing1292** [comment]
dup of #1018
