### ISSUE TITLE
Workflow Status is 'Unspecified' on the default view

### ISSUE THREAD

**Issue by denispolish** [temporalio/temporal#509]
The status for the running workflow is always shown as 'unspecified' on the default workflow view.

v0.26.0-web

![image](https://user-images.githubusercontent.com/1528293/86770755-db2cf380-c059-11ea-984f-c94ac77e4f22.png)

![image](https://user-images.githubusercontent.com/1528293/86770846-0283c080-c05a-11ea-9667-ef516c344c92.png)

**Comment by feedmeapples** [comment]
Thanks for filing the ticket. The issue was fixed in one of the latest PRs #492
