### ISSUE TITLE
Temporal Services Crash on Namespace Initialization 

### ISSUE THREAD

**Issue by yifeili3** [temporalio/temporal#5097]
## Context: 

I'm implementing RDS IAM auth for Temporal server since there's a recent [support for pgx](https://github.com/temporalio/temporal/pull/4913) that enables the options to configure db driver with [OptionBeforeConnect](https://pkg.go.dev/github.com/jackc/pgx/v4/stdlib#OptionOpenDB) when opening a new db connection. This addressed the issue mentioned in https://github.com/temporalio/temporal/issues/3077 where the token expires and the server loses the connection.

## Expected Behavior

I got the RDS IAM auth working with the latest build.  I was able to establish persistent connections and run workflows with the remote RDS instance from my local machine only under the condition that database is wiped out before server starts/restarts. I expect the server to read the registered namespace before trying to create a new namespace during initialization.

## Actual Behavior

```
{"level":"error","ts":"2023-11-09T15:28:53.273Z","msg":"Operation failed with internal error.","error":"CreateNamespace: ERROR: duplicate key value violates unique constraint \"namespaces_pkey\" (SQLSTATE 23505)","operation":"InitializeSystemNamespace","logging-call-at":"persistence_metric_clients.go:1281"}
```
The server crashes because of an underlying SQL error when it tries to register the same system namespace. This seems to be a consistent issue whether using RDS IAM Auth or not. I dived into the code and found that it hardcoded the primary key so that explains the error.

## Steps to Reproduce the Problem

1. I was able to reproduce the same error using vanilla 1.22.1 server with Postgres 13.8 by just changing the db driverName from pg to pgx. (https://github.com/temporalio/temporal/blob/v1.22.1/common/persistence/sql/sqlplugin/postgresql/session/session.go#L82)
2. No issue in the latest main branch with configuration `pluginName: "postgres_pgx"`.
3. No issue in the latest main branch with RDS IAM support when temporal db is wiped. Reproduced the issue when server is killed and restarted without wiping DB

## Specifications

  - Version: 1.22.1
  - Platform: local & k8s

**Comment by ndtretyak** [comment]
> I was able to reproduce the same error using vanilla 1.22.1 server with Postgres 13.8 by just changing the db driverName from pg to pgx. 

Hi, you can not just change `driverName` constant in the code, since error handling depends on the driver. Since the uniqueness error is not processed correctly, the service crashes.

**Comment by yifeili3** [comment]
@ndtretyak Thanks for the reply. I just found out about this issue as well. the pgConn type assertion failed to recognize the dub entry error and bypass the logic to catch this error when namespace is initialized. I used pgx v4 to implement the auth options instead of v5 so that causes the error. Issue is fixed now
