### ISSUE TITLE
Import Error in Build a Temporal Application from scratch in Go Tutorial

### ISSUE THREAD

**Issue by horw** [temporalio/temporal#5113]
## Describe the bug
Following the tutorial at https://learn.temporal.io/getting_started/go/hello_world_in_go/, I encounter import errors.

## Actual Behavior
could not import go.temporal.io/sdk/worker (no required module provides package "go.temporal.io/sdk/worker")

## Steps to Reproduce the Problem
  1. go get go.temporal.io/sdk

**Comment by yiminc** [comment]
Cannot repo. Followed https://learn.temporal.io/getting_started/go/hello_world_in_go/
```
~/code 21:42:47
$ mkdir hello-world-temporal
$ cd hello-world-temporal
~/code/hello-world-temporal 21:42:54
$ go mod init hello-world-temporal/app
go: creating new go.mod: module hello-world-temporal/app
~/code/hello-world-temporal 21:42:58
$ go get go.temporal.io/sdk
go: added go.temporal.io/sdk v1.25.1
```

Please use https://community.temporal.io/ or [slack](https://t.mp/slack)  to seek help like this.
