### ISSUE TITLE
If a workflow completes with not complete updates the server should fail those updates and notify the caller

### ISSUE THREAD

**Issue by Quinn-With-Two-Ns** [temporalio/temporal#5174]
## Expected Behavior
If a client sends an update request to a workflow, but the workflow completes before the update is complete the client is notified with a failure.

## Actual Behavior
If a client sends an update request to a workflow, but the workflow completes before the update is complete the client hangs.

**Comment by Quinn-With-Two-Ns** [comment]
The same logic should also apply to terminated workflows ie pending update request sent to a terminated workflow should return some error.

**Comment by dandavison** [comment]
Closed by https://github.com/temporalio/temporal/pull/5848, tests added https://github.com/temporalio/temporal/pull/5854
