### ISSUE TITLE
Migrate usage of metrics.Handler to metricDefinition.With

### ISSUE THREAD

**Issue by MichaelSnowden** [temporalio/temporal#5189]
**Is your feature request related to a problem? Please describe.**

The problem is that calls to our `metrics.Handler`'s methods often contain redundant information like this:

```
handler.Histogram( myHisto.Name(), myHisto.Unit() ).Record(...)
            │             │               └───┐
            │             │                   │
            └─────┐       └───────────┐       │
                  │                   │       │
   Redundant and Unsafe: 'Histogram'  │       │
   is specified despite knowing       │       │
   'myHisto' is a histogram. There's  │       │
   also a risk if 'myHisto.Name()'    │       │
   refers to a metric definition that │       │
   is not a histogram.                │       │
                                      └─── Redundant information
```

However, we now have an alternative solution as of https://github.com/temporalio/temporal/pull/5187.

**Describe the solution you'd like**

I'd like us to migrate all usage of `metrics.metricDefinition` objects to the new style of recording metrics. See [this](https://github.com/temporalio/temporal/pull/5187/files#diff-749877df70d45313bebea67a420260e28c0b2c5810cea6a246556f73e817f212) for an example. This should be a fairly mechanical refactoring. We may be able to utilize some automated structural refactoring tools, or this could be done manually.

**Describe alternatives you've considered**

**Additional context**

**Comment by luansapelli** [comment]
I think we can close this issue now 😄

Thanks for the support @MichaelSnowden.

**Comment by stephanos** [comment]
Closed as fixed in https://github.com/temporalio/temporal/pull/5236
