### ISSUE TITLE
Authorizer should be applied to AdminHandler API's

### ISSUE THREAD

**Issue by rfwagner** [temporalio/temporal#521]
The authorization.Authorizer interface is an extension point that lets integrators define their own custom authorization logic. 

Currently if a non-nil Authorizer is supplied, it is applied only to the workflow Handler (the Resource service). The code in frontend/service.go::Start wraps an AccessControlledWorkflowHandler around the base Handler and the AccessControlledWorkflowHandler calls the Authorizer interface on each API call, resulting in an Allow/Deny decision before forwarding the API call down to the base Handler (in the case of an Allow decision).

This same pattern should be applied to the AdminHandler as well. Our high level requirement here is that we are operating a multi-tenant Temporal cluster as a service and we want to disallow normal users from accessing admin commands via tctl. By applying the Authorizer interface to the AdminHandler API's, we are able to first check that the caller has admin credentials before forwarding the API call. Without an authorization wrapper around AdminHandler, this is not possible.

I'm open to other approaches to disallowing users from accessing admin commands if there's a cleaner way to go about it, but the above seems like a straightforward approach.

**Comment by sergeybykov** [comment]
Authorization functionality has been refactored, so that Authorizer is invoked as an interceptor on all inbound gRPC calls for all handlers, which I believe addressed this. Feel free to reopen if I missed something.
