### ISSUE TITLE
Authorizer interface could be richer

### ISSUE THREAD

**Issue by rfwagner** [temporalio/temporal#522]
Our use case is that we are running a multi-tenant Temporal cluster as a service. As cluster operators, we want to be in charge of all admin operations and all namespace provisioning operations. In addition, we would like to ensure that normal users can only see namespaces that they own.

The basic building block to enable this today is the authorization.Authorize interface. It works, but the interface is fairly simplistic. The only information we have to go on to make a Deny/Allow decision is whatever credentials we find in the context along with the name of the API call (as a string) and the name of the target namespace, if any.

We can do string matching on the APIName to disallow RegisterNamespace, UpdateNamespace and DeprecateNamespace for non admin-credentialed callers, but this feels brittle. Is there some way to add finer granularity to the Authorize interface so that we could know more directly that an API call is updating the set of namespaces?

ListNamespaces is also problematic: we want normal users to be able to run 'tctl namespace list' and see the namespaces they own, but not the ones they don't. Again, we can implement this with the existing interface by doing post filtering of results returned by the delegate handler, but it feels a little brittle.

Thinking out loud: perhaps authorization.Result could be extended to include a list of allowed namespaces for the given call:

	Result struct {
		Decision Decision
                AuthorizedNamespaces []string
	}

interpreted as:

    - in the case of an API that targets a single namespace, allow the call if Decision == DecisionAllow and the target is in the supplied list or the supplied list is empty(?)
    - in the case of an API that targets multiple namespaces (i.e. namespace list), allow the call but restrict results to the specified namespaces

**Comment by rfwagner** [comment]
Expanding on this statement from above regarding adding authorization to 'namespace list': "Again, we can implement this with the existing interface by doing post filtering of results returned by the delegate handler, but it feels a little brittle."

Actually, doing this requires either:

1. supplying our own complete implementation of an AccessControlledWorkflowHandler or
2. modifying the stock implementation of AccessControlledWorkflowHandler

1 means maintaining a lot of boilerplate delegation code just to work around this issue. 2 means maintaining changes in a fork of the upstream temporal code. So neither approach is very attractive.

**Comment by sergeybykov** [comment]
With the refactored authorization mechanism of `Authorizer` and `ClaimMapper`, we now support handling an explicit set of per-namespaces user roles and system-level roles for operations, such as `RegisterNamespace`.

However, `ListNamespaces` is still problematic because we aren't filtering results upstream.

**Comment by yiminc** [comment]
The authorizer is now capable of handling per-namespace user roles. This should satisfy the major ask of this issue. The limitation on filtering the ListNamespaces still exists, but that be a separate issue if that is needed.
