### ISSUE TITLE
Binaries for `1.22.3` missing in release

### ISSUE THREAD

**Issue by danieljoos** [temporalio/temporal#5223]
I believe the latest run of `goreleaser` failed for the `1.22.3` release:
https://github.com/temporalio/temporal/actions/runs/7134421678

It would be awesome to get it working again.
Thanks already.

/cc @rodrigozhou

**Comment by rodrigozhou** [comment]
Hm. I think I forgot to cherry pick the fix from the main branch.
However, do you mind sharing why you need the binaries? We have the [Temporal CLI](https://github.com/temporalio/cli) and also Docker images to run Temporal Server.
Also, we're planing to remove these binaries going forwards anyway.

**Comment by danieljoos** [comment]
For our use-case we built a custom Docker image and download the binaries from the GitHub release.
We need to base on some internal image because of compliance/security reasons.
It was very handy to just download the binaries from the GitHub release instead of building them our own.

**Comment by rodrigozhou** [comment]
@danieljoos We just release v1.22.4 which included the binaries.
