### ISSUE TITLE
Retrieved String Search Attribute includes quotation characters

### ISSUE THREAD

**Issue by pauldemarco** [temporalio/temporal#524]
## Expected Behavior
Retrieving **string** search attributes should not contain the quotation marks.

## Actual Behavior
The string retrieved from Search attributes includes quotations marks. If json is stored, or any other string encoded value, the first and last characters must be trimmed before decoding.

## Steps to Reproduce the Problem

  1. Retrieve search attribute
```
bytes := v.GetSearchAttributes().IndexedFields["CustomStringField"].Data
fmt.Printf("value: %s", bytes)  // prints value: "your-value"
```

## Specifications

  - Version: 0.26.0
  - Platform: Kubernetes

**Comment by samarabbas** [comment]
@alexshtin can you create corresponding issues in sdk repos and close this one.

**Comment by samarabbas** [comment]
This is post code complete.
