### ISSUE TITLE
Run workflows at sunset or sunrises 

### ISSUE THREAD

**Issue by kakopappa** [temporalio/temporal#5251]
**Is your feature request related to a problem? Please describe.**

Would like to start a workflow at sunrise or sunset based on a GPS location provided

**Describe the solution you'd like**

Start a workflow with

1. the GPS coordinates 

2. parameters like 
SUNSET (at sunset)
SUNSET+10m (10 mins after sunset)
SUNRISE-10 (10 mins before sunrise)

**Describe alternatives you've considered**

Looked at cron. Doesn’t seems to support this feature https://docs.temporal.io/workflows?_ga=2.197631087.1550479080.1703935511-856855575.1703935511#cron-schedules

Couldn’t find an alternative solution. If there’s please let me know

**Additional context**
This is for IOT platform to trigger user workflows at 🌅 or  🌄

**Comment by dnr** [comment]
This is an interesting idea but it seems like very niche functionality, and I don't think we want to build that into the server. Instead, we plan to expose an option in the [schedules feature](https://docs.temporal.io/workflows#schedule) (note: not the older "cron" feature whose docs you linked to) to supply a list of absolute timestamps. You could compute the list yourself and keep it updated periodically to achieve this effect. In the meantime, you could use the schedules feature with a list of calendar specs to achieve the same effect.
