### ISSUE TITLE
Upgrade `postgres` to `postgres12` driver.

### ISSUE THREAD

**Issue by duydo-ct** [temporalio/temporal#5260]
Hi. we have registered using driver `postgres` when using `Postgres` database.
Now we want to upgrade to `postgres12` driver.
How can I check if it requires a DB schema update?
If a schema update is needed, would it cause a downtime since we have roughly 50GB data on `Production`.
Thanks a lot. :gratitude-thank-you:
- Version Temporal Server: `1.22.1`

**Comment by yiminc** [comment]
There is no schema update needed between PostgreSQL versions.
