### ISSUE TITLE
"Error updating timer ack level for shard" errors when enabling task list partitioning

### ISSUE THREAD

**Issue by skrul** [temporalio/temporal#530]
## Expected Behavior

No errors :)

## Actual Behavior

On v0.23.0 when running only the echo canary, I am seeing various errors when deploying a dynamicconfig with the following settings:
```
matching.numTasklistWritePartitions:
- value: 10
  constraints: {}
matching.numTasklistReadPartitions:
- value: 10
  constraints: {}
```

The history service logs errors that look like this
```
{"level":"error","ts":"2020-07-09T17:39:23.515Z","msg":"Error updating timer ack level for shard","service":"history","shard-id":389,"address":"100.64.42.181:7234","component":"timer-queue-processor","cluster-name":"active","error":"Failed to update shard. Previous range ID: 46; new range ID: 47","logging-call-at":"timerQueueAckMgr.go:393","stacktrace":"github.com/temporalio/temporal/common/log/loggerimpl.(*loggerImpl).Error\n\t/temporal/common/log/loggerimpl/logger.go:138\ngithub.com/temporalio/temporal/service/history.(*timerQueueAckMgrImpl).updateAckLevel\n\t/temporal/service/history/timerQueueAckMgr.go:393\ngithub.com/temporalio/temporal/service/history.(*timerQueueProcessorBase).internalProcessor\n\t/temporal/service/history/timerQueueProcessorBase.go:328\ngithub.com/temporalio/temporal/service/history.(*timerQueueProcessorBase).processorPump\n\t/temporal/service/history/timerQueueProcessorBase.go:195"}
```

Additionally, here are a few metrics from the matching service that are getting triggered while the task list partitioning is enabled.  During this test (starting at 14:00 on the graphs) I ran the canary first with just echo, then added query, then signal, then concurrent execution. 

![image](https://user-images.githubusercontent.com/372141/87190132-c72a0180-c2a6-11ea-8827-77e3b6236104.png)
Yellow is operation:adddecisiontask and blue is operation:addactivitytask (which started to appear when the concurrent execution canary was enabled)

![image](https://user-images.githubusercontent.com/372141/87190240-fe001780-c2a6-11ea-9052-56cf47342cda.png)

These persistence errors on operation:updatetasklist happened first when enabling the partitioning then disabling it:
![image](https://user-images.githubusercontent.com/372141/87190356-2be55c00-c2a7-11ea-9fc5-0ec9cad76094.png)

Also note that even though there were errors, none of the canary workflow executions failed.

## Steps to Reproduce the Problem

  1. Run temporal v0.23.0
  2. Enable task list partitioning
  3. Run the echo canary

## Specifications

  - Version: v0.23.0
  - Platform: k8s

**Comment by wxing1292** [comment]
close due to issue too old, plus did not seen similar issue during load testing

plz reopen if latest version 1.7.x+ has similar issue
