### ISSUE TITLE
Retention update ignored

### ISSUE THREAD

**Issue by Zylius** [temporalio/temporal#5370]
Yesterday we upgraded namespace retention settings, but they keep on being deleted after 3 days.

## Expected Behavior

Updating retention with `tctl n default --retnetion 31` should change retention to 31 days (744 hours). I.E. Workflows should exist 

## Actual Behavior

Retention remains default 3 days.

## Steps to Reproduce the Problem

  1. Create a blank temporal server
  2. Update retention to 31 days
  3. Retention is reported as changed everywhere, but the workflows are still deleted.

## Specifications

  - Temporal Server Version: 1.22.4
  - Platform: Astra DB Cassandra 4.0.0.6816, PHP 8.1+ Roadrunner/Go services
 
## More info:
 I've looked at data `0x0a310a2435643039653865302d336266622d346261662d613565352d38656536336662333133363410011a0764656661756c74120d0a050880bda3011a00200130011a120a06616374697665120661637469766518012004` stored in cassandra and decoded it with [NamespaceResponse](https://github.com/temporalio/temporal/blob/main/proto/internal/temporal/server/api/persistence/v1/namespaces.proto#L35) structure it seems that we have 2678400 seconds stored, which is correct 31 days.

Also screenshots from tctl, elastika, temporal-web
![image](https://github.com/temporalio/temporal/assets/5536051/6aad5ea9-459d-4c68-ab02-e7f1fbc1af00)
![image](https://github.com/temporalio/temporal/assets/5536051/d491df58-24de-4a38-8779-cb628b4e61bb)
![image](https://github.com/temporalio/temporal/assets/5536051/fe7b1f2a-cfee-4138-a2ba-040b3a962726)

Showing that it's actually still deleting is a lil bit hard, but you get the point. I hope you can recreate it.
What's going on? Why is it still picking default 3 days?

Am I missing something?

**Comment by Zylius** [comment]
> Did the workflow that are being deleted after 3 days complete before or after the retention setting was changed? The retention timer is applied at workflow close time, so only workflows that complete (or fail) after the setting was changed will get the new retention.

Ahh I see, didn't know that the record itself stores retention time. Closing this issue ;) Thank you!

**Comment by r00ta** [comment]
For the posterity, in case you have an old DB dump that you need to inspect and to attach the temporal server/UI you have to move back the clock of you machine ;)
