### ISSUE TITLE
Vulnerability identified in otelgrpc package < 0.46.0

### ISSUE THREAD

**Issue by vinimona** [temporalio/temporal#5403]
Hi, 

There is a security vulnerability identified and reported in go package go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc (as mentioned [here](https://github.com/advisories/GHSA-8pgv-569h-w5rw)). This vulnerability is fixed in version 0.46.0. We observed that the latest temporal version i.e. 1.22.4 still uses an affected version of the package i.e. 0.42.0. Do you have an estimate on when the next release will be available which will have the fix for the reported vulnerability?

Thanks.

**Comment by stephanos** [comment]
@vinimona
Thank you for reporting the issue! We will update the main branch asap. I'm not sure whether it can be part of the next release. I'll have to check with the team.

**Comment by stephanos** [comment]
Oh, actually, nevermind: the library was already updated 2 days ago: https://github.com/temporalio/temporal/pull/5396
