### ISSUE TITLE
TaskQueue Kind not set for Scheduled WorkflowTask

### ISSUE THREAD

**Issue by samarabbas** [temporalio/temporal#543]
## Expected Behavior
Should be able to see Kind set to either `Normal` or `Sticky`

## Actual Behavior
Here is the output I see from tctl:
```
11  2020-07-14T19:34:11-07:00  WorkflowTaskScheduled           {TaskQueue:{Name:Samars-MacBook-Pro.local:fc872005-0526-4fc6-892b-8614d6ad7cc6,
                                                                 Kind:Unspecified}, StartToCloseTimeoutSeconds:10, Attempt:0}
```

## Steps to Reproduce the Problem

  1. Start workflow execution
  1. `./tctl wf show -w <id>`

## Specifications

  - Version:
  - Platform:

**Comment by alexshtin** [comment]
Was it timer task?
