### ISSUE TITLE
Temporal query reporting wrong value

### ISSUE THREAD

**Issue by abhimanyusinghgaur** [temporalio/temporal#5460]
## Actual Behavior
We have a workflow with the following query handler:
```
var state = &models.Execution{ ... }
queryHandler := func() (*models.Execution, error) { return state, nil }
if err := workflow.SetQueryHandler(ctx, "status", queryHandler); err != nil {
	return err
}

// state gets updated later as workflow progresses
```
The `models.Execution` looks like this:
```
type Execution struct {
	ID           string             `gorm:"column:id;primaryKey;type:uuid;not null"`
	Type         v1.ExecutionType   `gorm:"column:type;type:smallint;not null"`
	Input        string             `gorm:"column:input;not null"`
	Schema       *string            `gorm:"column:schema"`
	NumberOfRows *int32             `gorm:"column:number_of_rows"`
	SizeInBytes  *int32             `gorm:"column:size_in_bytes"`
	Status       v1.ExecutionStatus `gorm:"column:status;type:smallint;not null"`
	Error        *string            `gorm:"column:error;type:text"`
	CreatedBy    string             `gorm:"column:created_by;not null"`
	CreatedAt    time.Time          `gorm:"column:created_at;not null"`
	StartedAt    *time.Time         `gorm:"column:started_at"`
	FinishedAt   *time.Time         `gorm:"column:finished_at"`
}
```
The problem is with `StartedAt` and `FinishedAt` fields. `StartedAt` is set at the very beginning of the workflow, and `FinishedAt` is set the end of the workflow.

While the workflow is running, we get the following response from the query:
```
{
    "type": "...",
    "input": "...",
    "schema": "...",
    "status": "...",
    "createdBy": "...",
    "createdAt": "2024-02-21T21:08:39.667Z",
    "startedAt": "2024-02-21T21:08:39.710Z",
    "finishedAt": null
}
```
As you can see, the `startedAt` is just some milliseconds after `createdAt`. That's expected.
Once the workflow has finished, we get this response from the query:
```
{
    "type": "...",
    "input": "...",
    "schema": "...",
    "numberOfRows": ...,
    "sizeInBytes": ...,
    "status": "...",
    "createdBy": "...",
    "createdAt": "2024-02-21T21:08:39.667Z",
    "startedAt": "2024-02-21T21:08:51.663Z",
    "finishedAt": "2024-02-21T21:08:51.663Z"
}
```
Here you see that `startedAt` suddenly becomes exactly same as `finishedAt`. That's completely weird!

We have rechecked this multiple times in our codebase, and we are not doing any silly pointer mistakes here. We were even saving the `Execution` struct into our own postgres instance at the end of workflow, and there the values are completely correct. The values in our postgres instance are:
```
startedAt: "2024-02-21T21:08:39.710Z"
finishedAt: "2024-02-21T21:08:51.663Z"
```
So, it seems that temporal query isn't able to retrieve the values it stores for completed workflows correctly. Some problem with either unmarshalling its stored query response payload for completed workflows or marshalling the query response payload before temporal stores it.

### More observations
* Everytime I call that temporal query, the values for `startedAt` and `finishedAt` turn out to be the latest local time on my machine. That is even weirder. The way we are initializing those values is this:
```
func NowFunc() time.Time {
	return time.UnixMilli(time.Now().UnixMilli()).Local()
}

func NowFuncPtr() *time.Time {
	now := NowFunc()
	return &now
}

// initial initialization at start of workflow
state := &models.Execution{
		ID:        ...,
		CreatedBy: ...,
		CreatedAt: params.CreatedAt,
		StartedAt: NowFuncPtr(),
		Type:      ...,
		Status: ...,
	}

// later when workflow is finished, we do this:
state.FinishedAt = NowFuncPtr()
```
So, once set within workflow, the values should not have changed. But, they seem to be changing on every call to the query handler. I have verified even their pointer addresses:
```
"startedAtPtr": "0xc000e4ec60", "finishedAtPtr": "0xc000e4ede0"
```
they are indeed two different memory locations, but the values still turn out to be the same and the latest time on my machine.

## Expected Behavior
Temporal query should return correct values. i.e., in our case, the `startedAt` and `finishedAt` fields should not have changed at all.

## Specifications

  - Version: docker image - `temporalio/server:1.22.4`
  - Platform: 
    - Go: `go version go1.21.5` (don't think this would matter)
    - OS: Doesn't matter, happens on both mac or linux.

**Comment by Quinn-With-Two-Ns** [comment]
This is a bug in your workflow code, you should not be using `time.Now` in workflow code since the result is not deterministic across [replay](https://docs.temporal.io/workflows#replays). You need to use [workflow.Now](https://pkg.go.dev/go.temporal.io/sdk/workflow#Now) inside workflows.

**Comment by abhimanyusinghgaur** [comment]
Thanks, that fixed it. It is not a bug in temporal.
