### ISSUE TITLE
Request for standardized suffixes (Temporal doesn't abbreviate very well into a 3-4 letter key)

### ISSUE THREAD

**Issue by nodiex-cloud** [temporalio/temporal#567]
Hello, in light of the move of the maintenance of this project into the Temporal organization, and the change from Cadence to Temporal I am forced to come up with a suffix/abbreviation in my code for the character string Temporal. For Cadence, it was simple, I used cdnc. I personally, really don't like the abbreviation style of putting the number of letters between the first and last characters in a word ie, k8s, l8n. 

I also really don't want to type of temporal everywhere, that is entirely too long of an identifier. Please specify a suffix that is appropriate and please, please, please don't pick t6l. 

Soo... in that vein, what are you guys thinking tprl or trl? Anything past 4 characters is excessive imo.

**Comment by pauldemarco** [comment]
tmpl :smile:

**Comment by nodiex-admin** [comment]
I knew I was missing something. That sounds good to me.
