### ISSUE TITLE
Limitation in custom search attribute names

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/temporal#5670]
To repro:

tctl adm cl asa -n A.B.C -t Text
tctl adm cl asa -n A.B.C.D -t Text

(can also add with cli :) )

temporal workflow list -q "A.B.C='abc'"
runs fine

temporal workflow list -q "A.B.C.D='abcd'" 
gives error:

Error: unable to list workflow executions: invalid query: malformed SQL query: syntax error at position 34
('export TEMPORAL_CLI_SHOW_STACKS=1' to see stack traces)

seems in names with dots you cannot specify more than 2

**Comment by rodrigozhou** [comment]
You need to enclose search attributes with dots backticks. Eg: ``temporal workflow list -q "`A.B.C.D` = 'abcd'"``.

**Comment by tsurdilo** [comment]
What's the rules at this point you need to do the enclose? Trying to document

**Comment by Kindratte** [comment]
> You need to enclose the search attribute name with backticks. Eg: `` temporal workflow list -q "`A.B.C.D` = 'abcd'" ``.

try this from Go SDK `'glossary.GlossDiv.GlossList.GlossEntry.GlossTerm'='SMGL'"`
got this 
```
"invalid query: unable to convert filter expression: unable to convert left side of \"'glossary.GlossDiv.GlossList.GlossEntry.GlossTerm' = 'SMGL'\": invalid expression: must be a column name but was *sqlparser.SQLVal"
```
