### ISSUE TITLE
batch 400 error code

### ISSUE THREAD

**Issue by clcc2019** [temporalio/temporal#5732]
```yaml
invalid query: unable to convert filter expression: unable to convert left side of "TemporalNamespaceDivision = 'TemporalBatcher'": filter by 'TemporalNamespaceDivision' not supported for standard visibility

```
<img width="1509" alt="image" src="https://github.com/temporalio/temporal/assets/46099295/96c6c349-1c63-46f9-ae06-a051537c4c08">

**Comment by yiminc** [comment]
Batch operation require advanced visibility (ElasticSearch or SQL based). Standard visibility has been deprecated. See deprecation announce in https://github.com/temporalio/temporal/releases/tag/v1.23.0. 
`Standard visibility will be deprecated in the next release v1.24.0 along with old config key names, i.e. this is the last minor version to support them. Please refer to [v1.20.0 release notes](https://github.com/temporalio/temporal/releases/tag/v1.20.0) for upgrade instructions, and also refer to [v1.21.0 release notes](https://github.com/temporalio/temporal/releases/tag/v1.21.0) for config key changes.`
