### ISSUE TITLE
All Elasticsearch errors are returned back as internal service errors

### ISSUE THREAD

**Issue by samarabbas** [temporalio/temporal#582]
If user queries on an invalid index, elastic search returns back `bad query: 400` error back to the caller.  Temporal wraps all elastic search errors as internal service errors resulting in retry logic to kick in by clients.  Certain errors like error code 400 should not be wrapped as internal service errors.

**Comment by samarabbas** [comment]
Here is one example:

```
ctx := context.Background()
	searchResult, err := v.esClient.SearchWithDSL(ctx, v.index, queryDSL)
	if err != nil {
		return nil, serviceerror.NewInternal(fmt.Sprintf("ListWorkflowExecutions failed. Error: %v", err))
	}
```

**Comment by alexshtin** [comment]
After discussions and investigations we found that the way how we communicate errors needs to be changed to support this. `Internal` needs to be replaced with `Unavailable` everywhere where it should be retried. Which is a breaking change and will require us to block newer SDKs on old servers.
