### ISSUE TITLE
[Go SDK Bench] Corrupted incontinouous event batch makes workflow unusuable

### ISSUE THREAD

**Issue by mastermanu** [temporalio/temporal#584]
Our Bench Stat's workflow (whose sole job is to aggregate signals and update counters for test reporting / validation) got permanently stuck running into the following error:

"corrupted history event batch, eventID is not continouous"

As a result, that error keeps happening, the Workflow is perpetually stuck.

[admin_describe.txt](https://github.com/temporalio/temporal/files/4956834/admin_describe.txt)
[admin_dump.txt](https://github.com/temporalio/temporal/files/4956836/admin_dump.txt)
[frontend_logs.txt](https://github.com/temporalio/temporal/files/4956837/frontend_logs.txt)

{"level":"error","ts":"2020-07-21T22:48:14.497Z","msg":"Corrupted incontinouous event batch","service":"frontend","wf-branch-id":"1e215ab0-1a32-4089-814b-f96f6c8121c7","wf-tree-id":"1e5c08f7-1c00-4ab3-94a3-73259710a7cc","xdc-first-event-version":-24,"wf-first-event-id":1852,"xdc-last-event-version":-24,"wf-next-event-id":1852,"xdc-token-last-event-version":-24,"token-last-event-id":1850,"counter":1,"logging-call-at":"historyStore.go:462"

The dump indicates that event id 1851 was lost (the log has 1850 and 1852, which refers to 1851 as a scheduled event id, but that is nowhere to be found).

There were no known persistence errors in cassandra logs or in the grafana dashboard, suggesting Cassandra is not at fault here. Any logs that occurred when this error started happening have since been truncated/lost

**Comment by wxing1292** [comment]
close due to issue being too old and CICD pipeline never seen above issue
