### ISSUE TITLE
Unable to reset Workflow with hole in history events

### ISSUE THREAD

**Issue by mastermanu** [temporalio/temporal#585]
See: https://github.com/temporalio/temporal/issues/584

The following reset command fails with the same error: 
./tctl --ct 300 --ns benchtest workflow reset -w config-driven-stats-throughputstress-1-96 -r 1e5c08f7-1c00-4ab3-94a3-73259710a7cc --reason a --reset_type FirstWorkflowTaskCompleted

This means the workflow is not recoverable, even to a point before the hole as it reads the whole history before trying to recover.

**Comment by vitarb** [comment]
Resolved in #661
