### ISSUE TITLE
"Unspecified task queue kind" warnings in Temporal Server 1.23.0 (CLI version 0.12.0)

### ISSUE THREAD

**Issue by tomwheeler** [temporalio/temporal#5903]
When starting a local Temporal development server using Temporal CLI version 0.12.0, I observe multiple "Unspecified task queue kind" warnings in the terminal window. Although I experience this while using the CLI, I believe the underlying problem is in the server code, so I am reporting it here.

## Expected Behavior
When starting the development server via the CLI, using the default options, I do not expect to see warnings or errors in the terminal window (except in case of user error, such as a port conflict on the machine).

## Actual Behavior
After starting the development server via the CLI, I frequently see multiple warnings with the message "Unspecified task queue kind" in the terminal window where that server is running. Here is a complete copy of the terminal session in which I started the development server. There are 10 such warnings (amid three "error in prometheus reporter" warnings, about which I filed [issue #5897](https://github.com/temporalio/temporal/issues/5897) yesterday):

```
$ temporal server start-dev
Temporal server is running at: localhost:7233
Web UI is running at: http://localhost:8233
Metrics available at: http://localhost:64716/metrics
time=2024-05-10T10:34:44.299 level=WARN msg="error in prometheus reporter" error="a previously registered descriptor with the same fully-qualified name as Desc{fqName: \"AccessHistoryOld\", help: \"AccessHistoryOld counter\", constLabels: {}, variableLabels: [{service_name <nil>} {operation <nil>} {namespace <nil>}]} has different label names or a different help string"
time=2024-05-10T10:34:44.309 level=WARN msg="error in prometheus reporter" error="a previously registered descriptor with the same fully-qualified name as Desc{fqName: \"AccessHistoryOld\", help: \"AccessHistoryOld counter\", constLabels: {}, variableLabels: [{service_name <nil>} {namespace <nil>} {operation <nil>}]} has different label names or a different help string"
time=2024-05-10T10:47:47.354 level=WARN msg="Unspecified task queue kind" service=frontend wf-task-queue-name=orders wf-namespace=default
time=2024-05-10T10:47:47.364 level=WARN msg="Unspecified task queue kind" service=frontend wf-task-queue-name=orders wf-namespace=default
time=2024-05-10T10:47:47.417 level=WARN msg="error in prometheus reporter" error="a previously registered descriptor with the same fully-qualified name as Desc{fqName: \"AccessHistoryOld\", help: \"AccessHistoryOld counter\", constLabels: {}, variableLabels: [{operation <nil>} {service_name <nil>} {namespace <nil>}]} has different label names or a different help string"
time=2024-05-10T10:48:15.333 level=WARN msg="Unspecified task queue kind" service=frontend wf-task-queue-name=orders wf-namespace=default
time=2024-05-10T10:48:15.337 level=WARN msg="Unspecified task queue kind" service=frontend wf-task-queue-name=orders wf-namespace=default
time=2024-05-10T10:48:17.951 level=WARN msg="Unspecified task queue kind" service=frontend wf-task-queue-name=orders wf-namespace=default
time=2024-05-10T10:48:17.953 level=WARN msg="Unspecified task queue kind" service=frontend wf-task-queue-name=orders wf-namespace=default
time=2024-05-10T10:49:11.224 level=WARN msg="Unspecified task queue kind" service=frontend wf-task-queue-name=orders wf-namespace=default
time=2024-05-10T10:49:11.227 level=WARN msg="Unspecified task queue kind" service=frontend wf-task-queue-name=orders wf-namespace=default
time=2024-05-10T10:49:12.794 level=WARN msg="Unspecified task queue kind" service=frontend wf-task-queue-name=orders wf-namespace=default
time=2024-05-10T10:49:12.798 level=WARN msg="Unspecified task queue kind" service=frontend wf-task-queue-name=orders wf-namespace=default
```

## Steps to Reproduce the Problem

 1. Install Temporal CLI version 0.12.0 (which is based on Temporal Server release 1.23.0). I did this via homebrew, although I doubt that the installation method is relevant
2. Run `temporal server start-dev` to start the development server
3. Run a few Workflows. The code I'm using isn't yet in a public repo, but I don't believe the problem is specific to this application. If you're unable to reproduce the problem, let me know and I will share the code and/or demonstrate it. 

## Specifications

  - Version: Temporal CLI version 0.12.0
  - Platform: M2 MacBook Pro, running MacOS 13.6.6

**Comment by ShahabT** [comment]
This is already fixed in server code https://github.com/temporalio/temporal/pull/5661. It will be included in the next patch or minor release whenever comes first (1.23.2 or 1.24.0).
