### ISSUE TITLE
Support MySQL persistence for Admin commands which directly connects to database

### ISSUE THREAD

**Issue by samarabbas** [temporalio/temporal#598]
**Is your feature request related to a problem? Please describe.**
Temporal provides some useful admin commands which connects to database directly.
Looks like support for MySQL is missing right now for these admin `tctl` commands.

**Describe the solution you'd like**
`tctl` to support admin commands which directly connects to the database.

**Describe alternatives you've considered**

**Additional context**
https://community.temporal.io/t/how-to-configure-database-type-host-and-port-for-temporal-cli/266/4

**Comment by samarabbas** [comment]
Here is the implementation which provides support for Cassandra:
https://github.com/temporalio/temporal/blob/master/tools/cli/persistenceUtil.go#L73

**Comment by ringods** [comment]
Big question is: why do some admin commands require direct database access? Shouldn't `tctl` only talk to the Temporal server API?

It's like you would say `kubectl` needs direct access to the `etcd` store to manage a Kubernetes cluster.

Continuing this path makes it harder to add support for PostgreSQL (for which I have expressed interest before) or other storage backends. It also complicates the network setup for operational support in a production setup.

**Comment by feedmeapples** [comment]
@ringods 
The plan for admin commands was to:
1. Use temporal frontend as default (no direct db connection)
2. Through tctl options also support direct db connection to cover the cases when the service is down

We've implemented the latter first and plan to have both

**Comment by samarabbas** [comment]
@feedmeapples can you confirm if we still lack the ability to connect to database directly for non-cassandra databases?

**Comment by feedmeapples** [comment]
@samarabbas yes, MySQL and also PostgreSQL are supported  https://github.com/temporalio/temporal/pull/1002
