### ISSUE TITLE
temporalio/admin-tools:1.24.0 missing from dockerhub

### ISSUE THREAD

**Issue by bllfr0g** [temporalio/temporal#6052]
## Expected Behavior

temporalio/admin-tools:1.24.0 should be present in dockerhub

## Actual Behavior

it isn't

## Steps to Reproduce the Problem

  1. docker pull temporalio/admin-tools:1.24.0

**Comment by alexshtin** [comment]
We separated `admin-tools` docker [image](https://hub.docker.com/r/temporalio/admin-tools) release process. Version tag now includes versions of `tctl` (deprecated but still supported CLI) and `temporal` (modern CLI) binaries. This image is released every time whenever new version of any of these component is released. The right tag for 1.24.0 release is [1.24.0-tctl-1.18.1-cli-0.12.0](https://hub.docker.com/layers/temporalio/admin-tools/1.24.0-tctl-1.18.1-cli-0.12.0/images/sha256-a9ad0a14efb085d20ed04fc956c80af287359b20edbaa532b677c89a8b550ef2?context=explore)

Please note, we just published 1.24.1 and corresponding `admin-tools` image is [1.24.1-tctl-1.18.1-cli-0.12.0](https://hub.docker.com/layers/temporalio/admin-tools/1.24.1-tctl-1.18.1-cli-0.12.0/images/sha256-67a4b19942b546b6efeeb97bc3edcff5db61daff09b4e6ee4778d5193a8f1382?context=explore)
