### ISSUE TITLE
1.24.0 requires a schema upgrade, but it is not mentioned in the release notes?

### ISSUE THREAD

**Issue by bllfr0g** [temporalio/temporal#6059]
https://docs.temporal.io/self-hosted-guide/upgrade-server

When a schema upgrade is required, it is supposed to be mentioned in the release notes.

Apparently 1.24.0 requires a schmea upgrade, but this is not called out.

**Comment by pdoerner** [comment]
This was an oversight on our part. The release notes have been updated now.
