### ISSUE TITLE
Load all task queue partitions when root one is loaded

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/temporal#6160]
Feature request to load all task queue partitions when root one is loaded.
This helps prevent possible delays in task dispatch in low traffic situations and with the long worker poll timeout.

**Comment by jmbarzee** [comment]
Thank you for your request. I forgot to let you know, we added this feature with #6324

**Comment by jmbarzee** [comment]
Closing as this work is complete.

**Comment by jmbarzee** [comment]
6324
