### ISSUE TITLE
TestIntegrationSuite/TestActivityHeartbeatTimeouts is flaky

### ISSUE THREAD

**Issue by alexshtin** [temporalio/temporal#619]
```
    activity_test.go:1081: 
        	Error Trace:	activity_test.go:1081
        	Error:      	Should be false
        	Test:       	TestIntegrationSuite/TestActivityHeartbeatTimeouts
        	Messages:   	Expected activities to timeout but seeing completion instead
```

**Comment by samarabbas** [comment]
This could be an actual bug where we are loosing timer tasks for heartbeat timeouts.  This needs more investigation.  Here are relevant logs:

[activity_7_timeline.txt](https://github.com/temporalio/temporal/files/5003490/activity_7_timeline.txt)
[Failed Activity Info.txt](https://github.com/temporalio/temporal/files/5003491/Failed.Activity.Info.txt)
[history.txt](https://github.com/temporalio/temporal/files/5003492/history.txt)
[test.log](https://github.com/temporalio/temporal/files/5003493/test.log)

**Comment by wxing1292** [comment]
stale issue, close (buildkite in the past few month see no above issue)
