### ISSUE TITLE
schema checks at server start

### ISSUE THREAD

**Issue by bgerrity** [temporalio/temporal#6202]
The server should quit early if the Persistence Store database has a mismatched schema. Ideally, there'd be a check when the server initially connects to the database. Logging an error for a schema mismatch for the Visibility Store would also be valuable telemetry.

If this has already been implemented please go ahead and close. Otherwise if there's interest I'd be happy to take this on.

**Comment by yiminc** [comment]
This is already implemented. Upon server startup, it checks the schema version from database and match with what the minimal version requirement from the code. If the don't match, server exist with error message.
If you see this is not the case, please let us known.
