### ISSUE TITLE
What could be the problem with the slow opening of the temporal web?

### ISSUE THREAD

**Issue by trustnote-wang** [temporalio/temporal#6206]
I'm seeing a very slow loading of the resource http://10.0.0.57:32080/api/v1/namespaces/Answer-Flow/workflow-count?query=GROUP+BY+ExecutionStatus,  which takes nearly 1 minute. Our temporal uses a MySQL database

What could be the possible reasons? Please help me！

**Comment by yiminc** [comment]
Could you first identify if this is a web server issue or the temporal server issue?
You can check if the same query has similar latency issue by using temporal CLI to access server directly.
