### ISSUE TITLE
Temporal CLI download link seems to be incompatible with declared architecture

### ISSUE THREAD

**Issue by khalifmahdi** [temporalio/temporal#6209]
While trying to install Temporal CLI, I downloaded this file `https://temporal.download/cli/archive/latest?platform=linux&arch=amd64` (from [here](https://docs.temporal.io/cli#how-to-install-the-temporal-cli-on-linux)) to `/usr/local/bin/temporal`. 
After `chmod +x` and running the file, the following error is returned:
```
execute binary file: Exec format error
```
It seems the link is invalid for amd46 architecture.

```bash
# dpkg --print-architecture
amd64

# cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
...
```

## Expected Behavior
Temporal CLI help info to appear upon running `temporal` command:
```
NAME:
   temporal - Temporal command-line interface and development server
...
```

## Actual Behavior
The following error was returned:
```
execute binary file: Exec format error
```

## Steps to Reproduce the Problem

  1. `curl https://temporal.download/cli/archive/latest?platform=linux&arch=amd64 -o /usr/local/bin/temoral`
  1. `chmod +x /usr/local/bin/temoral`
  1. `temporal`

## Specifications

  - Version: latest (Not sure)
  - Platform: Ubuntu 22.04.4 LTS

**Comment by cretz** [comment]
That download is a tarball (you can use https://temporal.download/cli/latest?platform=linux&arch=amd64 first to see the file it will download). The filename HTTP auto-suggests for that download is `temporal_cli_0.13.1_linux_amd64.tar.gz`.

**Comment by khalifmahdi** [comment]
Thank you. It's correct.
So the download link should not change, right?

**Comment by cretz** [comment]
While it shouldn't, it's just a facade to the GitHub releases area. If you want a stable link, use a link from GitHub directly on https://github.com/temporalio/cli/releases.

(closing issue, feel free to join us on Slack or the forums with general questions)
