### ISSUE TITLE
Unable to connect to AWS hosted elasticsearch

### ISSUE THREAD

**Issue by kfoxb** [temporalio/temporal#621]
## Expected Behavior
Adding the correct endpoint, port, and scheme to the config pointing to an aws elasticsearch instance should connect and allow advanced visibility features.

## Actual Behavior
Temporal shuts down and an error is reported:
`error creating elastic search client: context deadline exceeded`

## Steps to Reproduce the Problem

  1. Create an aws elasticsearch cluster (https://aws.amazon.com/elasticsearch-service/)
  1. Use the connection information from the cluster in your Temporal config. I'm using the helm chart for this.
  1. Deploy Temporal

## Specifications

  - Version: v0.27.0
  - Platform: Docker/Kubernetes

## Additional Details
After some research and trial and error I think I've found the problem. AWS only supports HTTP for their Elasticsearch instances on port 80 or port 443. Elasticsearch doesn't support sniffing on those particular ports, you need to be using TCP on port 9200.

I found an issue with the upstream Elasticsearch client Temporal is using [here](https://github.com/olivere/elastic/issues/880). The solution proposed in that seemed to work for me. I added just this line `elastic.SetSniff(false)` when creating a new Elasticsearch client and I was able to connect.

To me it seems like the solution is to add a flag to the config to be able to disable this for customers that run Elasticsearch on port 80/443, but I'm opening this issue to see if there are other solutions that may be better.

**Comment by alexshtin** [comment]
Sniffing is disable by default in Temporal. We may add config param later.
