### ISSUE TITLE
Anyone Running Temporal Typescript SDK on Bun?

### ISSUE THREAD

**Issue by ccravens** [temporalio/temporal#6285]
I created the following issue over at Bun: https://github.com/oven-sh/bun/issues/12552

I wanted to see if anyone else in the Temporal community has had success running Temporal Typescript libraries on Bun? I'm getting a Rust crash and have outlined the error in the above mentioned issue. I figure this may be a Bun bug, but maybe there's a slight modification that can be made to the typescript libraries that increase compatibility with the Bun runtime?

**Comment by ccravens** [comment]
Wow, bun 1.1.20 was released just a few hours ago, and running bun upgrade now seems to have resolved this issue. I will close the issue but continue to provide status updates on if I'm able to get Temporal working on the bun Runtime. Thanks!

**Comment by zammitjames** [comment]
Hey @ccravens , were you able to get temporal to run on bun?
