### ISSUE TITLE
Java HelloUpdate example hangs when using `temporal server start-dev`

### ISSUE THREAD

**Issue by awwx** [temporalio/temporal#6352]
https://community.temporal.io/t/java-helloupdate-example-hangs-calling-addgreeting-update/12953/6

## Expected Behavior

The Java HelloUpdate example runs fine when using docker-compose and setting `frontend.enableUpdateWorkflowExecution` in `dynamicconfig/development-sql.yaml`

## Actual Behavior

When using `temporal server start-dev --dynamic-config-value frontend.enableUpdateWorkflowExecution=true` the client hangs at the point of making the first update call, and temporal pegs the CPU.

Temporal log output: https://gist.github.com/awwx/4b375e92da18b3bf57597956560ccc89

## Steps to Reproduce the Problem

Start Temporal using `temporal server start-dev --dynamic-config-value frontend.enableUpdateWorkflowExecution=true`  and run the HelloUpdate sample application.

## Specifications

```
$ temporal --version
temporal version 0.11.0 (server 1.22.4) (ui 2.21.3)
```

In samples-java, I’m on the latest commit

```
$ git log -n1
commit 637c2e66fd2dab43d9f3f39e5fd9c55e4f3884f0 (HEAD -> main, origin/main, origin/HEAD)
Author: Tihomir Surdilovic <tihomir@temporal.io>
Date:   Sun Jul 21 19:55:18 2024 -0400
```

```
$ ./gradlew --version

------------------------------------------------------------
Gradle 8.0.1
------------------------------------------------------------

Build time:   2023-02-17 20:09:48 UTC
Revision:     68959bf76cef4d28c678f2e2085ee84e8647b77a

Kotlin:       1.8.10
Groovy:       3.0.13
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.11 (Ubuntu 17.0.11+9-Ubuntu-1)
OS:           Linux 6.8.0-38-generic amd64
```

**Comment by awwx** [comment]
> Use docker compose to run temporal server and connect to it via client in your java application

Yes, as I said, Temporal run from docker-compose is working. This is a bug report for `temporal server start-dev`

**Comment by Quinn-With-Two-Ns** [comment]
Can you try updating your `temporal server `? You CLI version is multiple releases out of date. The latest is https://github.com/temporalio/cli/releases/tag/v0.13.2

**Comment by awwx** [comment]
> Can you try updating your temporal server ? You CLI version is multiple releases out of date. The latest is https://github.com/temporalio/cli/releases/tag/v0.13.2

I had followed the link in https://learn.temporal.io/getting_started/java/dev_environment/ for "Download Temporal CLI for Linux amd64", which links to https://temporal.download/cli/archive/v0.11.0?platform=linux&arch=amd64

The HelloUpdate example runs correctly when using the latest CLI version 0.13.2

I made a note of the outdated download link in the forum: https://community.temporal.io/t/download-points-to-outdated-cli-version-in-set-up-a-local-development-environment-for-temporal-and-java/13004
