### ISSUE TITLE
User metadata not propagated from child workflow command to child workflow's execution config

### ISSUE THREAD

**Issue by cretz** [temporalio/temporal#6412]
## Expected Behavior

Like start workflow, I would expect start child workflow user metadata to end up on the execution config on the child workflow.

## Actual Behavior

The user metadata only ends up on the event, not the actual child workflow

See https://github.com/temporalio/temporal/pull/5857 where user metadata propagation was added.

**Comment by skovtunenko** [comment]
I found the comment in the Go SDK related to this issue in private fields:
```
		// TODO(cretz): Expose once https://github.com/temporalio/temporal/issues/6412 is fixed
		staticSummary string
		staticDetails string
```

Those are fields in the `ChildWorkflowOptions` struct.
