### ISSUE TITLE
Activity additional info

### ISSUE THREAD

**Issue by bergundy** [temporalio/temporal#6605]
There's a couple of extra fields to help understand the status of a pending activity:

1. Add `last_failure_time` to PendingActivityInfo. Populated once an attempt failure is recorded for any reason that an attempt might fail, including any form of timeout.
2. Add `next_attempt_schedule_time` to PendingActivityInfo. Shown if activity is in backoff state (waiting for retry).

**Comment by ychebotarev** [comment]
3. Add next_retry_interval
