### ISSUE TITLE
Pending update requests should be aborted when workflow times out

### ISSUE THREAD

**Issue by dandavison** [temporalio/temporal#6614]
## Expected Behavior
If the workflow is timed out (due to `workflow_execution_timeout` / `workflow_run_timeout`) between update acceptance and update completion, then I expect pending update requests (`UpdateWorkflowExecution` or `PollWorkflowExecutionUpdate`) to be aborted in a way that signals to SDK clients that they should not continue to poll for the update outcome.

## Actual Behavior
The requests are not aborted, and SDK clients continue to poll indefinitely.

## Steps to Reproduce the Problem

  1. Create a workflow with an update handler that "never completes" (e.g. waits on a 60s timer)
  1. Start the workflow, with `workflow_execution_timeout` or `workflow_run_timeout` set to a few seconds.
  1. Start an update, waiting until `Completed`
  1. Wait until the workflow times out, and observe that the update request is not failed but rather times out naturally (if you are using an SDK client you may not see this, since the client issue repeated poll requests behind the scenes).

## Specifications

  - Version: latest server `main`

**Comment by bergundy** [comment]
Fixed in #6621
