### ISSUE TITLE
Configuration of Cassandra ConnectTimeout

### ISSUE THREAD

**Issue by Ryan-Thomas** [temporalio/temporal#662]
https://github.com/temporalio/temporal/blob/34948aedf5db069627e956348cc56a6dbf49b0bf/common/service/config/config.go#L240

Can you add ConnectTimeout configuration to Cassandra config? 

Would work something like this in `cassandraCluster.NewCassandraCluster`
```
	if cfg.ConnectTimeout != "" {
		connectTimeout, err := time.ParseDuration(cfg.ConnectTimeout)
		if err != nil {
			log.Fatalf("Error parsing Cassandra Connect Timeout: %v", err)
		}
		cluster.ConnectTimeout = connectTimeout
	}
```

**Comment by vitarb** [comment]
@Ryan-Thomas thanks for the feature request, I've added this config option on the server side, luckily standard yaml parser already supports time. Duration so there is no need for any additional parsing code.
Please check it out once it lands and let us know if you have any issues.
