### ISSUE TITLE
Ambiguous "context deadline exceeded" error cause on the CLI during server failures

### ISSUE THREAD

**Issue by vitarb** [temporalio/temporal#663]
## Expected Behavior

* Actual error details are displayed to the user.
* User shouldn't have to wait for the context deadline to be exceeded if server error has occurred and CLI should return immediately.

## Actual Behavior

CLI times out and displays ambiguous error saying "Error Details: context deadline exceeded"
Specifying `TEMPORAL_CLI_SHOW_STACKS=1` does not provide any useful details.
Actual error cause can only be found in the server log.

## Steps to Reproduce the Problem
I was able to reproduce this problem by performing a reset on an invalid event id, but I'm sure there are more scenarios that can cause this issue.

**Comment by samarabbas** [comment]
This issue is not specific.  I think we have made numerous around error handling so this might already been fixed.  Please re-activate the issue with specific details if this is still a problem for particular scenario.
