### ISSUE TITLE
Use dependency injection

### ISSUE THREAD

**Issue by alexshtin** [temporalio/temporal#67]
Currently we have [resource](https://github.com/temporalio/temporal/tree/master/common/resource) which essentially implements [service locator](https://en.wikipedia.org/wiki/Service_locator_pattern) which is anti-pattern in the most cases including ours. Same pattern is also used in few other places such as [RPCFactory](https://github.com/temporalio/temporal/blob/master/common/rpc.go).

The good alternative is to use [dependency injection](https://en.wikipedia.org/wiki/Dependency_injection). It requires dependency container. [Wire](https://github.com/google/wire) is a compile time dependency container from Google.

**Comment by yiminc** [comment]
This is done with uber fx.
