### ISSUE TITLE
TCTL command truncates workflow activity input/output with ellipses

### ISSUE THREAD

**Issue by mastermanu** [temporalio/temporal#678]
This can be quite frustrating. Prime example is that rather than printing the whole object, part of it are truncated with "..."

We should either stop doing the truncation or add a flag that lets us pretty print the full output. The workaround at this point is to output the file to a local json file, so this is probably lower priority.

**Comment by samarabbas** [comment]
@feedmeapples can you confirm if this is still applicable after the CLI redesign work you are doing?

**Comment by feedmeapples** [comment]
i'm going to have a unified flag to set a limit beyond which texts in Table/Card are going to be truncated. It's not yet implemented but tracked. I think we can close this issue and track through proposals/new UX implementation
