### ISSUE TITLE
Add `MaximumUpdatesPerExecution` to protect number of updates can accepted/admitted in a workflow execution.

### ISSUE THREAD

**Issue by longquanzheng** [temporalio/temporal#6872]
**Is your feature request related to a problem? Please describe.**
Similar to [MaximumSignalsPerExecution](https://github.com/temporalio/temporal/blob/c1e2206371b34804c05cdcf9c7788ba58e18333d/common/dynamicconfig/constants.go#L1984C2-L1984C28) , we need to add protection for updates on a single execution. Otherwise, the history could be blown up due to constant incoming requests and no chance for continueAsNew to complete(workflow task complete will be rejected).

Note that it should also count the updates that are carried over from rest(Admitted events).

**Describe the solution you'd like**
Just Add it the same way as MaximumSignalsPerExecution.

**Describe alternatives you've considered**
There is no alternatives unless no using updates.

**Additional context**

**Comment by stephanos** [comment]
Is `history.maxTotalUpdates` what you're looking for?

See https://github.com/temporalio/temporal/blob/c1e2206371b34804c05cdcf9c7788ba58e18333d/common/dynamicconfig/constants.go#L1947C2-L1951C3
