### ISSUE TITLE
Scheduling a Workflow Timer that exceeds the Workflow Execution Timeout should (potentially) fail

### ISSUE THREAD

**Issue by mastermanu** [temporalio/temporal#690]
There is no valid scenario where one should schedule a timer that goes beyond the remaining time the Workflow is allowed to execute. That seems like an unintentional business logic if this happens. Ideally we provide validation and fail the timer creation if this happens (or at least add a boolean where a user can opt-in to validation or auto-capping the timer to the minimum of remaining execution time vs. specified duration)

**Comment by wxing1292** [comment]
current behavior is NOT to schedule the timer is timer will fire after workflow timeout
