### ISSUE TITLE
Custom Tags addition in existing Metric using java sdk is not working

### ISSUE THREAD

**Issue by techFool** [temporalio/temporal#695]
Please refer to https://community.temporal.io/t/how-to-add-custom-tags-in-existing-temporal-metric-using-java-sdk/516 .

We are trying to add the custom tags but its not getting appeared in the metrics

**Comment by kkcmadhu** [comment]
any idea when this can be fixed?

**Comment by vitarb** [comment]
Closing as a duplicate of https://github.com/temporalio/sdk-java/issues/200
Please read correspondence provided there for more details.
