### ISSUE TITLE
MutableState cleanup to remove unused fields

### ISSUE THREAD

**Issue by samarabbas** [temporalio/temporal#702]
start version / last write version / current version can all be deleted here, since this is modifying the concrete mutable state record.

there is another function, `createOrUpdateCurrentExecution`, you can remove the start version from that function.
the 2 lines to be removed:
https://github.com/temporalio/temporal/blob/36525fad464757f59d1e963ccba3b3c46aff0e33/common/persistence/sql/sqlExecutionManagerUtil.go#L574
https://github.com/temporalio/temporal/blob/36525fad464757f59d1e963ccba3b3c46aff0e33/common/persistence/cassandra/cassandraPersistenceUtil.go#L964

**Comment by wxing1292** [comment]
there are other attr not really being used, close this specific issue, we will handle the e2e cleanup later
