### ISSUE TITLE
Blank namespace in the history event for childworkflow

### ISSUE THREAD

**Issue by darewreck54** [temporalio/temporal#724]
When querying the History Event, it looks like the child workflow's namespace isn't being populated in the attributes.

## Expected Behavior
I expect to see the namespace be not blank,  It should be same as the initial query where I had to specify it

## Actual Behavior
the namespace is blank

![image](https://user-images.githubusercontent.com/16171726/92997116-998b4f80-f4c5-11ea-8985-0568f38ad7fe.png)

## Steps to Reproduce the Problem

1. I first query to get the history based on a specific namespace and workflow ID

```
  GetWorkflowExecutionHistoryRequest request = GetWorkflowExecutionHistoryRequest.newBuilder()
                .setNamespace(namespace)
                .setHistoryEventFilterType(HistoryEventFilterType.HISTORY_EVENT_FILTER_TYPE_ALL_EVENT)
                .setExecution(WorkflowExecution.newBuilder().setWorkflowId(workflowId))
                .build();
```
2. I then take a child workflows

```
    List<HistoryEvent> childEvents = events.stream().filter(x -> x.getEventType() == EventType.forNumber(EventType.EVENT_TYPE_START_CHILD_WORKFLOW_EXECUTION_INITIATED_VALUE)).collect(Collectors.toList());
   
```
I then try to take the attributes of one of the child events

3. ```
 StartChildWorkflowExecutionInitiatedEventAttributes attributes = childEvent.getStartChildWorkflowExecutionInitiatedEventAttributes();
                String nodeWorkflowId = attributes.getWorkflowId();
                String nodeWorkflowNameSpace = attributes.getNamespace();

```


## Specifications

  - Version: 0.29
  - Platform:

**Comment by wxing1292** [comment]
Issue cannot not be reproduced in v1.2.1
close
