### ISSUE TITLE
Use a code-generator for boilerplate/'generic' code

### ISSUE THREAD

**Issue by shawnhathaway** [temporalio/temporal#76]
In many parts of the codebase we have very boilerplate code that is hand-maintained. Some offending examples:

persistenceRateLimitedClients - https://github.com/temporalio/temporal/blob/9c9ae82affc728f0e3466bb00e70bc4ddae1b050/common/persistence/persistenceRateLimitedClients.go

persistedMetricsClient - https://github.com/temporalio/temporal/blob/9c9ae82affc728f0e3466bb00e70bc4ddae1b050/common/persistence/persistenceMetricClients.go

resourceImpl - https://github.com/temporalio/temporal/blob/9c9ae82affc728f0e3466bb00e70bc4ddae1b050/common/resource/resourceImpl.go

Using a code generator in some of these places would be very beneficial to future development speed and safety by keeping changes in one place.

**Comment by rylandg** [comment]
That code could definitely be a lot DRYer but is code gen really the right option? It would definitely work but IMO refactoring the code would be cleaner if possible. That being said I'm not super familiar with Go so maybe code gen is the right call.
