### ISSUE TITLE
No way to install in tctl binaries in windows? 

### ISSUE THREAD

**Issue by anborg** [temporalio/temporal#781]
> To build the CLI tool locally, clone the Temporal server repo and run make bins.

How to install in tctl in windows? How can I compile with `make` for Windows? Is there a Windows binary? (I don't want to use docker at the moment.)

**Comment by alexshtin** [comment]
`make tctl` is simple:
```
go build -o tctl cmd/tools/cli/main.go
```
This should work on Windows.

**Comment by joshnoe** [comment]
FYI this no longer works? Win dist. or less painful way to run tctl would be much appreciated!

**Comment by joshnoe** [comment]
Long term, a Win dist for tctl would be really appreciated. Instructions for building it locally will inevitably become out of date. And using tctl through Docker can be pretty involved when you need to install certs etc.
