### ISSUE TITLE
Enable Serialization on WorkflowQueue

### ISSUE THREAD

**Issue by godhavari** [temporalio/temporal#792]
**Is your feature request related to a problem? Please describe.**
Java-SDK
In the following community thread.
https://community.temporal.io/t/workflow-await-does-it-release-thread/252
To continually process events on a specific entity in the order we received the events, we can use WorkflowQueue. To implement this solution, we need WorkflowQueue to be serializable. At this time we can not use this technique as the WorkflowQueue is not implementing Serializable. The main purpose of this technique is to avoid long running workflows.

**Describe the solution you'd like**
Enable Serialization on WorkflowQueue 

**Describe alternatives you've considered**
Using Java Queue for now

**Additional context**
I received the above details from @maxim in one of my conversation in slack channel. Creating this ticket to make sure this requirement is addressed as part of the future releases.

**Comment by mfateev** [comment]
Moved to Java SDK repo
