### ISSUE TITLE
Validate pings from different cluster does not result in joining the membership ring

### ISSUE THREAD

**Issue by samarabbas** [temporalio/temporal#857]
**Is your feature request related to a problem? Please describe.**
Have cluster name in the config which is used to initialize Ringpop as the App Name.  Also
make sure this results in pings from nodes in different clusters being rejected and not 
mistakenly end up joining the membership ring.

**Describe the solution you'd like**
Add ability to pass in cluster name which is used to initialize Ringpop AppName.

**Describe alternatives you've considered**

**Additional context**
https://github.com/uber/ringpop-go/pull/206

**Comment by wxing1292** [comment]
close in favor of #1234
