### ISSUE TITLE
Failure to connect to ElasticSearch on startup should not fail startup

### ISSUE THREAD

**Issue by kelnos** [temporalio/temporal#863]
If ES is configured, and the ES cluster is unavailable for any reason, Temporal refuses to start up at all.  Obviously ES being unavailable isn't great, but since Temporal queues ES writes to Kafka, it doesn't strictly _need_ ES in order to avoid data loss.

Obviously the ES cluster being down is an odd occurrence; ideally (especially in production) that would never happen.  But in a major outage scenario I think Temporal being a little more tolerant of failures of its dependencies would be useful.  If ES is down and I need to replace Temporal nodes due to (for example) an AWS AZ outage, currently I can't do that.

(As a real example, my ES cluster went down in my development environment right now, and I'm trying to test some changes to Temporal that require restarting it, but I'm sitting here waiting for another team to fix the ES cluster without making progress, because Temporal won't start at all.)

**Comment by mastermanu** [comment]
Hey Kelnos,

Please see the linked PR request. It includes a change to the Server and the addition of a variable in the docker startup script (assuming you are hosting on Docker) to workaround getting blocked their too.

**Comment by kelnos** [comment]
Oh, fantastic, what amazing timing.  Looking forward to seeing that in the next release :)
