### ISSUE TITLE
Refactor Failure representation in the APIs

### ISSUE THREAD

**Issue by mfateev** [temporalio/temporal#89]
Currently failures in all customer facing proto structures (not gRPC ones) are represented by two fields `reason` and `details`. This kind of works when all parts of a workflow are implemented in a single language. For example Java SDK serializes complete exception chain including stack trace of each exception into the details field. The problem is this serialization/deserialization code is completely Java specific. Now as Python client is added it uses different format for the stack trace. Go (in case of panic) also might require stack trace serialization/deserialization. Even without stack traces chaining of errors coming from SDKs in different languages is practically impossible without unifying the serialization format.

The proposal is that instead of unifying the serialization format, model the chain of errors with attached strack traces through a generic protobuf structure. This way no language specific serialization is necessary and errors coming from different components can be chained even if they are from different languages.

The strawman API changes.
```
message ApplicationFailureInfo {
    string sdk = 1; // java, go, python, etc
    string message = 2;
    string type = 3; // Exception class,  Go error type, etc.
    bytes details = 4; // Possibly error payload beyond the message.
}

message ActivityTaskFailureInfo {
    int64 scheduledEventId = 1;
    int64 startedEventId = 2;
    string identity = 3;
}

message ChildWorkflowExecutionFailureInfo {
    string domain = 1;
    WorkflowExecution workflowExecution = 2;
    WorkflowType workflowType = 3;
    int64 initiatedEventId = 4;
    int64 startedEventId = 5;
}

message Failure {
    oneof failureInfo {
        ActivityTaskFailureInfo activityTaskFailureInfo = 1;
        ChildWorkflowExecutionFailureInfo childWorkflowExecutionFailureInfo = 2;
        ApplicationFailureInfo applicationFailureInfo = 3;
    }
    repeated string backtrace = 4;
}

message FailureChain {
    repeated Failure failures = 1; // The initial cause is the first in the list
}
```
An open question if providing a typed backtrace would bring any value. For example it can be modeled as 
```
message StackTraceElement {
    string file = 1;
    int32 line = 2;
    string component = 3; // declaringClass for Java, module for Go
    string function = 4;
}
```
But it might require more fields for some languages for example PHP stack trace is much reacher:
https://www.php.net/manual/en/function.debug-backtrace.php

**Comment by firdaus** [comment]
I can't think of a use case for a typed backtrace. 

ApplicationFailureInfo, Failure and FailureChain look good to me.

**Comment by dadgar** [comment]
@mfateev It would be good to add a `retryable bool` to `ApplicationFailureInfo`.

**Comment by alexshtin** [comment]
Proto changes: https://github.com/temporalio/temporal-proto/pull/43

**Comment by alexshtin** [comment]
Go SDK PR: https://github.com/temporalio/temporal-proto/pull/43
