### ISSUE TITLE
Postgres password should be escaped (special characters) 

### ISSUE THREAD

**Issue by nadilas** [temporalio/temporal#903]
Hello,

there is an issue when postgres password contains special characters (using cockroachdb):
```
net/url: reject invalid userinfo values when parsing URLs
```

Password should be escaped:
https://github.com/temporalio/temporal/blob/e92adc008ca4a77463b3f479a9d53c6263d25228/common/persistence/sql/sqlplugin/postgresql/plugin.go#L105

`url.QueryEscape(cfg.Password)`

**Comment by HarshitaDPoojary** [comment]
Hi,
I would like to work on this issue.
I have refereed to use of [QueryEscape](https://golang.hotexamples.com/examples/net.url/-/QueryEscape/golang-queryescape-function-examples.html)

Thanks.

**Comment by HarshitaDPoojary** [comment]
Hi I had tried to create a [pull request](https://github.com/temporalio/temporal/pull/2014) but it threw an error in build stage in [BuildKite](https://buildkite.com/temporal/temporal-public/builds/1041#1f96c35b-bcd3-4c7a-a50b-60d74678b4b5)
```

common/persistence/sql/sqlplugin/postgresql/plugin.go
  | make: *** [Makefile:232: goimports-check] Error 1

```
Kindly help me in resolving the issue.

**Comment by yiminc** [comment]
The buildkite error was about goimports. You can fix it by run `make goimports` in the repo's root directory.

**Comment by HarshitaDPoojary** [comment]
Thanks @yiminc  it worked.
