### ISSUE TITLE
Is there an example for using temporal to implement a human involved task?

### ISSUE THREAD

**Issue by tonyabracadabra** [temporalio/temporal#906]
For example, I want to implement a workflow that involves getting approval from someone, for example, first I would trigger the task, then send it to someone waiting for his approval, upon his approval we can move to the next step based on the approval status.

**Comment by dnakov** [comment]
@tonyabracadabra 
https://github.com/temporalio/samples-go/tree/master/expense

**Comment by tonyabracadabra** [comment]
> @tonyabracadabra
> https://github.com/temporalio/samples-go/tree/master/expense

Thanks a lot! I’ve read through the comments, is it recommended to use pub sub for listening to the events to trigger the workflow? I’m planning to use redis for this case. I’ve also seen `GetSignalChannel`, is this also related to the scenario that I’m talking about?

**Comment by MrSaints** [comment]
Ideally, you should not need Redis or any external pub sub to trigger the workflow. 

Also, here are some comments on the matter:

https://community.temporal.io/t/signalling-system-human-driven-workflows/160

https://community.temporal.io/t/handling-user-feedback-retries-and-timeouts/172

**Comment by tonyabracadabra** [comment]
> Ideally, you should not need Redis or any external pub sub to trigger the workflow.
> 
> Also, here are some comments on the matter:
> 
> https://community.temporal.io/t/signalling-system-human-driven-workflows/160
> 
> https://community.temporal.io/t/handling-user-feedback-retries-and-timeouts/172

Thanks a lot!
