### ISSUE TITLE
Allow signalling external workflow with no input

### ISSUE THREAD

**Issue by mfateev** [temporalio/temporal#91]
There is no reason to enforce input when workflow signals an external workflow as it is already allowed when signalling from outside:

```
cause BAD_SIGNAL_WORKFLOW_EXECUTION_ATTRIBUTES
details "BadRequestError{Message: Input is not set on decision.}"
```

**Comment by MichaelSnowden** [comment]
This was already fixed by: https://github.com/temporalio/temporal/commit/84c85cd00e08d0084b2f18ee632d2ddee7ad66a6
