### ISSUE TITLE
Emit workflow completion metric on ContinueAsNew due to Cron or Retry

### ISSUE THREAD

**Issue by samarabbas** [temporalio/temporal#937]
## Expected Behavior
Temporal converts completion of workflow into ContinueAsNew event if there is a cron
or retry policy attached to the execution.  This is confusing as workflow failure is not
reported as `workflow_failed` counter when it does ContinueAsNew due to retry or
cron policy on the execution.

## Actual Behavior
`workflow_failed` counter is emitted for workflows with cron or retry policy. 

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:

**Comment by wxing1292** [comment]
ref: https://github.com/temporalio/temporal/blob/v1.13.0/service/history/workflow/transaction_impl.go#L466
