### ISSUE TITLE
CLI "namespace register" and "namespace update" should allow more granular retention periods

### ISSUE THREAD

**Issue by rfwagner** [temporalio/temporal#943]
The CLI "namespace register" and "namespace update" commands both allow specification of the namespace retention period using the "--retention" flag. The value for this flag is retention period in number of days. It is not possible to use the CLI to specify a retention period of less than a day.

In any number of testing scenarios it would be very useful to specify a sub-day retention period so that we can easily observe the effects of the cleanup process.

Please enhance the CLI to allow sub-day granularity (at least down to the minute) in both the "namespace register" and "namespace update" commands.

**Comment by yiminc** [comment]
This is supported. Retention could be specified as `--retention 30h` for example
