### ISSUE TITLE
CLI "namespace update" incorrectly reports success when specifying non-day retention period

### ISSUE THREAD

**Issue by rfwagner** [temporalio/temporal#944]
The CLI only accepts integer values for the "--retention" flag, representing retention period in days.

Before I realized this, I tried several variations along the lines of:

```
$ tctl --namespace default namespace update --retention 0h10m0s
Namespace default successfully updated.
```

Notice that the CLI reported success when in fact the retention period had not been updated (presumably because it failed to parse the supplied retention value as an integer).

**Comment by fghpdf** [comment]
I think this problem had been solved now.

version: 1.16.1

I run update command and then it works:
```
Name: default
Id: 8918f255-88f8-46a7-93ba-8ce19fe0556c
Description: Default namespace for Temporal Server.
OwnerEmail:
NamespaceData: map[string]string(nil)
State: Registered
Retention: 10m0s
ActiveClusterName: active
Clusters: active
HistoryArchivalState: Disabled
VisibilityArchivalState: Disabled
```

**Comment by yiminc** [comment]
This problem is fixed.
