### ISSUE TITLE
How to configure to reduce scheduling time.

### ISSUE THREAD

**Issue by a18401626205** [temporalio/temporal#984]
My performance test is not good.
Is there any configuration that can significantly improve performance. To reduce scheduling time.
thanks!!!

My configuration:
Log level: info
Number of work: 50
Block execution of 3 localActivity
Number of clusters: 3

ab -c 10 -n 1000
The whole process is within 1s, this is OK

![1](https://user-images.githubusercontent.com/71421997/98933370-7e67ab00-251b-11eb-9a99-db1d7c58d6ab.png)
localActivity:DoSendSms

but
ab -c 50 -n 1000
The whole process is around 5s

![2](https://user-images.githubusercontent.com/71421997/98933382-81629b80-251b-11eb-9c42-de08a864b02f.png)

ab -c 100 -n 10000
The whole process is about 10s

**Comment by a18401626205** [comment]
It seems that the bottleneck is not in bandwidth, cpu, disk, disk io...

**Comment by samarabbas** [comment]
There is some content on benchmarking Temporal server.  I would recommend to start with the tool we open sourced:

- [Load Simulator](https://github.com/temporalio/maru)
- [Blogpost on the tool](https://mikhail.io/2021/03/maru-load-testing-tool-for-temporal-workflows/)
- [Choosing number of shards](https://mikhail.io/2021/05/choose-the-number-of-shards-in-temporal-history-service/)

If this does not help please reach out on [forums](https://community.temporal.io/).
